### ISSUE TITLE
Make Colormap shader efficient by using 1D Textures

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#1052]
As discussed in [this pull request thread](https://github.com/vispy/vispy/pull/1044), the current implementation of Colormaps generate a chain of `if-then-else` which is very expensive as the number of control points increases.

Ideally, the colormap gradient is computed once, and is stored as a 1D texture which is used to map texture coordinates to the corresponding color for the `cmap.glsl_map` function that maps texcoords to colors.

**Comment by kmuehlbauer** [comment]
Is it possible to use one Texture2D with all available colormaps inside, so that one colormap covers one "row"? 

I recently worked with the spatial filtering, where the available filter kernels (1D) are combined in a Texture2D. The interpolation kernels are computed once and stored. Could this work for colormaps too?

**Comment by rougier** [comment]
One problem may be texture interpolation. You want bilinear in horizontal direction and nearest in vertical direction. One possibility would be to have 3 lines height for each colormap (to be tested)

**Comment by bollu** [comment]
Interesting idea, but I think we allow people to create custom colormaps as well. How would that work? Would we resize the texture and add an extra row?

What you're suggesting is similar to atlasing, correct? but that's only possible when you know all the resources you'd need beforehand. That's not really the case here.

Plus, isn't it more expensive bandwidth-wise to send a tex2d?

**Comment by Eric89GXL** [comment]
@rougier could we guarantee to hit the center of each pixel in the Texture2D in the vertical direction, so that we effectively achieve `nearest` (since the weight would be `1.` on the proper row) in the vertical direction while still having `linear` in the horizontal, or is that not practically achievable?

**Comment by kmuehlbauer** [comment]
I admit, that I didn't thought about other possible constraints.

**Comment by Eric89GXL** [comment]
@bollu we could make the texture 1024x1024 or maybe 2048x2048, and thus have a upper limit of 1024 or 2048 colormaps, which doesn't seem too bad :) Seriously though, if we did hit a use case beyond that (although I'd argue YAGNI until I saw it), we could set it up so that it keeps a record of a list of textures to use, and then it would be unlimited up to the memory/capabilities of the device.

**Comment by Eric89GXL** [comment]
@rougier if the precision isn't there to hit the center of each pixel in the Texture2D, couldn't we at worst need 2 rows per colormap, and put our point directly in between adjacent rows? That would only lose us half the storage, which still isn't bad.

**Comment by rougier** [comment]
Yes, maybe 2 rows could be enough.

**Comment by Eric89GXL** [comment]
That sounds like the way to go to me, then. @rougier do you think it would be better to use a 1024x1024 or 2048x2048? Do you know if 2048x2048 would be supported by most devices? I don't know enough about OpenGL ES devices to know...

**Comment by Eric89GXL** [comment]
BTW in implementing this, we should also address the idea that fonts should have a single atlas per context. Right now I'm not sure how we do it, but this would be another situation where you really only need one of these textures per context. Or multiple ones if extra storage is needed, but the idea is that each context should have a single, shared Texture or set of Textures it uses for storage. This issue could be tackled all at once hopefully.

@almarklein if we wanted to make it so that each context had some global Textures (for text SDF renderings and now Colormap control point storage), would we attach them to a GLIR instance or something?

**Comment by rougier** [comment]
1024 is already huge. 512x512 should be more than enough to hold all colormaps (256 different colormaps is a lot)

**Comment by almarklein** [comment]
@Eric89GXL you want to store such objects at `context.shared`.

The number of colors in a colormap should be sufficient so that linearly interpolation of the colormap-texture is smooth enough (or resembles the intended colormap close enough). Given that the human eye can only discern so many color levels, I think 256 is already pretty large. Or would there be a use-case for larger colormaps? If there is (which I think would be a rare use-case), then 512 might not be enough either? Maybe we should just use an Nx256 texture for "normal" cases, and provide an alternative route for situations which require huge colormaps?

As for the number of colormaps, we should have enough room to fit all our buildin colormaps + a few custom ones. So 128 already seems sufficient, I think. We can crank this up later if desired.

I'm pretty sure that if you get your texture coordinate right, you get the exact value for a pixel in a texture, so you *should* be able to pack one colormap per row. However, maybe there is a buggy driver somewhere out dare for which this does not hold :) Given that memory is not much of a problem, I agree we should just use two rows per colormap.

**Comment by campagnola** [comment]
What is the benefit to putting all colormaps into one texture? This makes the code more complex, especially for the case of user-defined and rapidly updating colormaps.

**Comment by rougier** [comment]
For user-defined and rapidly updating colormaps that would not change much. You only need to update two line instead of two.

**Comment by campagnola** [comment]
For example: we allocate a 512^2 texture for colormaps. What happens if a user wants more steps in their lookup table (perhaps for densely-packed colors), or when we run out of room in the texture because the user is dynamically generating many colormaps? Then we need extra code to switch to a different texture. It seems easier to just upload a single texture for each colormap, and optionally share those textures when possible.

**Comment by Eric89GXL** [comment]
I'm fine with that approach, too. So the idea is to use a `Nx1` Texture2D for each `Colormap` instance that needs texture lookups, where `N` is the lowest power of 2 that will fit all the control points? At least to start we can not worry about the shared texture case, and optimize it later when a user needs e.g. hundreds of objects that share the same colormap.

**Comment by HENDRIX-ZT2** [comment]
Doesn't [this example](https://github.com/vispy/vispy/blob/cfaf9d34761f4a6d234a67d5a6fee9dcf2b20f57/examples/demo/gloo/imshow.py) do pretty much what you'd want here? As far as I understand, it packs several colormaps into a texture2D and then uses that texture for the color lookup in the fragment shader. Or is there more to it?

**Comment by larsoner** [comment]
Yes it does, it's a matter of implementing it so it gets tracked properly (e.g., one per OpenGL context, etc.) and utilized properly by each `Visual` instance. I think something similar to what is done for SDF rendering can be done for this.

**Comment by larsoner** [comment]
#1397 could be addressed at the same time as this

**Comment by djhoese** [comment]
Not sure how this fell through the cracks, this has been implemented by #1457 a while ago. Soon to be released as part of 0.6.
