### ISSUE TITLE
Issues with HiDPI displays (using PyQt5)

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1063]
I tried the ``examples/basics/plotting/plot.py`` example with PyQt5 on a HiDPI screen, and this is the output:

<img width="714" alt="screen shot 2015-08-17 at 9 44 12 pm" src="https://cloud.githubusercontent.com/assets/314716/9314429/2012512c-4529-11e5-8038-0eb95385440d.png">

It looks like some of the plotting code must be making assumptions about a fixed non-HiDPI DPI value.

**Comment by nippoo** [comment]
Blarp. I went through and fixed everything on GLFW by adding a `physical_size` attribute in https://github.com/vispy/vispy/pull/787 so the examples should be HiDPI-capable... fingers crossed, it should just be a matter of making PyQt5 set the correct `physical_size` attribute as the framebuffer size. Looks like this is the issue here but it might be more subtle than that. I won't have time for 2 weeks...

**Comment by astrofrog** [comment]
Fixed in #1103, thanks @theWatchmen!
