### ISSUE TITLE
vispy/util/svg/geometry.py: BSD (2 clause) GPL (v2 or later)

### ISSUE THREAD

**Issue by picca** [vispy/vispy#1065]
Hello guyes, I am preparing the debian package of the 0.4.0 version took from pypi.
since I need to do a license check before uploading, I found this discrepancy.
The original license is GPL2+ and you added a BSD-2 clauses on top of that. 
Do you have an email of the original author which allow to relicense his code into BSD ?

cheers

Fred

**Comment by Eric89GXL** [comment]
ping @rougier this is from the SVG code

**Comment by rougier** [comment]
I'm the one that has written this file. It's a translation from the C++ antigrain library 2.4 which was BSD but the 2.5 version switched to GPL (but the code for this file is the same). But anyway, since it is a translation (from C++ to python with a fair amount of work), do we need to keep the original license anyway (I kept it just to point to the original work) ?

And as a matter of fact, the original author of the antigrain library, Maxim Shemanarev, is dead.

**Comment by picca** [comment]
To my understanding translation is like a derivativ work of the original author. so yes you need to keep the original verion license. If you started your work from the 2.4 version which was BSD as you said it is ok,but if you started the work from the 2.5 version it is not :(.

frommy point of view having it GPL2+ is not an issue, but from the point of view of the vispy team i could be an issue :)

**Comment by Eric89GXL** [comment]
Since the source code for that file was identical between 2.4 and 2.5 (other than the license clause), can the code considered dual licensed, then? If it is, then it seems like we should be able to put in either the BSD license clause or the GPL license clause for the translated code. In other words, we can just swap the license notice in `vispy` since the translation was based on dual BSD/GPL licensed code in the first place. @picca does that sound right to you?

**Comment by picca** [comment]
I would says that if the file did not changed between 2.4 and 2.5 you selec one license but not dual license.
In you case you should select BSD in order to release vispy as BSD and not GPL.

cheers.
can you put in that case the original  BSD header in te files ?


I know I know this is borring but it is quit eimportant.

cheers

and thanks

**Comment by Eric89GXL** [comment]
@picca I agree. I could push a simple commit and release `0.4.1` to `pip`, would that work?

What is your timeline for inclusion, by the way? If it's a month or two before anything comes of it, we could try to push out a new version `0.5` before then. There have been lots of bugfixes, enhancements, and changes.

**Comment by picca** [comment]
I have no time line :),  I can do the 0.4.0 upload with the GPL header now and wait until 0.5.0 to do the correction later.

It would be nice to have also the doc and the examples in the pypi version.
could you check also if all the vispy/ext/*.py are still relevant ?
We (dbian) do ot like embeded code, so it would be great if your could get rid of them as much as possible.

We do not like also minified code, expecially in the documentation, do you think that it would be possible to have in pypi an option during the build which I could use in order to give the debian system path of the twitter javascript code ?

**Comment by Eric89GXL** [comment]
@QuLogic has done some work to make it so that some of the `vispy/ext` packages can be removed. Basically the entire `vispy/ext/_bundled` directory can be deleted:

https://github.com/vispy/vispy/tree/master/vispy/ext/_bundled

Is there some way to mark this as the case for Debian packaging, or otherwise make it easier? We want to have them in the repo for most installs so that our only hard dependency is `numpy`, but for things like Debian we can make use of system packages instead.

I was under the impression that most packages don' include those things with the PyPi versions.

What twitter JavaScript code are you referring to?

**Comment by Eric89GXL** [comment]
> I was under the impression that most packages don' include those things with the PyPi versions.
Stupid early post. What I meant to say was, I was under the impression that most packages don't include `doc` and `examples` with their PyPi versions. Does e.g. `matplotlib` include the `doc` and `examples` in their PyPi uploads?

**Comment by picca** [comment]
I was refering to the bootstrap code used in skimage them, but it seems that it is no longer part of the code of vispy.


you are right the debian package of matplotlib comes fromsourceforge
version=3
opts="uversionmangle=s/rc/~rc/" \
http://sf.net/matplotlib/matplotlib-(.+)\.tar.gz

nevertheless it would be great to add the example directory in the pipy lik ein the git repository.
It is great to test vispy  for a new comer.

**Comment by picca** [comment]
Great for the _bundle, I can remove automatically this directory during the debian import.
then I see this kind of code.

try:
    from ._bundled.freetype import *  # noqa
except ImportError:
    from freetype import *  # noqa

Why don't you try the official version and then fallback to the _bundle one instead of doing the invert ?

**Comment by Eric89GXL** [comment]
@QuLogic did you have a reason for that order?

One potential reason is that we know that the bundled ones work with our software. We do have a Travis run that deletes that directory and installs the dependencies so it shouldn't be a big deal, though.

**Comment by rougier** [comment]
No obvious reason I would say. There was a problem with previous version of freetype but I made a new release since then. Maybe those lines date back from before the release.

**Comment by QuLogic** [comment]
I don't think there was any particular reason, but as @Eric89GXL says, it does mean that everything should work out of the box. Only packagers would care about the `_bundled` directory _and_ actually bother to delete it, and one hopes they know how to test their own packages before releasing them.

**Comment by picca** [comment]
yes using unit tests ;)
