### ISSUE TITLE
"cutting" volume data

### ISSUE THREAD

**Issue by raacampbell** [vispy/vispy#1076]
For datasets describing a solid 3-D volume, such as an MRI brain scan, it is very useful to be able to "cut" the volume to image its internals. e.g. something like the MATLAB [isocaps](http://uk.mathworks.com/help/matlab/ref/isocaps.html) command or the [slice](http://uk.mathworks.com/help/matlab/ref/slice.html) command. 3-D max intensity projections are pretty but lose a lot of detail. 

I imagine I could probably get _something_ vaguely functional if I could add a 2D image at the correct location in an isosurface plot or even embed it in a 3-D max intensity plot. Is there any easy(ish) way of placing 2-D images in this manner?

**Comment by Eric89GXL** [comment]
You should be able to do it with an `MatrixTransform` that rotates, scales, and/or translates the 2D image. You would take an `image = Image(...)` in a scene and set the `image.transfrom = ...` property to be some suitably configured transform function. Can you give it a try?

BTW we do have an MRI volume available as part of our dataset, it would be really cool if you could see how far you could get it to act like you suggest.

**Comment by raacampbell13** [comment]
Sounds like a good learning experience. I'll give it a shot.

**Comment by kmuehlbauer** [comment]
@raacampbell13 
I've similar requirements with 3D volume data (1000x1000x100). At the moment I have top view and side view and the ability to have arbitrary cuts. The calculation of the arbitrary cut is done on the CPU, slow. It seems that we have similar objectives. Should we join forces, WDYT?

**Comment by raacampbell13** [comment]
@kmuehlbauer Sounds good! The data sets I'm working with right now are roughly the size of yours. For a lot of what I do, 2-D slices through 3-D volume are the most useful. So I'm writing this tool: https://github.com/raacampbell13/lasagna What I'd like, however, is a 3-D view of some sort to go along with the three 2-D views. Hence this issue. If what I'm doing looks useful to you, we can take that discussion off-line.

**Comment by raacampbell13** [comment]
I got the image into place but it looks like I still need to make the regions outside of the brain transparent. Is this possible?
![mri](https://cloud.githubusercontent.com/assets/5427811/9520672/7f45fec6-4cc9-11e5-8a9b-e5f6430a0a6f.jpg)

**Comment by Eric89GXL** [comment]
You could plot the image with a custom grayscale colormap where the black / almost-black values have an alpha of zero.

**Comment by kmuehlbauer** [comment]
You could use this little filter (derived from the Alpha-Filter). This makes the black transparent.

```
class BlackToAlpha(object):
    def __init__(self):
        self.shader = Function("""
            void apply_alpha() {
                // perception
                const vec3 w = vec3(1, 1, 1);
                float value = dot(gl_FragColor.rgb, w);
                if ( value == 0) {
                    gl_FragColor.a = 0;
                }
            }
        """)

    def _attach(self, visual):
        self._visual = weakref.ref(visual)
        hook = visual._get_hook('frag', 'post')
        hook.add(self.shader())
```

**Comment by raacampbell13** [comment]
Do I need a luminance (M by N) image to set the colour map? When I feed an M by N array to scene.visuals.Image, it generates a storm of errors (even though the docs say that it accepts 2D arrays as inputs). I had to use an MxNx3 (RGB) image instead.

**Comment by Eric89GXL** [comment]
Maybe it needs to be `MxNx1` which would be a bug, but I think we have some examples of `MxN` in the repo (e.g., https://github.com/vispy/vispy/blob/master/examples/basics/visuals/colorbar_visual.py#L131). Could you look to see how your code differs from those?

Are you on latest `master`?

**Comment by raacampbell13** [comment]
ah ha! Both MxN and MxNx1 work but it fails if cmap is not defined.

**Comment by raacampbell13** [comment]
@kmuehlbauer Yup, your filter works:
![mri1](https://cloud.githubusercontent.com/assets/5427811/9522860/52135d5a-4cd7-11e5-9af4-086d1a03ed96.jpg)

**Comment by kmuehlbauer** [comment]
@raacampbell13

Looks good! How did you actually place the cut? I tried with ImageVisual but haven't found the correct transformation, yet. With a second VolumeVisual with just one layer it works somehow, but I get it not properly aligned.

**Comment by raacampbell13** [comment]
Added an Image not a VolumeVisual and used STTransform to move it. I think this is what you need:

```python
sectionTo=150
volume1 = scene.visuals.Volume(vol_data[0:sectionTo,:,:], parent=view.scene)
CMAP=volume1.cmap

section2D = vol_data[sectionTo,:,:]

plane = scene.visuals.Image(section2D, parent=view.scene, cmap=CMAP)
plane.transform = scene.STTransform(scale=(1,1,1), translate=(0,0,sectionTo))

view.camera=scene.cameras.ArcballCamera(parent=view.scene, fov=60, name='Arcball') 
 ```

I'm throwing together a quick GUI to allow the cut to be moved.

**Comment by kmuehlbauer** [comment]
@raacampbell13 Ahhrg, I had a dimensions mismatch! The GUI works nicely!

**Comment by kmuehlbauer** [comment]
@raacampbell13 @Eric89GXL 

I played a bit with the GUI, changed the `BlackToAlpha()` to just have `gl_FragColor.a = value;` for everything. This adapts the colors to a more consistent look.

When the image is moved inside the volume, the volume "before" the image isn't rendered or better said it's overlaid by the image. Is it from the special method used (kind of raycast)? Could it be overcome?

![brain_slice](https://cloud.githubusercontent.com/assets/5821660/9540447/3665b9bc-4d5f-11e5-957c-642f10799e77.png)

**Comment by raacampbell13** [comment]
What happens if you switch the order in which you add the overlaid image and the volume?

**Comment by kmuehlbauer** [comment]
@raacampbell13 
Them the images isn't rendered at all. I fiddled with the gl_states (cull_face etc) but failed so far.

**Comment by Eric89GXL** [comment]
@kmuehlbauer did you do anything with depth testing? It might need to be enabled on one or both visuals to get it to work properly. But @rougier or @campagnola would probably know for sure.

**Comment by kmuehlbauer** [comment]
@Eric89GXL 

Yes, I tried all four possible situations. Both with `depth_testing` enabled, disable, and one enabled, the other disabled and vica versa. 

I also followed @raacampbell13 suggestion to switch the visuals creation order. Seems to have no effect.

**Comment by campagnola** [comment]
The volume rendering methods we use do not play well with objects inside the volume. We've encountered this complaint so many times, though, that it's obviously time for somebody to write the necessary method :)   Right now, we only draw on the back surfaces of the volume, and the pixel colors are determined by integrating along each ray. What we need is to instead draw a stack of densely-spaced planes so that objects inside the volume will be correctly overlaid by the volume in front of them.

Anyone up for an adventure?

**Comment by kmuehlbauer** [comment]
That is what I suspected after reading inside `volume.py`. However, I had hoped that you have something in the "backyard" to conquer this. 

Anyway is there e method inside VisPy to achieve what @raacampbell13 and myself like to implement? If not, it seems a good idea to have an adventure. 

@campagnola can you elaborate a bit more on your idea? Do you have some pointers of information?

**Comment by raacampbell13** [comment]
It's true it would be nice to have better control of things inside volumes. It would make movies like this more effective: https://www.dropbox.com/s/cahqy7qmpd2mauy/foo.mp4?dl=0

**Comment by campagnola** [comment]
The basic problem is this: With OpenGL (and in general any rasterization-based renderer), rendering multiple transparent objects together requires either that 1) all objects are sorted such that the closest objects are rendered last, or 2) some other complicated / expensive technique is used to handle blending. This problem has been known for so long and caused so many headaches that there are endless websites, blog posts, and SIGGRAPH papers describing the problems and potential solutions. Examples:

https://www.opengl.org/wiki/Transparency_Sorting
http://www.openglsuperbible.com/2013/08/20/is-order-independent-transparency-really-necessary/
http://stackoverflow.com/questions/4127242/opengl-rendering-two-transparent-planes-intersecting-each-other-impossible-or
http://www.sjbaker.org/steve/omniv/alpha_sorting.html

For our current rendering method, there is no way to insert an object inside the volume because there is no (general/practical) way for the volume, while it is being rendered, to ask about the geometry of other objects. For example, we'd really like to just tell each ray-cast to stop when it encounters an opaque object (but we can't).
Once you have a good grasp of the problem, the solution makes a bit more sense. Let's say you want to draw a volume with an opaque plane cutting through it at some arbitrary angle:

1. Draw the opaque plane (in vispy, we use `visual.order` to change the rendering order)
2. Subdivide the volume into many densely-spaced planes, each of which only draws a thin slice of the volume. The planes can be orthogonal to the viewer or to some axis of the volume; the latter is easier (and I think it produces nicer results).
3. Render these planes from back to front, allowing the already-drawn opaque objects to occlude the slices.

This method is similar to the "shear-warp" method, except that the shear-warping part of it is handled by OpenGL drawing triangles in their proper place on-screen:

https://en.wikipedia.org/wiki/Volume_rendering#Shear_warp
http://users.csc.calpoly.edu/~zwood/teaching/csc572/final11/ghflores/documents/FastVolumeRendering.pdf

**Comment by bollu** [comment]
@campagnola: Interesting, I've always known the back-to-front rendering as "Painter's algorithm", though I'm not sure from _where_. I think the first place I ran into it was in the quake source code, where Carmack uses a BSP tree.

**Comment by michaelaye** [comment]
Quick question to this interesting problem: How does vispy.visual.order deal with the inversion of order when the camera travels around the object to be displayed? Is there some algorithm connected to that or would the programmer have to update the entries in visual.order by herself?

**Comment by campagnola** [comment]
It does not--the `order` property only determines which visuals are drawn first. If you want the visuals to be drawn depth-sorted, then it is necessary to recompute the order every time the camera or visuals move. For visuals that intersect, there may be no unambiguous way to decide which should be drawn first (for example, see the stackoverflow link I posted above).

To avoid this, the solution I propose does not require sorting visuals by depth. The individual slices in the volume are drawn back to front, but this only requires knowing the position of the camera relative to the volume, and does not make use of `order`, since all slices are drawn within a single visual.

**Comment by almarklein** [comment]
Rendering a series of dense-spaced planes will not work for any rendering method (e.g. it wont work with MIP). I wonder whether the result would be appealing enough when both the volume and the plane are semi-transparent, and we blend them with Nico's order-independent transparency strategy. 

The way to achieve truely correct result is depth peeling (https://github.com/vispy/vispy/wiki/Tech.-Transparency#depth-peeling), but this is an expensive multi-pass approach.

**Comment by rougier** [comment]
We should investigate https://github.com/maweigert/spimagine to see how rendering is done

**Comment by campagnola** [comment]
> Rendering a series of dense-spaced planes will not work for any rendering method (e.g. it wont work with MIP). 

Maybe you mean "will not work for all rendering methods" ?  Agreed MIP won't work. I'm not even sure what the math would look like to drop a translucent object in the middle of a max-projected volume..

**Comment by almarklein** [comment]
(yes, that is what I meant)

**Comment by raacampbell13** [comment]
@kmuehlbauer 
I tried setting everything as gl_FragColor.a = value as you suggest and it does, indeed, look smoother. Thanks. However, any idea how to stop dark regions on the cut section becoming transparent and turning into holes?

**Comment by kmuehlbauer** [comment]
@raacampbell13 

I think there is no satisfying solution to this. One could think about filling the holes with another opaque color (non b/w-grey). This would shield the structures "behind" the cut and show normally transparent sections of the cut at the same time.

**Comment by kmuehlbauer** [comment]
@raacampbell13 

Did you come any further with this?

While working on my visualisation app I found a solution which works for me to some extend.

![brain01](https://cloud.githubusercontent.com/assets/5821660/10822404/6b1901e0-7e57-11e5-8a88-aea5f3261a24.png)
![brain02](https://cloud.githubusercontent.com/assets/5821660/10822617/44828c44-7e58-11e5-872d-f91dba9ae1e7.png)

I use just the volume data and have just the axis-cut multiplied by some value. When using `mip-method` the intensity at the particular cut is pronounced.

**Comment by raacampbell13** [comment]
Nice images. Things have stalled on my end, as I need to work on some data extraction stuff and hardware stuff, not the 3-D vis.

**Comment by kmuehlbauer** [comment]
Recently (yesterday, yikes!) https://github.com/vispy/vispy/pull/2149 was merged. A first test of https://github.com/vispy/vispy/blob/main/examples/scene/volume_plane.py and https://github.com/vispy/vispy/blob/main/examples/scene/volume_clipping.py shows, that almost everything requested/tested in this issue is covered now. This is amazing! Great work @alisterburt!

So. I'm going to close this. @raacampbell almost 6 years is quite some time and you may have moved on in the meantime. Anyway, I'll just let you know, in case you are still connected with 3D-vis.

**Comment by raacampbell** [comment]
Thanks! I'm not using it right now but it's good to see this is a feature.
