### ISSUE TITLE
There is a ton of clunky output for the different backends.

### ISSUE THREAD

**Issue by oskarsinger** [vispy/vispy#1119]
While running the test script, there is a ton of output about the failure to find different backends even if one of them is successfully used for the tests.

When running vispy in ipython (not the test script, just code snippets), it displays error messages about not being able to find all of the backends except for the one it is currently successfully using.

**Comment by larsoner** [comment]
The tests I think are okay as is. But the backend searching messages should probably `debug` level, and only at the end if no backend is found emit an error.

**Comment by djhoese** [comment]
I know this is extremely old, but as far as I can tell this was updated at some point. I only see `logger.info` messages if you ask for a backend and it can't be loaded:

```
                    if backend_name is not None:
                        # Inform only if one isn't available
                        logger.info(msg)
```

Or `logger.warning` if a backend is imported before it is "used" by vispy and can't be used by vispy properly (assuming multiple backends are being imported). Otherwise, it looks like a single RuntimeError is raised after trying all backends.

I'm going to close this for now and if someone still has an issue with this please comment below or open a new issue.
