### ISSUE TITLE
4GB+ for contineous plotting at 100KS/s on a predefined buffer

### ISSUE THREAD

**Issue by kuldeepdhaka** [vispy/vispy#1129]
**WARNING: THIS WILL CAUSE THRESHING OF YOUR OS[1] AND MAKE YOUR OS UNSTABLE.**
[1] if paging to disk is enabled

I was able to recover after my kernel killed the script on reaching 100% memory usage.

here is a code that does the trick. the code simply generate 
- some random data, 
- copy it to numpy onetime allocated array, 
- pass the valid number of samples to vispy plot

tip: use timeout and/or ulimit
see `man timeout` and `man ulimit`

```
import numpy as np
from vispy import plot as vp

import threading
import time

sps = 100000 # 100KS/s
duration = 3 #number of seconds to show data
update_rate = 16 #in Hz
valid_l = 0 # valid value (from starting)
index_l = 0 # next index to write to
total_l = sps * duration # total samples
x = np.linspace(0.0, duration, total_l)
y = np.empty(total_l)

class Poller(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)

    def start(self, size):
        self.interruption_requested = False
        self.count = size
        threading.Thread.start(self)

    def stop(self):
        self.interruption_requested = True

    def run(self):
        global np
        while not self.interruption_requested:
            # generator some data
            data = np.random.random(self.count)
            self.feed(data)

    def feed(self, inc_y):
        #circular copy to data and set the data to plot
        global line, x, y, valid_l, index_l, total_l
        inc_l = len(inc_y)
        if (index_l + inc_l) > total_l:
            #if we reached at end and need to copy some at end and some at end
            start_l = (index_l + inc_l) - total_l
            end_l = inc_l - start_l
            end_y = total_l - end_l
            y[end_y:end_l] = inc_y[0:end_l]
            y[0:start_l] = inc_y[end_l - 1 : start_l]
        else:
            start_y = index_l
            start_l = index_l + inc_l
            y[start_y:start_l] = inc_y[0:inc_l]
        del inc_y
        index_l = (index_l + inc_l) % total_l
        valid_l = min(total_l, valid_l + inc_l)

        line_data = (x[0:valid_l], y[0:valid_l])
        line.set_data(line_data, symbol=None)

fig = vp.Fig(size=(800, 800), show=False)
line = fig[0, 0].plot(([0,0], [0,0]), title='Plot Test', xlabel='Time', ylabel='Voltage')
grid = vp.visuals.GridLines(color=(.5, .5, .5, 0.5))
grid.set_gl_state('translucent')
fig[0, 0].view.add(grid)

poller = Poller()
poller.start(sps / update_rate)

fig.show(run=True)

poller.stop()
poller.join()
```

Note: The above code is under (new) BSD License

![mem](https://cloud.githubusercontent.com/assets/1651124/11137466/e11fb712-89dd-11e5-9b94-40dbdde75cf7.png)

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
So there are a couple things that are questionable about your code here. Most important question though is what backend are you using?

As for risky points about your code:

1. You are using regular python threads in a GUI application. Typically a GUI framework provides its own "safe" object for doing things with threads (ex. QThread for PyQt).
2. You are modifying globals with threads. Not terrible, but risky with 1 above. Having some type of synchronization between the main thread and the background thread would help here to be sure nothing strange was happening.
3. You are modifying visualization variables from another thread. See https://vispy.org/faq.html#is-vispy-multi-threaded-or-thread-safe

Now all of that said, I don't see anything that I would think would cause this memory leak by itself. One thing to try would be to comment out the `set_data` call and see if things still blow up. Next thing would be to slow down the rate of data and see if it still grows (even if it is slower).

Lastly, a lot has changed since this issue was created and this was posted during vispy's maintainer dead zone (kind of) so sorry that no one got to this sooner. It would be worth it to try this again with a modern version of vispy as various memory leaks and performance improvements have been made. Given the age of this I'm guessing you have moved on from this issue in one way or another so I'm going to close this. If you want to continue working on this you can comment and we can reopen it.
