### ISSUE TITLE
VisPy Requires OpenGL 3.0

### ISSUE THREAD

**Issue by murphym18** [vispy/vispy#1138]
I saw in the [VisPy docs](http://vispy.org/installation.html#hardware-requirements) that OpenGL 2.1 is required. I had lots of trouble getting VisPy to work on my laptop (it runs OpenGL 2.1). After trying  many backends (glfw, pyglet, PyQt4) I found some success using the PyQt4 backend downloaded [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4). 

Using the PyQt4 backend on windows, I get an error when I run:

```
import vispy.app

c = vispy.app.Canvas()
c.show()
vispy.app.run()
```

Here is the error:

```
RuntimeError: Function glBindFramebuffer not present in context.
```

I found some information about glBindFramebuffer [here](https://www.opengl.org/sdk/docs/man4/html/glBindFramebuffer.xhtml) and notice that OpenGL 3.0 was the first version supported. I'm not sure if this error actually matter but if it does, then it might be helpful to update the docs.

Note: In addition to the trace log, the code above does create and show a window on my OpenGL 2.1 computer.

**Comment by philshvarcz** [comment]
Independent on what's written in the docs:
Is OpenGL 3.0 really required for essential functionality? I've got a notebook with integrated graphics supporting only OpenGL 2.1, and can't really use VisPy on that otherwise fine machine. This is somewhat a downer, as I mainly need simple functionality like point and line plots that would easily be covered by GL 2.1.
If OpenGL 3.0 features are not part of the core functionality, would it be possible to allow an optional choice, to restrict VisPy to functionality that is available in OpenGL 2.1 ?
Regards
Phil

**Comment by djhoese** [comment]
I know this is a response 2.5 years after this was first created, but I can at least give some kind of answer. The `glBindFramebuffer` was first added in OpenGL 3.0 as your link shows @murphym18, but can also be available to GPUs that provide the `GL_ARB_framebuffer_object` extension (https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_framebuffer_object.txt).

I am not the original developer of this functionality in vispy so I can't say for sure why a non-2.1 feature was used in the core of vispy, but it is my opinion that it has lived their so long that it would be near-impossible to remove. Perhaps @almarklein can comment on this since it looks like he was the person who first wrote the glir.py module.

VisPy is slowly starting to add features for higher versions of OpenGL and with WebGL 2.0 becoming supported more I'm not sure I can dedicate the time to modify vispy to use v2.1-only features. At least not ones that are already used.

I hope that any new-ish machine from the last couple years will support the necessary GL extensions to work with vispy as is. I will leave this issue open as a reminder to myself to update the documentation to say that 2.1 is required with certain extensions.

**Comment by larsoner** [comment]
Closing since I think we'll have to live with this ambiguity going forward
