### ISSUE TITLE
PanZoomTransform vs PanZoomCamera

### ISSUE THREAD

**Issue by crashMOGWAI** [vispy/vispy#1202]
Anyone noticed that the mouse wheel event behaviors are different between these two? PanZoomCamera is the most intuitive, centered on event and zooming in and out based on scroll direction.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
I'm not sure I understand how they differ based on your description. What does the PanZoomTransform do differently? Either way, I would say the PanZoomTransform is not very widely used and this hasn't been reported otherwise. If you can provide a description of how they differ or a small code example that would be nice and we can look at it. Otherwise this issue is rather old so I think I'm just going to close this but am willing to reopen if needed.
