### ISSUE TITLE
LinePlot and Markers

### ISSUE THREAD

**Issue by crashMOGWAI** [vispy/vispy#1204]
Markers are not working in LinePlot, anyone else see this? First noticed higher up in PlotWidget, but haven't found root cause yet.

**Comment by scottpaine** [comment]
Out of curiosity, do they work in MarkerVisual? If you run the point_cloud.py example, can you see markers?

I had the same issue on my computer, turns out that Intel Graphic Drivers don't play well with OpenGL. It won't throw any errors, but programs will fail to draw markers.

On my laptop, I have an nVidia card, so by turning off the Intel graphics drivers, I could get the points to draw again.

**Comment by crashMOGWAI** [comment]
Can see markers: 
examples\basics\visuals\markers.py
examples\basics\visuals\line_plot.py

Can't see markers:
examples\basics\scene\point_cloud.py
examples\basics\plotting\scatter_histogram.py

Driver issue was the conclusion I was headed toward. I'll have to confirm on a different machine. Thanks for the heads up.

**Comment by scottpaine** [comment]
[Here's the relevant issue](https://github.com/vispy/vispy/issues/1085) (that's still open at this time):

**Comment by crashMOGWAI** [comment]
Yep, same issue. Since its in the queue already, I'll kill this thread.
