### ISSUE TITLE
Documentation gone?

### ISSUE THREAD

**Issue by ghisvail** [vispy/vispy#1209]
v0.4.0 used to have a `doc` folder with the sphinx sources. This folder is absent from the current tip of `master`. Why is this?

**Comment by campagnola** [comment]
IIRC, documentation was moved to a separate repository, but I don't see it anywhere. @Eric89GXL, do you know where the docs have gone?

**Comment by Eric89GXL** [comment]
Yeah it's up here https://github.com/vispy/vispy-website

**Comment by campagnola** [comment]
Ah, of course. I was expecting something like `vispy-docs`.

**Comment by ghisvail** [comment]
Why not keeping the docs *connected* to the main repository via a submodule?

**Comment by ghisvail** [comment]
Otherwise, this sounds like a regression to me. I could build the documentation from `v0.4.0` but it will no longer possible in `v0.5.0` then?

The reason I am caring is because I wanted to resume the packaging effort initiated by [Fred Picca](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759820) for Debian and have to know whether I will be able to provide a documentation package built from the `vispy` source in the future.

Thanks for letting me know.

**Comment by campagnola** [comment]
You should be able to build the docs from the vispy-website repository; why is it necessary to have them connected to the main repository?

**Comment by ghisvail** [comment]
> why is it necessary to have them connected to the main repository?

One repository = one source package, which should build all the necessary binary packages. Here, the python 2 and python 3 packages and, until `v0.4.0`, the corresponding documentation package.

> You should be able to build the docs from the vispy-website repository.

Which means providing a separate source package for the docs only. This is not ideal, hence myself proposing a *soft* link via a submodule. This way, the docs can still be checked out from the same repository, whilst being maintained separately.

**Comment by campagnola** [comment]
I'm not quite getting it. Why can't the Debian source package contain files from both repositories? Is it somehow easier to do a `git submodule init` rather than a second `git clone`? 

In any case, I am not opposed to having docs as a submodule, but it's not something I have worked with much before. Anyone know any drawbacks of setting up submodules?  (@Eric89GXL ?)

**Comment by ghisvail** [comment]
> Is it somehow easier to do a git submodule init rather than a second git clone? 

From a packaging standpoint, it would be.

**Comment by vasole** [comment]
On 08.05.2016 08:08, Luke Campagnola wrote:
> 
> In any case, I am not opposed to having docs as a submodule, but it's
> not something I have worked with much before. Anyone know any
> drawbacks of setting up submodules? (@Eric89GXL [1] ?)
> 

Well, the point with submodules is that if one does not know there are 
submodules and it makes simply a clone the submodules are not going to 
be present.

Because of that I prefer to use git subtree. However it does not come 
without drawbacks.

https://developer.atlassian.com/blog/2015/05/the-power-of-git-subtree/

**Comment by ghisvail** [comment]
The documentation is now back to the source tree via submodule. Closing.
