### ISSUE TITLE
How to clear canvas and redraw?

### ISSUE THREAD

**Issue by chemelnucfin** [vispy/vispy#1241]
This must be something I'm overlooking...

I use QT as the backend and I change the plots based on UI interaction, however, the new plots draw on top of what is already there.  To get a new plot, I can only overwrite it with another canvas (which, obviously, causes memory issues)

**Comment by drewm1980** [comment]
My understanding is that the backend (QT) should be irrelevant to the user-facing API.

Maybe you're creating a bunch of new objects instead of updating the data in the original objects? I would dig around in the object hierarchy in ipython until you find something like set_data(). If there's nothing that's obvious that just works, I would read the code.

It is not obvious that overwriting a canvas should cause memory issues. If vispy is segfaulting or something, that's a bug and I would post a minimized example.

**Comment by chemelnucfin** [comment]
It's been a while, but I did see the memory go up as I kept changing the plot information. Either ways, I didn't need to investigate further.  Thanks.
