### ISSUE TITLE
PyQt4 backend sould not be imported directly

### ISSUE THREAD

**Issue by bdvd** [vispy/vispy#1243]
Hi,

I've just noticed a strange behavior in the current version of vispy.

If I type in the console:
from vispy.app.qt import QtGui
I get a RuntimeError saying that the backend._qt should not be imported directly. Now I repeat the command and everything is fine. No error message occurs. Maybe I'm wrong but I think I should get an error message in both cases or no error message at all.

Running Python 3.4 with PyQt4 under Win7 x64.

**Comment by drewm1980** [comment]
If you are calling vispy.app.qt, you are probably trying to write backend-specific code. This error seems like it was put in-place to alert you in a bid to keep you from doing that, and it succeeded. 

The error probably ~should happen every time, but seems very, very low priority. If it really bothers you, I would try fixing it. There are >200 open issues, but only 10 open pull requests; if you fix it, it would probably be merged quickly. (I am not a core dev)

**Comment by scottpaine** [comment]
It appears that this happens because, when you import from `vispy.app.qt`, the first line is `from .backends import qt_lib`. This is defined in `backends` as `None`, and that is only changed when a Qt backend is chosen by VisPy based on what you have in your own Python environment (you can see an example of this at the end of [vispy.app.backends._pyqt4](https://github.com/vispy/vispy/blob/master/vispy/app/backends/_pyqt4.py)). After that, there's this lovely chunk of code:

```python
if qt_lib in ('pyqt4', 'pyside'):
    from PyQt4 import QtGui
    QWidget, QGridLayout = QtGui.QWidget, QtGui.QGridLayout  # Compat
elif qt_lib == 'pyqt5':
    from PyQt5 import QtWidgets
    QWidget, QGridLayout = QtWidgets.QWidget, QtWidgets.QGridLayout  # Compat
elif qt_lib:
    raise RuntimeError("Invalid value for qt_lib %r." % qt_lib)
else:
    raise RuntimeError("Module backends._qt should not be imported directly.")
```

Basically, what I think is happening is that when you import from vispy.app.qt, there is no qt_lib defined in backend, and it raises the error. It may be possible to fix this like so:

```python
from vispy.app import backend
backend.qt_lib = 'pyqt4'
from vispy.app.qt import QtGui
```

However, this just kind of seems like delving too far into the VisPy internal guts, so I propose an alternative method:

If you can build your GUI in QtDesigner with some kind of widget placeholder, you can make the Vispy canvas object separately and place it in the GUI as follows:

``` python
from my_gui import MyGUI
from vispy_canvas import VispyCanvas

gui = MyGUI()
widget_placeholder = gui.widget_placeholder

canvas = VispyCanvas(*your_args, **your_kwargs)
canvas.create_native()
canvas.native.setParent(widget_placeholder)

widget_placeholder.setCentralWidget(canvas.native)
```

Something to this effect will work for taking a Vispy canvas object and inputting it into an existing Qt object, since `canvas.native` is a nice, slightly modified version of QtWidget. For examples like this, see [primitive_mesh_viewer_qt.py](https://github.com/vispy/vispy/blob/master/examples/demo/gloo/primitive_mesh_viewer_qt.py) or [wiggly_bar.py](https://github.com/vispy/vispy/blob/master/examples/demo/visuals/wiggly_bar.py) in the demos section.

**Comment by bdvd** [comment]
I have already tried the dirty way and set the backend.qt_lib before and than the code says no Applicationbackend. So I think the Qt4 backend is actually not imported the right way or it is not imported at all.

**Comment by davidh-ssec** [comment]
@bdvd I know this is really old, but I'm going through all the vispy issues I can and came across this. There are a couple things covered in this issue that I have answers to:

1. If you can help it, do *NOT* import PyQt modules *from* the vispy backend module.
2. The reason the error only shows up once is that in `qt.py` the `qt_lib` variable is imported first, followed by a call to `use_app` which, through the magic of vispy backend loading, sets up the backend properly. However the `qt_lib` variable you imported is still `None`. When you import the module again it sees that the backend is already loaded (from the previous `use_app`) so it continues as desired.
3. For your QtDesigner stuff, if the generated python ends with an import from the backend then you should make sure to put the below code *before* you import the generated python module:

```
from vispy import app
app.use_app('pyqt4')
```
