### ISSUE TITLE
jupyter webgl    not working

### ISSUE THREAD

**Issue by sniperlucian** [vispy/vispy#1245]
namespace changes in ipython causes for   **vispy.app.use_app('ipynb_webgl')**  to throw:

C:\Anaconda2\lib\site-packages\IPython\html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
C:\Anaconda2\lib\site-packages\IPython\utils\traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")

**Comment by drafter250** [comment]
I was just sifting through this part of the project (app.backends.ipython._widget.py) and was about to just start updating module names etc to try my hand at getting . when I realized the vispy devs might want to still support the older versions of the Jupyter/Ipython Notebook.
@campagnola, @Eric89GXL, @rossant, what say you? just updating to the latest and greatest seems a bit easier than trying maintain backwards compatibility?

**Comment by Eric89GXL** [comment]
I think it was mostly experimental anyway, so it would be okay with me to update it

**Comment by itsagoodbrain** [comment]
Just thought I'd let you know that the warning is just a deprecated warning. This is not actually the reason that the webgl backend is broken currently. I've just submitted a PR with the fix to get it working. I haven't implemented any changes for the deprecated warnings however, so that would be great to do as well! Especially given Eric's approval.
