### ISSUE TITLE
suggestion: bundle with glfw, freetype and OpenSans

### ISSUE THREAD

**Issue by yhql** [vispy/vispy#1266]
It is a nice feature that you allow any backend to be selected by the user, however I think it would be nice if at least one was provided so that VisPy runs as-is.
Also, on corporate networks it is not easy to get VisPy to download freetype and OpenSans typefont from the dedicated repository.

One of the developers here (@rossant I think ? :) ) mentioned 'glfw' was the most maintained, and it's also very small (about 50 Ko). Freetype and OpenSans aren't too large either, so I modified VisPy to install those 3 in a separate vispy/misc/ folder and look there first when importing.

If needed I could make a pull request with this. So far I'm just switching between 32 and 64 bits versions of Freetype and glfw, both using VC2013, I would need to switch for linux/OSX as well.

What do you think ? :)

**Comment by drafter250** [comment]
I just ran into this myself as I was trying out one of the basic plotting examples and the plot window kept locking up because it was trying to download stuff on the fly from a secondary demo-data repo through the company firewall. If these libraries are crucial to core functionality then shouldn't they be included in the main project. I also really don't like the idea of an implicit download from GitHub for security purposes.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
There has been a lot of work regarding downloads and including stuff in vispy or adding dependencies that include external dependencies inside vispy. VisPy still downloads demo data of examples on-the-fly, but at least those are examples. There may be cases still where vispy downloads ancillary files on the fly. If those are still issues please file a new github issues.

As for backends, there has also been a lot of work in backends since this issue was originally created. I, however, don't support the idea of having a hard requirement on one specific backend. We do depend on the python wrapper of glfw now so it may be easier to have that has a hard requirement, but seeing as most of these backends wrap some amount of C/C++ code there is a non-zero complexity with getting them installed on all supported platforms. One option would be the new experimental tk backend, but even that depends on an external library for OpenGL support in tk. So I think what I'm saying is that I'd rather keep with the current strategy of no hard requirements on a specific backend. Feel free to provide some counter argument and we can continue this discussion but given the age of this I'm going to close the issue.

**Comment by almarklein** [comment]
People who want to "ship glfw with vispy" can install vispy using ;)
```
pip install -U vispy glfw
```

I also think since we use Rougier's freetype wrapper, the dll is included via that package.

That leaves the fonts. And for these I actually agree that packaging them along makes a lot of sense. Relying on a post-install download can be fragile ...

**Comment by almarklein** [comment]
We ship them:

![image](https://user-images.githubusercontent.com/3015475/144930572-2abc3558-bfe6-4544-82eb-198fdc574a3b.png)
