### ISSUE TITLE
Rotate cube example broken

### ISSUE THREAD

**Issue by chrisspen** [vispy/vispy#1291]
[This example](http://api.vispy.org/en/v0.2.1/examples/howto/rotate-cube.html) fails with the exception:

```
Traceback (most recent call last):
  File "rotatecube.py", line 164, in <module>
    c = Canvas()
  File "rotatecube.py", line 91, in __init__
    self.vertices, self.filled, self.outline = cube()
  File "rotatecube.py", line 75, in cube
    I1 += np.repeat( 4*np.arange(2*3), 6)
TypeError: Cannot cast ufunc add output from dtype('int64') to dtype('uint32') with casting rule 'same_kind'
```

**Comment by kmuehlbauer** [comment]
@chisspen

The example you are referring to is from an outdated vispy version (0.2.1). The error your are experiencing is due to some change in numpy regarding inplace-math.

This is already fixed in the latest [rotating cube example](https://github.com/vispy/vispy/blob/master/examples/basics/gloo/rotate_cube.py).

Please report back, if this fixes it for you and close the issue.

**Comment by kmuehlbauer** [comment]
@chrisspen

The example you are referring to is from an outdated vispy version (0.2.1). The error your are experiencing is due to some change in numpy regarding inplace-math.

This is already fixed in the latest [rotating cube example](https://github.com/vispy/vispy/blob/master/examples/basics/gloo/rotate_cube.py).

Please report back, if this fixes it for you and close the issue.

**Comment by kmuehlbauer** [comment]
Closing this. All rotating cube examples works with commit 2e78ae21e61e9bbb4db3eb798687103742115fd4.
