### ISSUE TITLE
Kivy

### ISSUE THREAD

**Issue by jimanvlad** [vispy/vispy#1299]
Hi,

Is there any way to use VisPy with a [Kivy ](https://kivy.org/#home) backend?

I see this was discussed back in 2014: https://github.com/vispy/vispy/pull/138

**Comment by davidh-ssec** [comment]
@jimanvlad I know this issue is fairly old, but as far as I know no one here has tried using vispy with Kivy. Theoretically it should be possible based on what their documentation says and what vispy's goal is (GL ES 2.0 compatibility). If you'd like to discuss this further feel free to bring it up on https://gitter.im/vispy/vispy
