### ISSUE TITLE
Export to X3D

### ISSUE THREAD

**Issue by macrocosme** [vispy/vispy#1300]
This is more of a general inquiry than an issue. Is there any current effort towards enabling export to X3D? I noticed the mention from @astrofrog on Glue-Viz (https://github.com/glue-viz/glue-vispy-viewers/issues/116). I was wondering if there is any interest about it on the vispy side.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
Sorry for not responding earlier @macrocosme. It would be interesting to have some kind of conversion from X3D to a vispy visualization, but it is definitely not a priority. I know nothing about X3D beyond what I just read by googling it but it sounds like it would be better as a separate package from vispy that uses vispy core to implement the conversion. Any actual work on this though would probably come from outside the core vispy team as we have a difficult time as it is keeping up with maintenance and user support.

I'm going to close this, not because I don't want it implemented, but because I don't think it should be part of this vispy repository and I don't think it will be implemented any time soon.
