### ISSUE TITLE
AttributeError: module 'vispy.scene' has no attribute 'ScrollingLines' from examples/demo/scene/oscilloscope.py

### ISSUE THREAD

**Issue by SBUtltmedia** [vispy/vispy#1321]
I'm trying to run examples/demo/scene/oscilloscope.py but I get the following error:
  File "oscilloscope.py", line 91, in <module>
    class Oscilloscope(scene.ScrollingLines):
AttributeError: module 'vispy.scene' has no attribute 'ScrollingLines'

tried this in python2.7 and python3.6 

Doing a search in the documentation finds no mention of ScrollingLines

**Comment by kmuehlbauer** [comment]
Obviously you are not working with the last vispy from github master branch The `ScrollingLines` was introduced after release of 0.4.0. Please use the latest from github master branch.

Unfortunately https://github.com/vispy/vispy/blob/master/examples/demo/scene/oscilloscope.py will not run out of the box because of two numpy related errors.

See: #1326
