### ISSUE TITLE
0.5.0 Release

### ISSUE THREAD

**Issue by davidh-ssec** [vispy/vispy#1322]
It's been almost a year since the last release and there is a conda-forge package waiting for the 0.5.0 release. Is there anything else that needs to be added?

Conda problems with vispy issue:
https://github.com/vispy/vispy/issues/1275
Conda-forge ticket:
https://github.com/conda-forge/staged-recipes/pull/1657

**Comment by kmuehlbauer** [comment]
JFTR: 0.4.0 was released almost 2 years ago.

**Comment by hadim** [comment]
A more general question would be to ask the status of this project I guess.

Could a developer clarify this point?

**Comment by rossant** [comment]
As far as I know, no one is actively working on this project, unfortunately. There are no future plans of development. A few persons would be capable of making a 0.5 release but I don't know if they'd have time to do it in the foreseeable future. @campagnola @Eric89GXL @almarklein @astrofrog ?

**Comment by rougier** [comment]
Yep, same for me here plus I lost track on all the latest changes.

**Comment by keunhong** [comment]
Bummer, vispy seems to be the only decent OpenGL API in python that interfaces with Numpy as if now.

I wonder if anyone can go through some of my pull requests and merge them upstream? I have some waiting that I'm using extensively in my research (texture cubes, depth textures, mipmapping etc.).

My fork's 21 commits ahead and it'd be nice to cut that down a bit :P

**Comment by davidh-ssec** [comment]
@keunhong Sounds cool. I'm hoping that if we get the attention of some of the current maintainers we can add a few new ones. I wouldn't mind being added.

**Comment by Eric89GXL** [comment]
If there are folks who have some experience maintaining a repository (GitHub code review, TDD, etc.) it would be great if other people could take over. There is a lot of good code in here that could use some love. I just don't have the time currently. But I can try to provide some light guidance here and there.

@davidh-ssec do you feel equipped to do maintenance work?

@almarklein @campagnola @rossant @rougier I'm planning on letting some other folks more or less take over maintenance because it seems like none of us have the time -- speak now or forever hold your peace :)

**Comment by davidh-ssec** [comment]
@Eric89GXL I think I am equipped to do maintenance (pull requests, fixing/adding tests, fixing certain bugs, etc). I've also been trying to stay active on gitter and at least answer some people's questions when possible. My biggest challenges will be my lack of experience with a large portion of OpenGL and my lack of time during certain parts of the year. One of my main projects at work depends on vispy and it isn't difficult to justify work on vispy benefiting the project.

I have experience with other open source python projects that I am a maintainer/contributor on that utilize travis and appveyor for unit tests and release on PyPI. Some of the packages are released for Mac, Windows, and Linux. It will take some time for me to get caught up on vispy's way of doing things, but I don't foresee a problem.

**Comment by keunhong** [comment]
I can help out with things under gloo and gl although I'm not sure I'm fit to be a maintainer. I can do code reviews and such.

**Comment by Eric89GXL** [comment]
@keunhong anyone can comment on PRs, so don't hesitate to do that. It's great if you can look after gloo and gl because it sounds like @davidh-ssec lacks some experience at exactly those levels. I don't think it takes any elevated privileges to review code (comment on PRs) so feel free to do that already. Over time if you get comfortable with the flow then it would make sense to be a maintainer.

@davidh-ssec sounds good, I'll add you once I wait a few days to give other current maintainers time to respond. Also @astrofrog feel free to comment as a maintainer if you wish.

**Comment by kmuehlbauer** [comment]
@davidh-ssec Thanks for bringing up this issue again. For my vispy-background and point of view see this [gitter-comment](https://gitter.im/vispy/vispy?at=57d47371ef19fa3f40758496). 

I'm also willing to contribute by answering and (hopefully) resolving issues, reviewing PR's and bug-fixing. As @Eric89GXL already pointed out, that can be done without being a maintainer. But in the end maintainers are needed to get things along.

**Comment by rossant** [comment]
@Eric89GXL +1, I would be delighted to see new maintainers.

**Comment by Eric89GXL** [comment]
@kmuehlbauer would you be interested in becoming a maintainer?

**Comment by kmuehlbauer** [comment]
@Eric89GXL If this will be of any help, yes. Like @davidh-ssec I have some experience with development and maintenance of python packages utilizing travis and other CI's. Parts of my work depends heavily on vispy, so I'm all in for maintaining vispy.

**Comment by bollu** [comment]
@Eric89GXL - I somewhat disappeared after GSoC, but I'd love to help with keeping `vispy` alive. I still use the library occasionally and feel it needs to exist for sure

**Comment by Eric89GXL** [comment]
Okay, invitations sent to @kmuehlbauer and @davidh-ssec

**Comment by davidh-ssec** [comment]
Since there seems to be quite a few people waiting on a 0.5 release I thought I'd post this here. I've changed the 0.5 milestone due date to October 1st (https://github.com/vispy/vispy/milestone/5). If you go to the milestone you'll see a list of issues that have been marked by @Eric89GXL as prerequisites for this version release. If there is an issue not listed there that anyone sees as urgent for 0.5 then let me know here. If you decide to start solving an issue please post on that issue first so we can reduce the amount of redundant work given how many people are interested in a 0.5 release and may be working on any one issue.

I haven't looked through all the issues for 0.5 or all the other open issues for vispy so we'll have to see if October 1st is a good estimate.

**Comment by kmuehlbauer** [comment]
@Eric89GXL I've no invitation received so far. 

@davidh-ssec I'll also sweep trough the open issues the next days.

**Comment by kmuehlbauer** [comment]
@Eric89GXL Ha, the invitation was first displayed after visiting https://github.com/vispy.

**Comment by Eric89GXL** [comment]
Glad it came through :)

**Comment by sevas** [comment]
Hello, 

I have been following this project since its inception, and I would be pretty sad to see it go away.
Right now I still use pyqtgraph for GPU python visualization, because for day to day work it is still ahead of vispy. I'm currently thorn between adding a naïve support of geometry shaders to pyqtgraph for something I need right now (I actually already started), or piggyback on vispy's more complete abstraction of opengl stuff and work on visuals. A recent comment from @campagnola made me fallback on pyqtgraph for now.

Anyway, all that to say that I am interested to contribute to vispy.

I think I have a rather decent python/numpy experience, and I'm far from an expert but I can get my way around OpenGL & GPU stuff.

Let me know if I can help.

-f

**Comment by davidh-ssec** [comment]
@sevas Any help is appreciated. Pull requests are welcome. As far as helping the project out beyond your needs, we have plenty of github issues over the last year or so that need to be looked at. As mentioned above we hope to get a 0.5 release out soon so people can start using features that have existed on github for over a year.

**Comment by sevas** [comment]
@davidh-ssec are the issues listed in the 0.5 milestone filter up to date?

**Comment by kmuehlbauer** [comment]
@sevas ATM we are trying to figure out, what is necessary to get 0.5 out. See also [this comment](https://github.com/vispy/vispy/issues/1322#issuecomment-301927114).

**Comment by Eric89GXL** [comment]
I took a quick look at the milestone issues and they all seem doable, and would be good to have if possible before release

**Comment by ghisvail** [comment]
After version `0.5` gets delivered, perhaps you guys could commit to more frequent releases with smaller diffs (a.k.a. [RERO](https://en.wikipedia.org/wiki/Release_early,_release_often))?

**Comment by davidh-ssec** [comment]
@ghisvail That's the plan. As described above the main reason 0.5 has been delayed for so long was how busy the maintainers got. Hopefully with more maintainers we can come up with enough time to do regular releases.

**Comment by flutefreak7** [comment]
I've checked in on vispy every couple months for years and I'm hopeful that development continues as the original core devs pass the torch to the community.

I've been in my job 5 years and have tons of unfinished projects, so I definitely sympathize that good work takes time, people move on, and getting a grand idea all the way to a fully-realized, feature-complete product is incredibly challenging. My main project has been in development for around 10 years and won't fly for another 2. Hang in there folks and keep plugging away. Vispy is worth the effort. Thank you to all the volunteers!

**Comment by davidh-ssec** [comment]
Vispy 0.5.0 is now on PyPI. Still working on announcements and other post-release updates, but it is out.

**Comment by Juanlu001** [comment]
Awesome!
