### ISSUE TITLE
Could you create a requirements.txt file and add it to the repository? 

### ISSUE THREAD

**Issue by codypiersall** [vispy/vispy#1324]
Usually it's better to just do a `pip install -e .` when beginning a project, but sometimes dependencies break compatibility. When that happens, it's nice to have a 100%-known-working version of all dependencies. A requirements.txt provides that. 

Specifically, I would like to track down why #1312 is happening. I'm guessing that Jupyter broke backwards compatibility, so I'd like to test with a version that is known to work.

**Comment by davidh-ssec** [comment]
I was just about to start working on this, but now I'm not sure how to proceed. As you've stated @codypiersall a `requirements.txt` file should list the packages and specific versions of a working environment to properly use the package in question. For vispy this is a little difficult because while we could have a `requirements.txt` for a basic environment it would most likely only contain one backend (and that backend's dependencies). To include more than one backend would mean that any user of the `requirements.txt` now has more large packages installed than they need. To have a `requirements.txt` that doesn't have any backends doesn't really help anyone using the file.

Additionally a lot of the backends require some C library underneath that is sometimes independent of the python wrapper package version. So listing a backend package in the `requirements.txt` doesn't control the version of the C library installed.

Lastly, maybe it would be more helpful to users if we released version 0.5.0 and completed the process to make a conda package (via conda-forge, https://github.com/conda-forge/). Doing this would allow us to list any limitations for dependency versions.

@larsoner @kmuehlbauer Thoughts?

**Comment by larsoner** [comment]
I think Anaconda provides `vispy`, albeit an old one.

I don't know of any way with `requirements` to make a set of optional packages to choose from, so I'm not sure there is much we can do there.

**Comment by kmuehlbauer** [comment]
AFAIK the only needed dependency is `numpy`. And one of the backends for sure. There are some modules pulled in in the examples namely `scipy`, `networkx`, `imageio` and `matplotlib`. We could wrap them in some _HAS_XYZ construct like [here](https://github.com/vispy/vispy/blob/11a4a6fdb768fa6e0a107eb6d15af9d9e1448a43/vispy/visuals/isocurve.py#L16).

The docs seem very clear to me (http://vispy.org/installation.html). I'm not sure if a requirements.txt makes that much sense here. We can have one with `numpy` and possibly the other needed packages for the examples. But we can't restrict/set the backend in there.

I very much second to bring in vispy to `conda-forge`. There would also be the possibility to have several backend packages (eg. vispy_qt4, vispy_qt5, vispy_wx etc. pp). This would be extremely useful.

**Comment by davidh-ssec** [comment]
@kmuehlbauer What do you mean by backend packages like "vispy_qt4"? Wouldn't someone just install the package for the backend? `conda install 'qt<5'`

**Comment by kmuehlbauer** [comment]
@davidh-ssec Sure experienced users like us :-) would do that. What I had in mind, are packages which just pull vispy and one respective backend. So you can do `conda install vispy_qt4` and this will pull vispy as well as pyqt4.

**Comment by davidh-ssec** [comment]
Do any other packages do something like that? And some point I think you have to expect a user to be able to follow installation instructions.

**Comment by kmuehlbauer** [comment]
I'm convinced. The idea was obviously not that good.
