### ISSUE TITLE
VisPy automatically downloads and uses freetype253.dll. This is not OK.

### ISSUE THREAD

**Issue by stxlvt** [vispy/vispy#1327]
I was shocked and dismayed to discover that running `examples\basics\visuals\line.py` would automatically download a `dll` file (`freetype253.dll`) without even asking me first. 

*This is not in any way OK.*

Worse, this happens *on import* of `vispy.util.fonts`. Nothing much should happen on import of any module, because there are other reasons for importing a module besides wanting to call any of the functions in it. For example, Sphinx imports modules when it makes documentation from docstrings, and so modules should not do anything on import that you don't want to happen when building docs. This includes downloading files from the internet.

(If a module contains a lot of functions that each require the same setup to be performed before the first time they're called, a good solution is to make a decorator that does the setup if it hasn't been done already, and then calls the decorated function. For the end user this will work just the same, with the exception that importing the module has no side-effects.)

Worse still, the file was downloaded using plain-text http only, and no verification was performed to ensure that github.com really was github.com or that the downloaded file was the intended file. It was just loaded and used, no questions asked.

I *insist* on being in control when it comes to what files are downloaded and executed from the internet, and I think it is very reasonable demand that VisPy, being a reputable python module, does not do such things.

I urge you in the strongest possible way to make VisPy at least *ask* before downloading and running executable files, no matter their origin (I even want to be asked about pure data downloads -- who knows, maybe I'm on mobile data and don't want to download a big file right now -- but in this issue I want to focus on the executable files).

In my opinion this warrants an immediate bugfix release once fixed.

**Comment by djhoese** [comment]
@larsoner @kmuehlbauer What is the current state of this? I'm not up to date on how vispy handles Windows installation. To add on to the discussion started in #1284, I would prefer if these extra libraries were listed as separate dependencies that we didn't bundle with vispy, but if we are really close to things be "acceptable" as-is then bundling is ok.

**Comment by larsoner** [comment]
I'm fine with bundling, no time to implement myself ATM

**Comment by djhoese** [comment]
I'm changing the milestone for this because I don't fully understand what needs to happen to fix this. If someone can get this fixed I'd be fine making a 0.6.1 with the change for it.

**Comment by larsoner** [comment]
First order solution is to at least download over https. But even this isn't great.

Second order solution is to bundle the freetype DLL when building a windows release. In fact we should probably bundle that and the other thing that will be downloaded when someone tries to use text, which is the default font. Somehow this should be possible using wheels but I am no expert.

Also this is the first release of VisPy to include compiled Cython/C code, so we shouldn't just distribute a source tarball, as it will fail for windows users.

The cleanest solution is probably to produce wheels for release. It fixes the "compiled code" problem and the "downloaded stuff" problem, because we can compile+bundle in the wheel (I think!).

@djhoese any interest in learning how to do this stuff? If not, it's something I could probably benefit from learning, and this seems like a decent way to learn it, especially since I incorporated the compiled code bits.

Ideally we could get Travis (OSX and Linux) and AppVeyor/Azure (Windows 64-bit only maybe?) to build these for us, and then get the artifacts and upload them to PyPi. Or something...

**Comment by djhoese** [comment]
My preference would be for travis and appveyor to do this. I mentioned in other issues (or maybe here) that the `pytroll/aggdraw` project uses cibuildwheel to build wheels. I think we could add a prebuilt dll as a package file if we really wanted to as a short term solution, but yeah not great.

There is a push to release 0.6 (mostly by me) this week. We could release the source tarball, have the conda-forge package, and work on wheels on the side. @larsoner if you have any spare cycles it would be great if you could look at this, especially if you do it with cibuildwheel. I don't have a Windows machine to test on.

**Comment by larsoner** [comment]
> I don't have a Windows machine to test on.

You can [develop for Windows with VirtualBox or other virtualizers for free](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) and easily install Python using Anaconda, so this excuse no longer cuts it -- you have to admit your distaste for the operating system itself or cite a Windows-related medical condition if you want to abstain :)

FWIW, though, the CIs on each OS must already have the machinery for building, so in theory it shouldn't be too much more work to get them to make wheels for us. I'll look into `cibuildwheel`, but getting it to work this week will be tough if it's not immediately obvious and working.

**Comment by djhoese** [comment]
> but getting it to work this week will be tough if it's not immediately obvious and working.

That's why I think we should plan on developing wheels over the next week or so. It may not be obvious. The CI machinery supports building but the problem is that the wheel has to be in a very specific environment to be considered "clean" from what I understand. This is especially true for manylinux wheels which require being built on a CentOS 5 machine (could be wrong).

> You can develop for Windows with VirtualBox or other virtualizers for free 

Cool. Now I know.
