### ISSUE TITLE
Online server-side browser backend

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#134]
This online web backend generates PNG images on the server, and streams binary images to the browser via WebSockets. In return, the client streams user actions to the server.

This server-side online backend may be useful for heavy visualizations based on huge amounts of data. In effect, it is more efficient to transfer small PNG images instead of huge datasets.

Assigned to @mfkaptan (GSoC 2014).

**Comment by bek0s** [comment]
Hello. I wonder if there has been any progress on this. Thank you.

**Comment by davidh-ssec** [comment]
@bek0s No there has not. There has been work (by me) to update the the jupyter notebook backend, the most recent work for this is still in a separate branch. That backend is in higher demand and still doesn't have all the functionality it needs. If you would like to offer help with either the notebook backend or this backend I would be happy to point you in the right direction.

**Comment by djhoese** [comment]
I'm going through some of these older issues and after re-reading this I think this could be a separate backend or separate "mode" of the Jupyter Widget (since that is what most people will want to do with it at first). We could look at providing a video stream generated on the server side. Using something like https://ipywebrtc.readthedocs.io/en/v0.4.0/ or some other functionality being worked on by the ipywidgets community.

**Comment by djhoese** [comment]
@larsoner This is something you brought up again during the last sprint. Do you think this is something an undergraduate programmer could work on (CC @Aaru143)? Do you or @rossant have any guidance/pointers for where to get started? Has anyone looked at the most recent technologies for doing this type of thing (streaming PNG or video to a jupyter widget from the python kernel)? I suppose we'd still need a custom jupyter widget if we wanted to cleaning send mouse and keyboard events back to vispy. Otherwise I could see us using existing tools like I mentioned above from ipywidgets and have some if statement in the vispy `Canvas` to create and "display" these widgets and connect events to the various vispy events.

I think this aligns with deprecating the existing jupyter support and instead offer this PNG streaming option as a replacement.

**Comment by larsoner** [comment]
> Do you think this is something an undergraduate programmer could work on (CC @Aaru143)? Do you or @rossant have any guidance/pointers for where to get started?

I think piping PNGs is what's implemented for VTK here:

https://github.com/Kitware/ipyvtk-simple

We've used in in MNE-Python and it works, including at least click/click-drag events. So I think most of the infrastructure and design should already be there. I'd start by using this code, and then once it works, see if there is something better (like streaming video so that you can take advantage of compression, etc.) and of course if there is something better, contribute it back to ipyvtk_simple (or open an issue telling them it might be helpful) :)

**Comment by GuillaumeFavelier** [comment]
And `ipyvtk-simple` itself is based on https://github.com/martinRenou/ipycanvas , the `Viewer` class is inherited IIRC.

**Comment by djhoese** [comment]
Based on what I'm seeing here, this looks like ipycanvas can handle the mouse and keyboard events: https://ipycanvas.readthedocs.io/en/latest/events.html

So this could probably be a new backend in VisPy (maybe `ipycanvas`?) or maybe just `jupyter` so we have the freedom to completely change how it works in the future...eh maybe `ipycanvas` is better.

**Comment by almarklein** [comment]
It's weird, but I thought that we already implemented a VNC approach for IPython back in the days. I half-remember it being ok but a bit slow, and that being one of the reasons we invested in GLIR. Did I make that up or did we perhaps have a POC at some point? @rossant do you remember?

**Comment by djhoese** [comment]
There are mentions of `vnc` and a backend for it either in the code, in github issues, or both. Would VNC work the same way though?

**Comment by almarklein** [comment]
I think the approach outlined in the top post is what we referred to as "the VNC method".

**Comment by djhoese** [comment]
Perfect: https://github.com/vispy/vispy/blob/master/vispy/app/backends/_ipynb_vnc.py

So we just need to "revive" that backend and test it with more modern interfaces maybe.
