### ISSUE TITLE
Is vispy always using OpenGL?

### ISSUE THREAD

**Issue by skostrichegg** [vispy/vispy#1344]
Hi,

Sorry for a lot questions these days.

Are all vispy's subpackages(gloo, scene, plot, ...) always using OpenGL?

I render some 3D grapihc and save it as JPEG by matplotlib.
But that package is slow because it supports only software rendering.

So, I'v moved that codes to vispy by using subpackage 'scene'.

However it takes longer time than matplotlib.
I think OpenGL is not using GPU in my system.
(I'm not sure, but maybe my GPU doesn't support OpenGL or its driver installed is not for OpenGL.)

So, I want to make sure below.
If the env for using GPU via OpenGL is created, vispy is always using GPU whatever its subpackage is?

Thanks!

**Comment by davidh-ssec** [comment]
Hi, For the most part vispy is always using OpenGL and therefore the GPU. There are a few cases where vispy will do calculations in the CPU, but it normally limits these times to when it isn't reasonable to do it in the GPU. Meaning either the code would get really ugly or would be difficult to code for the GPU or the GPU is not good at performing those calculations.

Although the 'scene' interface may not be the most performant in some cases, it should be able to handle most things at about the same speed as the lower level interfaces. If I had to guess here are a few things that may be causing your application to run slow:

1. You are trying to plot a *ton* of points, like 100k+ to millions, but only producing an image that is less than 8000 by 8000 pixels. I see this a lot in matplotlib questions where someone tries to plot their data file of 100k points on a small figure where there is no way that the computer can draw each of those points in a meaningful way. Normally you can help by averaging or smoothing out your data.
2. On top of #1, perhaps your GPU does not have a ton of memory and you are trying to plot a lot of points. In which case you could be running out of GPU memory. If your computer was made in the last 5 years this is very unlikely, but I thought I'd mention it.
3. A bug in your video driver.
4. What colormap are you using for your surface? Certain colormaps in vispy (viridis) perform very poorly and can even cause compilation errors on some GPUs because of how they are currently converted to shader language. There is already a github issue to get these colormaps to perform better, but no one has had time to tackle it yet.
5. Maybe you aren't using the GPU you think you are? If you have a separate video card there is a small chance that vispy (your computer) is choosing to use the integrated GPU in your CPU which might not perform like your separate GPU should.

That's what I came up with off the top of my head. So my questions for you are:

1. What version of vispy are you using? The latest github master?
2. What does the following show you:

```
import vispy
print(vispy.sys_info())
```
3. Is the code you are talking about in your previous issue the same code that is running slow for this issue? Same amount of input data?

**Comment by davidh-ssec** [comment]
I should add it is possible that certain calculations in vispy may not be the best in preparing the data for the GPU. We won't know if this is the problem for you until we look at what you're using. Do you have a simplified version of what you are doing that we can test ourselves?

**Comment by skostrichegg** [comment]
@davidh-ssec Thank you for your detailed reply.

First of all, I think my system is not suited for using GPU vis OpenGL.
Becuase it has only integrated GPU(in CPU), and no separate one.
(And the integrated GPU is MGA-G200e model by MATROX. It looks like having very low performance)

So, I just want to check that I'm using vispy correctly before I'm going to add on separate GPU.
Because When I tested with same data on both matplotlib and vispy, vispy takes much longer times.

The code what I'm talking about above comments is not same as previous issue's source.
Unfortunately, I'm afraid to can't show you the codes because of some reason..
But I can tell you what the codes include.
 - about 10 Mesh(scene.visuals) object with 10000 ~ 20000 points and 20000 ~ 40000 triangle datas.
 - about 150 Mesh(scene.visuals) object with 100 points
 - about 150 Ellipse(scene.visuals) object
 - about 50 Text(scene.visuals) object
 - not using specific colormap. just 'clr=color.ColorArray(color=(0.9, 0.9, 0.9), alpha=0.8)'

And below is vispy version information what I'm using.
 - vispy version: (0, 5, 0, 'dev0')

A result of vispy.sys_info():
WARNING: could not determine DPI
"Platform: Linux-3.10.0-514.21.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core\nPython:   3.5.2 (default, Jan  9 2017, 20:05:19)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]\nBackend:  PyQt4\npyqt4:    ('PyQt4', '4.12', '4.8.5')\npyqt5:    None\npyside:   None\npyglet:   None\nglfw:     None\nsdl2:     None\nwx:       None\negl:      EGL 1.4 (DRI2) Mesa Project: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3\nosmesa:   None\n_test:    None\n\nGL version:  '2.1 Mesa 11.2.2'\nMAX_TEXTURE_SIZE: 8192\nExtensions: 'GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array
... (too much strings)

Thanks,

**Comment by davidh-ssec** [comment]
I'm going to guess that your main issue is the 150 Mesh and 150 Ellipse objects, even 50 text objects is pretty big. Each one of those objects is a separate OpenGL program that has to get sent to the GPU. Normally you want to combine as many of your "objects" as possible so that the GPU can draw multiple elements at one time, in one program.

This may be difficult using the high-level Scene interface, but it's not impossible. You'll have difficulty getting good performance regardless of what GPU you run it on with as many Visual objects as you have now. However, I'm not very familiar with Mesh objects and Ellipse objects so I'm not sure how much help I can be. @Eric89GXL and @kmuehlbauer might be able to point you in a good direction on how to combine those to get better performance.

**Comment by davidh-ssec** [comment]
@skostrichegg I'm closing this since the original question has been answered. If you still need help with your specific problem you can post a question on the mailing list (https://groups.google.com/forum/#!forum/vispy) or create another issue here.
