### ISSUE TITLE
Website / documentation on readthedocs

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#1374]
Hi all, congrats on the new release!

Vispy also has a page on http://vispy.readthedocs.io (and `api.vispy.org` "links" to it). The builds were failing for a long time. Trying to make myself useful a bit, I just made a branch to fix that. Before moving on, let's decide what to do:

* Only use http://vispy.org. Advantage: simple, one place to host docs, which is manually updated. Subtasks:
    * Delete readthedocs account.
    * Update/remove the `api.vispy.org` CNAME. 
    * Perhaps explicitly mention the version in the reference docs.
* Use readthedocs for hosting the website/docs. Advantage: keep multiple versions, so ppl using a release can use a different version as ppl using master. Docs build automatically on each commit to master. Disadvantage: you have the `en/latest/` suffix to the url. To be precise, going to `http://vispy.org` will redirect to `http://vispy.org/en/latest` (or `stable`). Subtasks:
    * Merge my branch and update rtd to use master again.
    * Update `www.vispy.org` CNAME to point to rtd.
* Use readthedocs for reference docs, and website for the rest. Seems complex.

I don't really have an opinion on this matter. I'll help out with whatever is chosen :)

**Comment by davidh-ssec** [comment]
Also see https://github.com/vispy/vispy-website/issues/3

I'm a little confused about all of the hosting locations. So we have:

1. Github hosting of `vispy.github.io` which is what `vispy.org` goes to
2. Readthedocs which is where `api.vispy.org` and `vispy.readthedocs.io` go. And readthedocs uses `vispy/doc` to create that site.

Right?

**Comment by almarklein** [comment]
That is correct.

**Comment by kmuehlbauer** [comment]
I would favour bulletpoint 3 of your list @almarklein, although it might seem complex.

IMHO we should differentiate between the VisPy website (vispy.org) and the API doc, gallery.
We could use `vispy.org` as kind of landing page where all those other resources can be referenced. Even blog-posts, news, etc. could be published there without the need to create the whole documentation as it is now.

I'm fine also with point 2, because having different versions available would be good.

**Comment by davidh-ssec** [comment]
I agree that having multiple versions would be good.

I'm not super excited about essentially having two websites related to vispy. It seems that SciPy technically has two sites, scipy.org and docs.scipy.org. However, scipy.org is used to advertise multiple packages (numpy, scipy, ipython, matplotlib, etc) so it makes sense to have one landing page for all of them.

There also seems to be a numpy.readthedocs.io, but I'm not sure how up to date that is. Another thing to think about is where do we draw the line between what goes on the readthedocs and what goes on vispy.org?

**Comment by davidh-ssec** [comment]
Just discovered that vispy.org is also used for uploading failed image diffs via `vispy.org/upload.py` in a POST request so you get images like this: http://data.vispy.org/data/visuals/1ad54f0d6ee8a4d39d439a83432614d6dec0ccc8/rectpolygon10.png

**Comment by kmuehlbauer** [comment]
@davidh-ssec `data.vispy.org` resolves to `luke.campagnola.me`. @campagnola Is this image upload for debugging purposes only?

**Comment by davidh-ssec** [comment]
@kmuehlbauer any idea where this redirect is configured? If `vispy.org` is just a CNAME for `vispy.github.io` then where does this redirect get configured? Or I guess `vispy.org` is @almarklein's domain that has subdomains configured and that's doing the `api.vispy.org` and `data.vispy.org` redirection?

**Comment by davidh-ssec** [comment]
I started thinking about this again today and there is no reason we couldn't follow glumpy's lead and do the original 3rd bullet point (Documentation link goes to rtd). I'm not sure it helps users, but it seems the best way to do more complex hosting with a gallery and examples while still having detailed documentation in a place people expect.

**Comment by kmuehlbauer** [comment]
@davidh-ssec I've no idea where the redirect is configured. It is most likely done at the current hoster. I do this similar in another project (one gh-repo for the landing page, one gh-repo for the docs).

👍 for bullet point 3

**Comment by almarklein** [comment]
@davidh-ssec  Sorry, I only read this today. I still get all notifications, but they get filtered in an email folder that I don't follow that closely atm. I'll see if I can reconfigure things so I get a better prompt when I am mentioned. 

Yes, I still own the vispy domain, and have the subdomains configured at the registrar. Let me know where you want to point things to and I will make it so :)

**Comment by almarklein** [comment]
Current DNS setup:
![image](https://user-images.githubusercontent.com/3015475/34910073-3f6d5130-f8ae-11e7-8865-554011c7660e.png)

**Comment by djhoese** [comment]
Now that I'm looking at this again, I've changed my mind again. My original thought for having two sites was that github might limit how much data we can throw in the gallery page (`_static`) so it'd be nice to have a way out by having a separate domain for the "flashy" stuff where we could possibly put the files somewhere else.

However, github has a per-repository limit of ~1GB and we aren't going to hit that if we do things correctly. This is especially true since we have the github sphinx docs in a separate repository which "saves" space. It'd be really nice if there was one place to go for all of the documentation. You often see API docs right next to gallery pages for other libraries and I think that is important for vispy which lacks a lot of documentation at the moment.

**Comment by kmuehlbauer** [comment]
Makes sense. So the API docs would be build via rtd at every push, right? Also versioning could be configured.

**Comment by djhoese** [comment]
Yes. But I'm saying that now I would rather have everything (API, gallery, landing page) on rtd which would use `vispy/docs` (which points to the `vispy-website` repository). So going to `vispy.readthedocs.io` would have the same effect as going to `vispy.org` now. This is the second bullet in @almarklein's original post. We'd have to update the instructions for updating the docs since right now it requires updating multiple repositories with `make` commands.

I can be convinced otherwise, just bringing this up again since a user brought it up on gitter.

**Comment by kmuehlbauer** [comment]
I would still pick bullet point 3, but do not have strong preference. In the end it is a matter of maintainability, so whatever is easy and nicely automated is good.

**Comment by djhoese** [comment]
Maintainability, yes, but also user experience. Having two separate websites may be confusing to users. I'll think about it more.

**Comment by almarklein** [comment]
> Would you mind add me (davidh-ssec) and @larsoner and @kmuehlbauer?

Sorry, I've somehow missed that message. I've added you. @larsoner and @kmuehlbauer, if you provide/send me your rtd user names, I can add you too.

**Comment by larsoner** [comment]
Just signed up, mine is `larsoner`

**Comment by almarklein** [comment]
Great! Done!

**Comment by djhoese** [comment]
This issue still hasn't been decided on, but I've been thinking about it more and I think we should drop readthedocs. We are currently using readthedocs through the vispy/vispy.github.com repository. By using github pages we allow ourselves more flexibility on the building of the website. We could continue to do it ourselves with the `make` commands or we could automate it using something like Travis CI. That should allow us to do fancier things like testing or generating examples before uploading the resulting HTML.

I've been told about some tools to help with some of this including https://drdoctr.github.io/ which helps with the upload process and deploy key management. Not that that is super difficult *but* it also means we can use plugins like https://github.com/goerz/doctr_versions_menu to keep the versions list that readthedocs gets us.

The biggest issue I'm having right now is that the HTTPS certificate for vispy.org doesn't seem to be working correctly. If you go to `https://vispy.org` your browser will likely show an error because the site name in the certificate does not match the vispy.org domain name (it is the github.com one). As far as I can tell the DNS stuff is set up on @almarklein's side of things, but something must not be right on GitHub's side. I've just removed the custom name on github's Settings page and then re-added it. Hopefully that triggers something to reset and magically fixes it.

Let me know if you have ideas or feedback on any of this.

**Comment by djhoese** [comment]
:tada: I think the remove/add domain in Settings fixed it. @kmuehlbauer please verify that you can go to HTTPS for vispy.org.

**Comment by kmuehlbauer** [comment]
@djhoese Works! At least firefox is telling me so...

**Comment by djhoese** [comment]
FYI @kmuehlbauer @almarklein I plan on deleting the readthedocs project so people don't accidentally end up there when we don't want to maintain that website (we are using github pages).

@almarklein After I merged #1931 then I will do the delete and I *think* that `api.vispy.org` can be removed from your custom domain names. I'm 90% that it was just used as the name for the readthedocs pages.

**Comment by djhoese** [comment]
@almarklein Could you please make `api.vispy.org` redirect to `vispy.org`?

**Comment by almarklein** [comment]
@djhoese done! Can take a while to settle; the TTL was set to 1 day.

**Comment by djhoese** [comment]
Since I'm impatient, I'm going to assume that this is going to work and close this. Readthedocs is gone, github pages (vispy.org) is the only vispy docs site now. The new pydata theme is now being used for vispy.org. Now to just finish all the "coming soon" things that I put in the website (https://github.com/vispy/vispy-website/issues/30). Thanks everyone for the discussion and help.

**Comment by almarklein** [comment]
Nice work @djhoese !  I'll leave the latest email notification of this issue as unopened in my mailbox, to remind me to check the domain again tomorrow :P

**Comment by kmuehlbauer** [comment]
@djhoese @almarklein Could you have a look at the https settings again. Currently I've an issue with the certificate so it seems. But maybe this is due to the TTL of 1 day Almar mentioned. Maybe it will get fixed over the day.

**Comment by almarklein** [comment]
I checked the "enforce https" button.

The `api.vispy.org` now points to the Github IP's, but Github does not know the domain. Apparently we can only set one custom domain, so we need to redirect. Will work on this.

**Comment by almarklein** [comment]
Mmm, as far as I can tell, I cannot fix this with just DNS. Some registrars have "special" types of records that allow a redirect to another domain, but the one I use (TransIP) only has A and CNAME, which redirects to the IP behind the specified name.

@djhoese What is the intention with the api.vispy.org domain? Is this mostly for backwards compatibility? I can host a simple service that does a 301/308 redirect.

**Comment by kmuehlbauer** [comment]
@almarklein `vispy.org` now works as expected and shows a nice Let's encrypt certificate. 

Not sure how `api.vispy.org` should resolve. IIUC just simple redirection to `vispy.org`?

**Comment by djhoese** [comment]
The `api.vispy.org` change is just for backwards compatibility for anyone who had references to the readthedocs page and hopefully for any google search results that still list api.vispy.org (although most seem to have the readthedocs URL). I'm not sure it is worth any work beyond configuration settings. Hm...can I have multiple domains on a github pages repository. Let me see...

**Comment by djhoese** [comment]
https://stackoverflow.com/a/16455966/433202

**Comment by almarklein** [comment]
Yeah, that's unfortunate. Anyway, I've got the redirect setup!

**Comment by almarklein** [comment]
https://github.com/vispy/vispy-website/pull/31
