### ISSUE TITLE
Adopting matplotlib colormaps

### ISSUE THREAD

**Issue by KOLANICH** [vispy/vispy#1397]
As mpl is a de-facto standard, some library developers (I) have written the code converting some foreign (from a file of a proprietary format, which was reverse engineered) colormaps into matplotlib format. I guess that vispy colormaps either should be compatible with matplotlib ones using duck typing, or receive matplotlib colormaps into the colormap constructor to give vispy colormaps.

EDIT: There are a few other colormaps listed in #648 we should add.

**Comment by davidh-ssec** [comment]
@KOLANICH Agreed. The main issue right now is that certain vispy colormaps (viridis) are naively translated in to GLSL using a series of `if` branches. This is an extremely bad idea for GPU coding once you get passed 10+ branches (my guess). In fact we have reduced the resolution of the viridis colormap in vispy due to some GPUs failing to handle as many branches as needed.

The solution is to allow vispy colormaps to write the color information to a Texture and load the appropriate color inside the GLSL. This has been discussed elsewhere, but I don't think there is a single issue talking about it. I think this issue may be that issue.

**Comment by rougier** [comment]
Also, only 1 (2D) texture is needed for all the different colormaps. One line for one colormap.

**Comment by kmuehlbauer** [comment]
Ref: #1052 for more discussion regarding texture an cap.

**Comment by rougier** [comment]
512 or 1024 wie is more than enough. I doubt a user would need more than that but I'm may be wrong.

**Comment by larsoner** [comment]
Should we just do a single texture of 1024x1024? That way we can support up to 1000 colormaps without breaking. We can support more when we need to (e.g., ask user to delete existing ones and deal with indexing, or create a list of Texture2D to store them).

**Comment by KOLANICH** [comment]
1 I guess fixed size textures are not good.
2 We should have a benchmark verifying if on modern gpgpu-optimized chips branching is bad.

**Comment by davidh-ssec** [comment]
@KOLANICH As for your 2nd question: https://github.com/vispy/vispy/pull/1332

So yes it is a problem on certain modern video cards (CPU-integrated and dedicated).

**Comment by larsoner** [comment]
> I guess fixing the size of the texture are not good.

Can you elaborate on why you expect it to be problematic in this case in practice?

**Comment by KOLANICH** [comment]
I guess because I may want to use for example 10 colors, so using 1 MiB of memory for 10 colors looks like waste of memory. I know that, noone cares about it.

**Comment by larsoner** [comment]
> I guess because I may want to use for example 10 colors, so using 1 MiB of memory for 10 colors looks like waste of memory.

This is true, but it's not uncommon in scientific plotting to use a few 256-color colormaps, so we'd definitely want at least 256 along one dimension. I think we should do 256x256, 512x512, or 1024x1024 to start to allow flexibility and expansion (the cost of this should be low). And if someone hits memory problems we can add an option to set the size later, assume YAGNI for now.

> I heard that iPhones requre the textures' dimensions to be powers of 2

Yes this sort of thing is not uncommon historically at least, thus the choice of 512 or 1024.

>  for example it's not so hard to imagine that the texture dimension may be required to be a multiple of 4096?

My guess is that this is unlikely given how many smaller textures must be in the wild currently, but who knows.

Let's keep things as simple as possible to start -- there are costs to increasing code complexity to support unknown, suspected, or even known but uncommon use cases. Besides, I think what we've discussed is compatible with subsequent modifications that are backward-compatible (e.g., adding an option to specify the size can take on the default `size=(512, 512)`.

**Comment by davidh-ssec** [comment]
@larsoner So are we completely dropping the option of per colormap textures?

I think there is also the option of having a reference counting kind of system where it is a texture per colormap but only if the colormap is being used. For example, changing the colormap on an ImageVisual could reuse the same texture for the colormap if it was the last Visual using that colormap. This could be admittedly much more complex than the other options.

**Comment by larsoner** [comment]
> So are we completely dropping the option of per colormap textures?

We should pick one and go with it, either way is really fine by me.

A single colormap so far sounds like the best compromise of flexibility (should cover 99.9%+ of real-world use cases) and speed (only create and manage one per context), and @rougier advocated for it and I'm happy to defer to his OpenGL experience. But if it turns out to be easier to implement one per colormap I'm fine with that, too.

**Comment by davidh-ssec** [comment]
I'm not against the shared colormap texture, just want to make sure we don't forget about other options.

**Comment by KOLANICH** [comment]
🎉
