### ISSUE TITLE
Spectrum & max texture size

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [vispy/vispy#1402]
I'm using vispy to build an interface for an audio restoration tool I created, and I want to say thank you for creating such a _superb_ toolset. 

One thing I quickly noticed, the default spectogram does not handle large data sets, ie. long audio files, small hops & large FFT sizes. Feed it a long array to reproduce the issue, eg.:
15,000,000 samples
sr = 44.1kHz
n_fft = 4096
step = 512
It raises an obscure error with `GL_INVALID_VALUE` and the spectrum stays blank.

I found this is due to the **maximal allowed texture size**.
The data used as a spectrum texture may not have a dimension longer than `max_width = gloo.gl.GL_MAX_TEXTURE_SIZE * 4`, because `GL_MAX_TEXTURE_SIZE` is given for rgba data but spectra use luminance only.

I fixed this in my custom spectrum display by slicing the FFT data according to `max_width` and then feeding each slice to a different texture image. My method has some issues because I am not sure how to delete the images I don't need anymore (after changing the spectrum settings), but all in all it works and displays full spectra for the problematic input data.

On a side note: Are textures "padded" to a square format in memory, so would it be more efficient to split the spectrum data into many small, square pieces instead of fewer rectangular pieces with one side as long as `max_width`?

I suppose a similar approach could be implemented for the builtin spectrogram display. In general, it would make sense to capture this error and warn the user about too large texture data. It may not be too common but I thought it worth mentioning.

**Comment by kmuehlbauer** [comment]
@HENDRIX-ZT2 

I think I can follow your arguments. But that will not work at all, since `GL_MAX_TEXTURE_SIZE` is valid for all types of data (`rgba`, `luminance`, etc). See [OpenGL specs](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexImage2D.xml), where for `GL_LUMINANCE` is stated:

                       

>  Each element is a single luminance value.
>                         The GL converts it to floating point,
>                         then assembles it into an RGBA element by replicating the luminance value
>                         three times for red, green, and blue and attaching 1 for alpha.
>                         Each component is then clamped to the range [0,1].
>             

So you can't exceed `GL_MAX_TEXTURE_SIZE` by any means.

The `SpectrogramVisual` uses `ImageVisual` under the hood. So for spegrams exceeding `GL_MAX_TEXTURE_SIZE`we could think of splitting it into pieces. But this seems not that straightforward, because it depends on the calculated fft-sizes. Anyway, it would be good top check for `GL_MAX_TEXTURE_SIZE` in `ImageVisual`.

**Comment by kmuehlbauer** [comment]
@HENDRIX-ZT2 
Now I'm sure I can't follow.

Just to be on the same page, if I use `15,000,000 samples, sr = 44.1kHz, n_fft = 4096, step = 512` I get the imdata.shape = (2049, 29289). This is well above my `MAX_TEXTURE_SIZE: 16384`. 

Also your for-loop is a bit strange, because it will only run once (`range(start, stop, step)`), but that might be due to writing from top of your head. 

You would not need to create the Spectrum over and over again. Just use the `set_data` method to feed new data to the `Visual`.

I still do not get that completely. It would be a great deal if you could make a minimal example out of this code of yours.

**Comment by HENDRIX-ZT2** [comment]
@kmuehlbauer 

I get `gloo.gl.GL_MAX_TEXTURE_SIZE = 3379`, so mine is significantly lower than yours at `16384`. I'm also wondering why mine is not a power of 2, it seems fishy...

In my case and with the example data mentioned above, the for-loop does 3 iterations, because `4*3379 < 29289`, and each loop creates a new texture in a new image from the current slice of FFT data. For you, it only does one iteration because `4*16384 > 29,289`. So for you to get more than one iteration in the loop as is, you need _really big_ data, >65,536 entries along one axis of the luminance data.

I'm not sure if I understand you correctly there. So you're saying the `set_data` ([as in the oscilloscope example?](https://github.com/vispy/vispy/blob/9d46fac28eac985fbe5d032d1581710fb74999ea/examples/demo/scene/oscilloscope.py#L173)) method deals with too large textures in one image? Interesting, I'll have a look at that too.

By trial and error, I found that my _actual_ texture limit is also `16384`. So I can feed 16384 FFTs into one texture, and not one more. This means
1) My `gloo.gl.GL_MAX_TEXTURE_SIZE` value is wrong. I will update my graphics drivers and see if the issue persists.
2) My assumption that luminance textures can be `GL_MAX_TEXTURE_SIZE * 4` was most likely **dumb luck** induced by [this post](https://www.gamedev.net/forums/topic/414765-maximum-size-of-texture/?tab=comments#comment-3762094) and point 1), because my `GL_MAX_TEXTURE_SIZE * 4 = 13516` is just a little smaller than `16384`.

So there's actually two "issues" here:
1) faulty `gloo.gl.GL_MAX_TEXTURE_SIZE` value
2) circumventing the `GL_MAX_TEXTURE_SIZE` limitation to display complete spectra.

I will try and put together some example code after updating my drivers.

**Comment by kmuehlbauer** [comment]
> So there's actually two "issues" here:
> 
>    1. faulty gloo.gl.GL_MAX_TEXTURE_SIZE value
>    1. circumventing the GL_MAX_TEXTURE_SIZE limitation to display complete spectra.

OK, now this makes sense. Also the for-loop is OK, I now realize that a wrongly assumed `len(imdata[0])` to be `imdata.shape[0]` which is 2049. Should read more careful next time.

Then also my suggestion to use `set_data` is somewhat out-of-place. No there is no such inside machinery. You would need to create the needed `ImageVisual`-instances as you did before. But if you then would calculate another specgram you can use `set_data` on those instances to just load new data into the `Visuals`.

> I will try and put together some example code after updating my drivers.

This would really help to get you running.

**Comment by HENDRIX-ZT2** [comment]
I've updated my Intel & Nvidia graphics drivers, but still got `gloo.gl.GL_MAX_TEXTURE_SIZE = 3379`.
Turns out I simply used it incorrectly: `3379` is merely the _ID of the value_, and the desired value is `gloo.gl.glGetParameter(gloo.gl.GL_MAX_TEXTURE_SIZE) = 16384`. So that part is solved - sorry for the confusion!

Now time to clean up the code of the multi-piece spectral display...

**Comment by HENDRIX-ZT2** [comment]
Here's the minimal working example: https://pastebin.com/hcZdpDez
This will draw the spectrum of 15,000,000 samples of noise in several pieces, in orange. So far, so good.
Uncomment the stuff starting at line 172 to draw a new green spectrum that _should_ replace the existing one.
The "issue" is at line 133, where all old pieces should be deleted. However, some of the orange spectrum persists and you can see still it when you zoom out. I read somewhere that clearing an object's `parent` property would remove it, but this is apparently not working. It should be something really simple, but I just can't figure it out...

Thanks for all the help.

I could also upload the full code if you like. There might be interest in an improved spectrogram widget. I've implemented a mel scale transform (still have to figure out the axis code, though) and the color bar widget is used to drive the normalization of the spectrum.
![grafik](https://user-images.githubusercontent.com/28632661/33955092-ab781a36-e03a-11e7-8734-7c60be890a90.png)

**Comment by kmuehlbauer** [comment]
@HENDRIX-ZT2 Just an update, your example code works for me. I'll try to add a synthetic chirp signal, which will be updated to mimic your application. Then I'll look how to do the updating in the correct way.

Chirp, we can also add some noise here later
```python
N = 15000000
t = np.arange(N) / float(sr)
f0, f1 = 1., sr / 2.
phase = (t[-1] / np.log(f1 / f0)) * f0 * (pow(f1 / f0, t / t[-1]) - 1.0)
signal = np.cos(2 * np.pi * phase)
```

**Comment by kmuehlbauer** [comment]
@HENDRIX-ZT2  But you might try to find out by yourself.

The thing is you if you do not change `sampling rate, fft_size, overlap` and the other stuff which is used to set up the visuals, you need just create the Visuals once. And you can keep them as a list like you already did.

Then If you calculate the next spectrum, just iterate over your Visual list and use `set_data` function of the visual. This will load the new data. And it will be displayed after the next update.

If you increase the amount of samples (which will add Visuals) you still can use the current ones, but you would need to fix the `STTransform` to get the Visuals at the right places.

In my applications so far I did not need to create new Visuals, but always reused those I created before. I'm at loss atm, because I really do not know how to properly destroy/remove Visuals.

@davidh-ssec @larsoner Do you have an idea how to remove Visuals from the scene?

Anyway, I think that such multi-piece visual like presented, could be a nice addition to the example section. We also can discuss the addition of logic to add the capability of super-sized textures to Texture2D or some other place.

**Comment by HENDRIX-ZT2** [comment]
@kmuehlbauer I got the desired behavior by using a reversed loop. For some reason, the default for-loop did not process all spectrum pieces. So clearing the parent makes them disappear indeed, but is this the "proper" way of deleting the old images?
```
			for i in reversed(range(0, len(images))):
				images[i].parent = None
				images.pop(i)
```

**Comment by kmuehlbauer** [comment]
@HENDRIX-ZT2 Good you found a working solution, but I also would like to know, how this is done properly. You still might think about reusing the old images. This will have a significant impact on performance.

**Comment by HENDRIX-ZT2** [comment]
@kmuehlbauer Yup that's indeed an option. Any change of the crucial parameters will require new data to be set, but as you said, I assume overwriting the existing pieces where possible and only adding / removing as many pieces as needed would cause less overhead.

**Comment by davidh-ssec** [comment]
@kmuehlbauer I'm 99% sure removing the parent is the proper way to remove a visual from the scene graph. If you are worried about performance there may be a way to block the update signal while in the for loop, but without rereading the event emitter code I can't remember the exact way to do it.

**Comment by kmuehlbauer** [comment]
> I'm 99% sure removing the parent is the proper way to remove a visual from the scene graph.

Thanks @davidh-ssec, this would also be the most likely way to do.

> If you are worried about performance there may be a way to block the update signal while in the for loop, but without rereading the event emitter code I can't remember the exact way to do it.

What I was trying to say is, that the creation of a `Visual` takes some time (don't know how heavy the overhead is). And that the best option is to re-use already created `Visual` by `set_data`. And, if we would make this a `Visual` and put all those capabilities into the `Visual` code, it should only trigger update once. Do I miss something?

**Comment by kmuehlbauer** [comment]
@HENDRIX-ZT2 It looks like your original problem is more or less solved. I'll close the issue. If there is more to discuss, we can reopen.
