### ISSUE TITLE
Possible dimensions error in Isocurve  

### ISSUE THREAD

**Issue by luigi1973** [vispy/vispy#1403]
Hi,
working by Vispy, that is great! I think I found a possible problem in
` vispy/vispy/visuals/isocurve.py.`
Isocurve works only if the data first dimension is equal to the second dimension. Taking a look at the code it seems that there is a wrong order of the arguments for the function np.meshgrid. In particular, if data has a shape, for instance (n,m), the result of the meshgrid function are two matrix (m,n).

https://github.com/vispy/vispy/blob/9d46fac28eac985fbe5d032d1581710fb74999ea/vispy/visuals/isocurve.py#L107-L109

my solution:

            if self._X is None or self._X.T.shape != data.shape:
                self._X, self._Y = np.meshgrid(np.arange(data.shape[1]), **_<- changed_**
                                               np.arange(data.shape[0])) **_<- change_**

Am I wrong? I hope it helps you.
Kind regards,
Luigi

**Comment by kmuehlbauer** [comment]
@luigi1973 

Yes, there is something fishy there. I would consider this a bug. But we need to check, which dimension is x and which is y (or cols /rows). 

Bitter truth is,  that I didn't found that, when I was implementing the matplotlib contour algorithm back then. All examples where using equal-sized (x,y) dimensions, so this didn't surface.

@larsoner Do we have any assignment on the sequence or order of dimensions (x/y, rows/columns)?

**Comment by davidh-ssec** [comment]
I agree and this needs to be handled carefully. There is always confusion surrounding rows/cols versus x/y, especially when meshgrid comes in to play.

**Comment by larsoner** [comment]
I'm not sure what the requirement is. Probably best to do whatever `matplotlib` does

**Comment by kmuehlbauer** [comment]
```python
        # if using matplotlib isoline algorithm we have to check for meshgrid
        # and we can setup the tracer object here
        if _HAS_MPL:
            if self._X is None or self._X.T.shape != data.shape:
                self._X, self._Y = np.meshgrid(np.arange(data.shape[0]),
                                               np.arange(data.shape[1]))
            self._iso = cntr.Cntr(self._X, self._Y, self._data.astype(float))
```

This is actually the code to use the matplotlib contour line tracing (directly from the c code)  in `IsocurveVisual`. Now doing this was/is not recommended from the matplotlib devs, we thought it would be good to have it here for performance reasons. The plain python approach is really slow.

IMHO the order is (rows/cols) what also @luigi1973 already suggested, but then we have to fix also those if-clause (otherwise the meshgrid will be recreated everytime same-shape new data is loaded):

```python
        # if using matplotlib isoline algorithm we have to check for meshgrid
        # and we can setup the tracer object here
        if _HAS_MPL:
            if self._X is None or self._X.shape != data.shape:
                self._X, self._Y = np.meshgrid(np.arange(data.shape[1]),
                                               np.arange(data.shape[0]))
            self._iso = cntr.Cntr(self._X, self._Y, self._data.astype(float))
```
@davidh-ssec Does that make sense to you? At least in the isocurve example the underlying image if sized (200,100) has 200 rows and 100 columns. So we should be on the safe side then, shouldn't we.

Side Note:
For those who do not need the isocurve vertices at all, they can use ContourVisual where the contour lines are created directly with shaders.

**Comment by davidh-ssec** [comment]
This makes sense to me. It definitely seemed odd to have the `.T` in there so I'm glad that is gone. We can even compare meshgrid usage to the contour code in mpl: https://github.com/matplotlib/matplotlib/blob/49d5ced86c4dd3b8ce4ec8db235a1c49b9ae2f0f/lib/matplotlib/contour.py#L1610

So yes, this all looks good to me. `shape = (num_rows, num_cols)` and `x, y = np.meshgrid(x, y)`

**Comment by kmuehlbauer** [comment]
Yes, absolutely. I'll issue a fix as suggested in near time.
