### ISSUE TITLE
Bug report, non-contiguous array

### ISSUE THREAD

**Issue by mkkb** [vispy/vispy#1442]
If doing a custom visual, the following gives a warning saying you are copying a non contiguous array.

print( v_color.flags['C_CONTIGUOUS'] , v_position.flags['C_CONTIGUOUS'] , v_size.flags['C_CONTIGUOUS'])
-> True, False, True

self.shared_program.vert['a_color'] = gloo.VertexBuffer(v_color)
self.shared_program.vert['a_position'] = gloo.VertexBuffer(v_position)
self.shared_program.vert['a_size'] = gloo.VertexBuffer(v_size)

**Comment by davidh-ssec** [comment]
@mkkb For the record, we started talking about this on gitter. There I recall you saying this was an error, but looking in the code I'm guessing you are only getting a warning.

```
                if not data.flags['C_CONTIGUOUS']:
                    logger.warning('Copying discontiguous data for struct '
                                   'dtype:\n%s' % _last_stack_str())
```

I also thought you were getting this error while using a higher level Visual class, but from your code it's obvious you are doing lower-level stuff. I think this is all expected behavior given the low-level operations you are using and that it is just a warning about copying.

If you are getting an error or there is something else going wrong here then we can reopen this, but I'm closing it for now.

**Comment by mkkb** [comment]
Yes you are right, I only got the warning. Sry i misunderstood. Im only doing numpy transformation and then Im sending the arrays to the vertex buffer. The ".flags['C_CONTIGUOUS']" I just put in to check that the arrays in fact was non contiguous, this since I didnt know where the warning spawned.
