### ISSUE TITLE
Add GLIR specification to Sphinx docs

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1469]
After talking with @campagnola on gitter and discussing changes to the GLIR specification needed to support geometry shaders I realized that the GLIR specification should really be added to the vispy documentation site (or vispy.org site). It is currently provided as a "hard to find" wiki: https://github.com/vispy/vispy/wiki/Spec.-GLIR

If it is added to the docs then it can be revision controlled along with the rest of the code and we can added version change warnings/notes in the restructuredtext. This assumes of course that the GLIR spec doesn't have its own version number.

**Comment by campagnola** [comment]
Can this just be embedded in the docstrings in gloo.glir? I am worried that otherwise, the spec docs and the actual implementation are more likely to be out of sync.

**Comment by davidh-ssec** [comment]
I am ok with that as long as the docs for the glir module are then put on the doc site (automodule). The glir.py module contains the command queue stuff and the desktop parser. Since most commands are handled in one function right now (with calls to other functions) then documenting at the top of the module makes the most sense to me.

**Comment by djhoese** [comment]
This has been done for a while, but I forgot to close this after updating the website.
