### ISSUE TITLE
Dense point clouds doesn't show properly

### ISSUE THREAD

**Issue by baptiste-mnh** [vispy/vispy#1496]
Hi, I'm currently working with depth cameras (Reaslense D400) and I need a viewer working with numpy point clouds.
Using the lib open3D I successfully open .pcd file and convert them in numpy format.
Then the viewer is able to show the point cloud with the colors but the result isn't good : 
### My code
```python
# -*- coding: utf-8 -*-
# vispy: gallery 10
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.

""" Demonstrates use of visual.Markers to create a point cloud with a
standard turntable camera to fly around with and a centered 3D Axis.
"""

import numpy as np
import vispy.scene
from vispy.scene import visuals

import open3d


#
# Make a canvas and add simple view
#
canvas = vispy.scene.SceneCanvas(keys='interactive', show=True)
view = canvas.central_widget.add_view()


# generate data
pcd = open3d.read_point_cloud("/home/baptiste-mnh/Pictures/rs/seq0c0_rs_pcd__732612060188.pcd")
array_points = np.asarray(pcd.points)
array_colors = np.asarray(pcd.colors)

# create scatter object and fill in the data
scatter = visuals.Markers()
scatter.set_data(array_points, edge_color=array_colors, face_color=(1, 1, 1, 1), size=5)


view.add(scatter)

view.camera = 'turntable'  # or try 'arcball'

# add a colored 3D axis for orientation
axis = visuals.XYZAxis(parent=view.scene)

if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
```
### Sreenshots
![zoom0](https://user-images.githubusercontent.com/30402725/43389456-0d78671c-93ec-11e8-9e95-c73db59cace0.png)
![zoom1](https://user-images.githubusercontent.com/30402725/43389461-101ef36e-93ec-11e8-8421-106e0c7fb8e9.png)
![zoom2](https://user-images.githubusercontent.com/30402725/43389462-11675964-93ec-11e8-92a2-f40de3515835.png)

Am I missing something?
Furthermore is there a way to actualize the view without closing the window?
Thanks

**Comment by djhoese** [comment]
It is hard to tell from your screenshots, but it kind of looks like there are some weird lighting effects happening. I don't have any experience with depth cameras, but should there be huge gaps in the point cloud like that (the black around the shoe)? Do you have any idea why there are so many white pixels? Maybe the MarkersVisual is adding a border around points? I don't remember the default. I guess the main question is, what exactly doesn't look right about this in your opinion?

What do you mean by "actualize the view"?

**Comment by EtienneCmb** [comment]
May be it's because you're coloring edges and not faces?

```
scatter.set_data(array_points, face_color=array_colors, size=5, edge_width=0.)
```

**Comment by baptiste-mnh** [comment]
Yes, the gaps are normals, it's a scan from only one point of view. I this code : 
`scatter.set_data(array_points, face_color=array_colors, size=5, edge_width=0.)
` and there is no notable differences.

Here is an exemple with pcl (point cloud library) :
![screenshot from 2018-07-30 18-56-11](https://user-images.githubusercontent.com/30402725/43411389-539824a6-942a-11e8-849e-81545de7e4ce.png)

By actualize I mean change the data inside the scatter whitout creating a new window or reset the point of view.

**Comment by djhoese** [comment]
Regarding changing the data, you would have to configure your UI to allow a user to specify a new point cloud input (or whatever you want) and then call the `set_data` method again on your MarkersVisual. Easiest way to do that would be to make your own class that holds on to all of your visual objects and data as well as has the handler for when the user wants data to change. You call `set_data` and `update` on your markers visual and it *should* work.

Depending on your situation you could also create multiple MarkersVisuals and change there `.visible` property to show/hide them, but you would want to be careful with performance if you have a lot of them visible at once.

I'm surprised setting the face colors instead of edge colors didn't improve the colors on the image. When I zoom in to the third image from your original post it seems like the "white" part of the shoe has a white face and a black border. I would expect playing around with the various options on the MarkersVisual would get you something better. Also is there any angle that the image looks best? I'm really not sure why the "back" of the point cloud has different colors than the "front" or am I understanding your screenshots wrong?

Lastly, what vispy backend are you using?

**Comment by baptiste-mnh** [comment]
Thank you for your response.
I also tried to color the edge and the front but it didn't change.

I think the issue is that the points which are too far from the point of view aren't visible (may be fake light shader issue).

What do you mean by "what backend"? I'm using the python library.

**Comment by djhoese** [comment]
If you compare your pcl screenshot to your vispy screenshot it looks like the colors are more vibrant or at least that is the main issue I see as far as quality of the display. To me it seems that the circles being drawn by the MarkersVisual are not one solid color as I would expect. All of my suggestions and @EtienneCmb's should have fixed this by making the circles one solid color. What exact issue are you trying to solve?

VisPy supports multiple backend GUI frameworks like PyQt, GLFW, Wx, etc. If you do `print(vispy.sys_info())` it should make it more clear for us if you aren't sure right now.

**Comment by baptiste-mnh** [comment]
Ok, after some test I've found a better solution using the Open3D viewer.
I think my pointcloud was maybe too dense for the vispy viewer.
THanks a lot for your responses and your time.

**Comment by djhoese** [comment]
I would expect density to have an effect on performance not quality of the image. Plus any performance issues would be on the OpenGL side, not vispy itself. I'm glad you found a solution, but I have a feeling this was either a GPU driver bug or some bad configuration of the object.
