### ISSUE TITLE
Draw order combined with opacity does not behave as expected

### ISSUE THREAD

**Issue by kne42** [vispy/vispy#1541]
Visual nodes drawn in front of others with sub-1 opacities set do not show the node underneath rendered.

Reproducible example:
```
#!/usr/bin/env python
from vispy import __version__, app, scene, use
from skimage import data


print('vispy version:', __version__)
use(app='PyQt5')

canvas = scene.SceneCanvas(show=True)
view = canvas.central_widget.add_view()
view.camera = scene.PanZoomCamera(aspect=1)
view.camera.flip = (0, 1, 0)

astro = scene.Image(data.astronaut(), parent=view.scene)
cam = scene.Image(data.camera(), parent=view.scene)

astro.order = 0
cam.order = -1  # will be displayed in front

# redraw the scenegraph
canvas._draw_order.clear()
canvas.update()

# offset to show that astro is really underneath cam
astro.transform = scene.STTransform(translate=(astro.size[0] / 2,
                                               astro.size[1] / 2))

# workaround since 'opacity' property does not function as intended
# fixed in development version of vispy
cam._opacity_filter.filter = (1, 1, 1, 0)  # 0 opacity

# set the view to show the images
view.camera.set_range((0, cam.size[0] + astro.size[0] / 2),
                      (0, cam.size[1] + astro.size[1] / 2))

# we expect to see the entirety of the astronaut here
app.run()
# we instead see the astronaut image with a corner cut out of it
# ie the camera image is still blocking light at 0 opacity
```

@AhmetCanSolak and I would be happy to fix this if you could give us some pointers.
cc @royerloic

**Comment by djhoese** [comment]
How does this code change with the current development version of vispy (master branch)? Have you tried with the PyQt4 backend? What about the branch used in this PR: https://github.com/vispy/vispy/pull/1394?

**Comment by djhoese** [comment]
Side note: Is there a website or screenshots of what napari is for? Just curious.

**Comment by djhoese** [comment]
I'm testing with PyQt4 and current master. `cam.opacity = 0.5`

I also see the issue.

**Comment by kne42** [comment]
Napari is a Python-native high-dimensional data visualization & processing tool. It is currently in the Pre-Alpha stage so if you want more details I can DM you but we'd prefer to keep it on the low until it's ready for an official release.

**Comment by djhoese** [comment]
Any data or a specific type of data? Specific scientific field?

**Comment by kne42** [comment]
We'll primarily be dealing with images & ROI/drawing utilities and we're not technically specific to any one field but the driving forces behind the project are to provide an easy-to-use, modular, responsive graphical processing tool for biologists.

**Comment by djhoese** [comment]
Got it to work:

1. Set `cam.order = 1` meaning it will be drawn last. The default actually worked for me, but iirc this does matter.
2. Set a z-level for your images. In your `STTransform` specify a 3rd dimension of `100`.

![image](https://user-images.githubusercontent.com/1828519/47240192-3a8e3000-d3ad-11e8-8bb1-edaa6350153b.png)

**Comment by djhoese** [comment]
Sorry, also important to note I set `cam.alpha = 0.5`.

**Comment by kne42** [comment]
Yes, we have been using this as a workaround. However, we would like this
to work with regards to draw order as well. Unless this is intended
behavior.

**Comment by sofroniewn** [comment]
Working with @kne42, our preferred solution to this now is to use 
`set_gl_state(self.layer.blending, depth_test=False)`
which may have been proposed as a solution in https://github.com/vispy/vispy/issues/1486#issuecomment-398483407 too.

It works fine for 2D image visuals, and seems to be ok for some 3D visuals but there are some complex 3D mesh visuals where you need depth testing, and in these cases neither the proposed `z-level` offset solution nor this solution work perfectly

**Comment by djhoese** [comment]
@sofroniewn Could you explain what doesn't work perfectly about them? Do you have screenshots of some of the effects you're seeing?

What does the current version of the code look like? Either with set_gl_state or z level changes?

**Comment by sofroniewn** [comment]
If we leave `depth_test=False` for a complex mesh, like the one shown in this screenshot then the triangles don't appear right, likely as opengl doesn't know how to then order the triangles, see here:
![image](https://user-images.githubusercontent.com/6531703/64287401-77570d00-cf14-11e9-82a4-0f71672c0b11.png)

If we turn `depth_test=True` then they appear correctly, see here:
![image](https://user-images.githubusercontent.com/6531703/64287493-b8e7b800-cf14-11e9-8d22-613a80ada111.png)

One thing that though seems to happen is that if I have `depth_test=True` is that I then I need to have the order reversed (i.e. -order) to get the display order to be consistent with when `depth_test=False`. I'm not quite sure why - it could relate to the setting of `glDepthFunc` as described in https://learnopengl.com/Advanced-OpenGL/Depth-testing. I can try creating a minimal code example.

That's an easy change, but we then run into problems with the opacity (some of which similar to those mentioned for 2D images in this issue when `depth_test=True`, others are unique to 3D meshes)

I know general 3D mesh issues are being discussed elsewhere like https://github.com/vispy/vispy/issues/1665 and I'm happy to try and help out there, but I'll include the examples below for completeness too.

In this example there are two mesh visuals that have been added to the canvas showing brains - one is colored using the a custom colormap the other is grayscale, the colored one is "on top"
and `set_gl_state('translucent', cull_face=False, depth_test=True)` for both.

As I reduce the opacity of the top colored one you first see a patterning artifact that I think comes from triangles on the "back" of the image coming into view - setting `cull_face=True` can improve this behavior as many offending triangles are dropped, but not all of them. This issue is likely specific to 3D rendering of the triangles

![surface_blending](https://user-images.githubusercontent.com/6531703/64282174-b03db480-cf09-11e9-8e81-70c1ee455ca4.gif)

The other issue though is that as the opacity of the "top" colored ordered visual drops to 0 it reveals a black background underneath, instead of revealing the other grayscale visual (which can be revealed by turning off the visibility of the "top" visual entirely).

Ideally as we reduced the opacity of the top visual it would start blending with the visual underneath until it disappeared revealing only the visual underneath. Similarly `additive` blending mode would allow these visuals to be combined at full opacity.

I can try making some minimal code examples if it will be helpful and am happy to align any of this investigation into 3D meshes with other on-going efforts

**Comment by sofroniewn** [comment]
So progress using `set_depth_func('lequal')` on the canvas context has fixed both the ordering problem (where I had to use a `-` sign) and the blending / triangle appearing problem - see this gif

![surface_blending_working](https://user-images.githubusercontent.com/6531703/64288897-103b5780-cf18-11e9-8f94-a30b7c8fa3cc.gif)

I will investigate further, but it seems like this setting is actually giving us all the performance features we want (including for the original stuff mentioned in this issue) and we can leave `depth_test` on or off as we need

**Comment by sofroniewn** [comment]
`set_depth_func('lequal')` resolves all issues related to ordering multiple visuals.

There is still the problem of triangles from behind showing up when there is just a single mesh visual present and opacity < 1- see here for example - with `cull_face=False'

![image](https://user-images.githubusercontent.com/6531703/64289878-df5c2200-cf19-11e9-87ff-7032803a9cf3.png)
and with `cull_face=True`:
![image](https://user-images.githubusercontent.com/6531703/64289992-16cace80-cf1a-11e9-86c3-b5d6680e652f.png)

but this is a separate issue that I can look into resolving elsewhere. It could just be that this mesh has lots of triangles that it maybe shouldn't.

**Comment by djhoese** [comment]
Maybe I can beg @rougier to weigh in on this and sanity check some of this. He has 10x (100x?) more experience with GL stuff than me.

What are the default GL state settings for the mesh visual? If you've shown that changing the default depth function/comparison produces more usable results then I'm willing to change it for MeshVisual or even change the overall default (unlikely given the GL default).

I think, from my experience, that drawing two things at the same Z level in whatever order is undefined and ends up being based on the GL/GPU implementation. I'm hoping @rougier put some logic and reasoning in to this though.

**Comment by rougier** [comment]
Yes, you cannot draw twice the same mesh or the result will be undefined because GL cannot decide which is front and back. If you want to do it anyway, you'll have to use offset:

```
glEnable( GL_POLYGON_OFFSET_FILL )
glPolygonOffset( 1.0, 1.0 )
draw mesh 1 (the one behind)
glDisable( GL_POLYGON_OFFSET_FILL )
draw mesh 2 (the one in front)
```

**Comment by rougier** [comment]
Note that you could also blend you two meshes using a shader.

**Comment by sofroniewn** [comment]
Thanks @djhoese and @rougier. I think with the new depth_func setting we'll be able to get quite far, though thanks for the tips with the `GL_POLYGON_OFFSET_FILL` and shaders too.

**Comment by larsoner** [comment]
I'm not sure there is much that can be done at the VisPy end for this, I've seen the same problem with VTK etc. One solution is to do the blending ahead of time on CPU or in the shaders. For MNE-Python we ended up writing a little CPU blending class (with color-mapping) which wasn't too bad even for realtime updates of vertices for FreeSurfer fsaverage (~150k vertices per hemi for two hemis), e.g. https://mne.tools/dev/auto_tutorials/source-modeling/plot_mne_dspm_source_localization.html#visualization
