### ISSUE TITLE
Recommended API for offscreen drawing (ndarray)?

### ISSUE THREAD

**Issue by nyanpasu64** [vispy/vispy#1543]
I observed Vispy has a lot of "cooking recipe" demos, and a "math textbook" API reference, but no good official tutorials. I've been piecing together an offscreen line drawing program, based off a combination of [basics/visuals/line](http://api.vispy.org/en/v0.4.0/examples/basics/visuals/line.html) and [demo/gloo/offscreen](http://api.vispy.org/en/v0.4.0/examples/demo/gloo/offscreen.html).

```py
class Canvas(app.Canvas):
def on_draw(self, event):
    with self._fbo:  # _fbo.activate()
        gloo.set_viewport(0, 0, *self.size)

        draw visuals...

        self.im = _screenshot((0, 0, self.size[0], self.size[1]))
        app.quit()
```

The offscreen mentions:

- Not showing the canvas (show=False).
- Rendering to an FBO.
- Manually triggering a rendering pass with self.update().
- Retrieving the scene with _screenshot().
- Closing the app after the first rendering pass (if that’s the intended scenario).

While browsing Canvas API docs, I discovered Canvas.render().
- Creates fbo and calls `fbo.activate()`
- Calls self.events.draw()

Is (self=Canvas()).update() similar or different from self.events.draw()?

Should I eliminate all references to self._fbo and instead use:

```py
c = Canvas()
c.render() # calls fbo.activate() etc.
```

If I supply data, render a new frame synchronously, and write the image to a pipe when ready, can I build a working program if I remove `on_draw()` entirely (which I assume is called by Vispy framework and not my user code)? Can I never call `app.run()` at all?

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
Disclaimer: I am not an offscreen rendering expert.

If you moved the logic of the `offscreen` example's `on_draw` method to a separate method and called it manually then you could probably get something to work. In general though, in modern VisPy which has had some changes to the `.render()` method, you can probably keep all the drawing logic in `on_draw` and call `canvas.render()` to get the image array. You shouldn't need to use `_screenshot` any more. This is especially true and good practice for SceneCanvas in my opinion because you can let the SceneCanvas deal with all its child widgets and how/when they get drawn and separate the "trigger" of that drawing to a single `.render()` call.

Regarding `.update()` versus `.events.draw()`, it will probably have the same effect except in special cases that are dependent on the GUI backend being used. The `.update()` typically calls a redraw event on the backend (if I recall correctly). The draw event is emitted as part of this process. Emitting the draw event yourself may not tell the GUI backend to update everything. So if you have a GUI window that is only a vispy canvas then this shouldn't be a problem even if I am right about the behavior.

The main point with `app.run()` is that it triggers the GUI backend. There are some (all?) backends that let you force the processing of the event queue, for example Qt's `processEvents()`. If you ran that method on the native Qt application then you could probably avoid calling `app.run()`. However, I think it would be better and more flexible to use a timer to trigger a method to do all the drawing you want and then tell the window to close (if open) or close the application. This way you can optionally run the visualization application as a normal window instead of only as an offscreen renderer.

Note that only some backends like EGL are meant for "real" offscreen rendering. Other backends like Qt I think will always require some display to exist (even if virtual/fake) to execute.

I'm closing this given the age. Let me know if you have any other questions.
