### ISSUE TITLE
module 'sys' has no attribute 'argv'" when C++ call vispy

### ISSUE THREAD

**Issue by StefanWangsjtu** [vispy/vispy#1585]
I tried to embedd vispy in Qt 5.5.1 by PythonQt, in python file ,I typed " import vispy" and I got an error:
"Traceback (most recent call last):\n"
"  File \"/home/stefan/QtObjects/Vispy_based_MeshLab/test.py\", line 8, in <module>\n"
"    "
"from vispy import app"
"\n"
"  File \"/usr/local/lib/python3.5/dist-packages/vispy/__init__.py\", line 30, in <module>\n"
"    "
"from .util import config, set_log_level, keys, sys_info  # noqa"
"\n"
"  File \"/usr/local/lib/python3.5/dist-packages/vispy/util/__init__.py\", line 10, in <module>\n"
"    "
"from .config import (config, sys_info, save_config, get_config_keys,  # noqa"
"\n"
"  File \"/usr/local/lib/python3.5/dist-packages/vispy/util/config.py\", line 470, in <module>\n"
"    "
"_init()"
"\n"
"  File \"/usr/local/lib/python3.5/dist-packages/vispy/util/config.py\", line 91, in _init\n"
"    "
"_parse_command_line_arguments()"
"\n"
"  File \"/usr/local/lib/python3.5/dist-packages/vispy/util/config.py\", line 151, in _parse_command_line_arguments\n"
"    "
"opts, args = getopt.getopt(sys.argv[1:], '', argnames)"
"\n"
"AttributeError"
": "
"module 'sys' has no attribute 'argv'"
"\n"

How to fix it?

**Comment by djhoese** [comment]
Hi @StefanWangsjtu. I'm not familiar with PythonQt, but this is not a problem with vispy, but with how you or PythonQt is creating a python environment. Whenever python is started it makes any command line arguments available to the python application via the `sys` module in the `argv` attribute. Vispy expects to have this information available since it is available in every normal python environment.

After doing some searching I found this: https://sourceforge.net/p/pythonqt/discussion/631393/thread/502204d0/
Looks like you may have to add some information to your PythonQt creation to add argv to the python environment. Since I don't have any experience with PythonQt I don't think I can be of much help. Good luck.

**Comment by StefanWangsjtu** [comment]
@djhoese Thank you very much for your useful advise, I tried the solution that provided in https://sourceforge.net/p/pythonqt/discussion/631393/thread/502204d0/ , and I got another problem in C++.  Anyway, thank you for your reply!
