### ISSUE TITLE
How to determin whether a visual object is out of view/windows

### ISSUE THREAD

**Issue by yepengxj** [vispy/vispy#1625]
How to determin whether a visual object is out of view/windows
I want fully display a visual object in a view/windows, How could I check whether visual object is out of view.

**Comment by djhoese** [comment]
My best guess would be to add an event handler (`on_view_change` if I recall correctly) where you could use the visuals transform to figure out where the visuals coordinates end up on the GPU buffer. Something like `pos = my_visual.transforms.get_transform().map(visual_pos)` (I think) should give you the GPU position which should be between 0 and 1 (maybe it is -1 to 1). If it is beyond that then it is off the canvas.

So that would probably work, however, you'll want to be careful doing things on every view change or it could effect your performance. I'm also curious what are you trying to accomplish? There are things that the GPU does to *not* draw things that are off screen or out of view to the viewer so you may not need this type of logic.

**Comment by yepengxj** [comment]
@djhoese Thanks for you help, I'm using a sub viewbox to display a bounding box, so it's necessary to display the whole box in the view. I know that we can use RMB or LMB to change the view of viewbox to display entire box, but I want to do that automatically
![pic1](https://user-images.githubusercontent.com/7285026/56471272-3984ab00-6483-11e9-9f34-19ddc06fa131.png)
![pic2](https://user-images.githubusercontent.com/7285026/56471274-3ee1f580-6483-11e9-919a-42a6d2f05080.png)
![pic3](https://user-images.githubusercontent.com/7285026/56471276-41dce600-6483-11e9-82b8-c19a81027333.png)

**Comment by djhoese** [comment]
So do you want to make the object disappear when it is zoomed in too far or out too far?

Or do you want to stop the user from zooming in/out when they go too far?

**Comment by yepengxj** [comment]
I want to display a boxing box neither too small nor too big, just fit size of viewbox

**Comment by djhoese** [comment]
Ok, so you aren't worried about using a camera, you want the visual to immediately show at the full size of the viewbox? Put another way, when the user opens the window the box should fill the window.

If I'm understanding this correctly then you could use a combination of:

```
my_visual.transform = STTransform()
```

then to set how large the box should be you can do the below (when the window first opens and when it is resized) to set the scaling of the X, Y, and Z dimensions:

```
my_visual.transform.scale = (2.5, 2.5, 2.5)
```

To determine what the scale should be...maybe:

```
scale_x = canvas.size[0] / 800
scale_y = canvas.size[1] / 600
# pick the minimum scale
scale = min(scale_x, scale_y)
my_visual.transform.scale = (scale, scale, scale)
```

I think something like this would work. I can't come up with something better right now.

**Comment by yepengxj** [comment]
@djhoese Thanks of your patient, That's what I need.
