### ISSUE TITLE
faster mesh generation

### ISSUE THREAD

**Issue by bryantChhun** [vispy/vispy#1635]
I'm interested in using vispy to quickly render millions of lines/vectors (1-4 million, 30 fps).  Using GL lines (https://github.com/vispy/vispy/blob/master/vispy/visuals/line/line.py) was great and performant, but the team has decided to move towards rendering everything as a mesh object for reasons I won't get into here.  So now we need to calculate every line as two triangles, and the overhead of calculating vertices+faces for even 1m "lines" is prohibitive (roughly 1 second for about 4m "lines").

Question:  Is there a way to accelerate the calculation of vertices+faces?  Does vispy provide any c-accelerated code for this?

**Comment by djhoese** [comment]
I may not be the best person to answer this but I'll at least get the ball rolling. @rougier probably knows more about this. Things that vispy has that may be of use to you:

1. AGG lines (in that same line.py module you linked to) will draw lines using multiple triangles (see [here](https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc) for details on the concept). I've been told by @rougier I think that mentioned the algorithm used by vispy may not be the most performant but was much simpler to implement.
2. Triangulation utilities: https://github.com/vispy/vispy/blob/master/vispy/geometry/triangulation.py
3. Isosurface utilities: https://github.com/vispy/vispy/blob/master/vispy/geometry/isosurface.py

If you end up needing to implement a faster AGG algorithm it would be great if it could be contributed to vispy for others to use.

**Comment by rougier** [comment]
If you need only line segment, you can also use geometry shader such that you don't have to compute anything on the CPU.

**Comment by bryantChhun** [comment]
> If you need only line segment, you can also use geometry shader such that you don't have to compute anything on the CPU.

When I used GL lines, i represented each vector as two coordinates with connector="segments". So I assume this means i am using only segments.

Could you point me to the geometry shader you refer to?

**Comment by djhoese** [comment]
In the master branch we recently merged the functionality to support "geometry shaders". You can see an example here: https://github.com/vispy/vispy/blob/master/examples/basics/gloo/geometry_shader.py

I would google the concept of geometry shaders to better understand what @rougier meant. However, keep in mind that geometry shaders require a newer version of OpenGL and you will have trouble getting it to work with OSX due to the way it requires these versions enabled (core versus compatibility GL profiles).

**Comment by rougier** [comment]
https://github.com/rougier/glsl-experiments/blob/master/linestrip-geometry-shader.py

**Comment by bryantChhun** [comment]
Resurrecting an old thread:

Did a fresh install of PyOpenGL, Vispy, to a new python environment.  Then tried to run the geometry_shader.py script @djhoese posted above.  Then get the following error:

> File "/Users/bryant.chhun/PycharmProjects/vispy/vispy/gloo/glir.py", line 930, in set_data
    (self._target, errormsg))
RuntimeError: Shader compilation error in 35633:
    on line 1: '' :  version '330' is not supported
      #version 330
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x10cdd3ac8>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x10cdd3ac8>> repeat 2
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x10cdd3ac8>> repeat 4

I'm running OSX 10.13.6 on MBPR.  Overall I'm seeing people post issues with GLSL compatibility problems.  This explicit version problem was referenced in #796 but I think was resolved.  Issue #1715 referenced a (different?) issue with geometry shaders.

Hopefully my error is different?  Here's my output of sys_info:

> Platform: Darwin-17.7.0-x86_64-i386-64bit
Python:   3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)  [Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy:    1.17.3
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.13.1', '5.13.0')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '2.1 ATI-1.68.20'
MAX_TEXTURE_SIZE: 16384
Extensions: 'GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_blend_equation_separate GL_ATI_blend_weighted_minmax GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGI_color_matrix GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod '

**Comment by djhoese** [comment]
i've generally had a lot of trouble getting new OpenGL features to work on a mac. It seems like you have the necessary extensions to support geometry shaders, but the GLSL 3.30 shader language is not available in the "compatibility" GL profile on your system. The other option for GL profile is "core" which basically means "I want to use the newest features of the GPU". In PyQt5 it defaults to the compatibility profile, but does have some function calls that can be made (from what I remember) to force the "core" profile. However, Vispy does not have an interface for controlling this.

Additionally, when I last tested this on my mac (which I don't have any more), switching to the core profile forced a certain calling sequence for initializing and using the GPU that Vispy was **not** doing. The way Vispy uses the GPU through OpenGL calls works with the compatibility profile but for some reason the core profile is more strict or maybe was buggy on my system. I know @campagnola (the person who added geometry shaders originally) was able to use them fine in linux. I have not tested this since I got my linux machine.

Lastly, MacOS has dropped support for OpenGL since Mojave so you may have limited functionality running things on a macbook.

Disclaimer: This is all said from what I remember when dealing with this the last time. I could be wrong about some things. @rougier likely knows more.

**Comment by queenish001** [comment]
@bryantChhun Is your doubt resolved?

**Comment by djhoese** [comment]
I'm going to close this issue due to the age and lack of discussion. The OSX issues are a pretty big roadblock, but there may still be ways around it in the future (but possibly not simple). If there is still active work on this then we can reopen this issue to continue the discussion.
