### ISSUE TITLE
scene.visuals.Compound corrupts subvisuals' transformations

### ISSUE THREAD

**Issue by risa2000** [vispy/vispy#1648]
I am running VisPy the current branch. When using `scene.visuals.Compound` I noticed that it resets (or corrupts) subvisuals transformation.

Running the following code:
```python
"""
VisPy test
"""
# standard imports
import sys

# external imports
import numpy as np

# VisPy imports
from vispy import app, scene, visuals

canvas = scene.SceneCanvas(keys='interactive', bgcolor='white', show=True)
view = canvas.central_widget.add_view()
view.camera = scene.TurntableCamera(up='+y', azimuth=110, elevation=15, fov=60)
axis = scene.visuals.XYZAxis(parent=view.scene)

cube1 = scene.visuals.Cube(name='cube1')
cube1.transform = visuals.transforms.STTransform(translate=[0, -1, 0])
cube2 = scene.visuals.Cube(name='cube2')
cube2.transform = visuals.transforms.STTransform(translate=[0, 1, 0])
com1 = scene.visuals.Compound([cube1, cube2], name='com1')

view.add(com1)
#view.add(cube1)
#view.add(cube2)

# Add a 3D axis to keep us oriented

if __name__ == '__main__':
    if sys.flags.interactive == 0:
        app.run()
```
I would expect to see two cubes one shifted up and one down by 1.0. I.e. this:
![cube_2_vert](https://user-images.githubusercontent.com/1336835/59159814-7ce8b680-8acf-11e9-923e-dd4a33ab43dd.png)

Instead it looks like the transformations set for individual cubes got ignored/erased by Compound and the cubes are "squashed" at origin:
![cube_2_squashed](https://user-images.githubusercontent.com/1336835/59159842-a4d81a00-8acf-11e9-93ff-81726c4df0d2.png)

Interestingly, if I just change the way the view is initialized to this:
```python
#view.add(com1)
view.add(cube1)
view.add(cube2)
```
while keeping creation of `com1` in code. The image I get is this:
![cube_2_off_up](https://user-images.githubusercontent.com/1336835/59159862-e1a41100-8acf-11e9-9d2a-0f62fc13a7da.png)

Which suggests that both cubes have now the translation set to [0, 1, 0], i.e. the one originally set for `cube2`. To display the cubes correctly, I have to remove completely `com1` from the code.

From the wording in the doc (http://vispy.org/scene.html#vispy.scene.visuals.Compound) I understood that `Compound` could be used to build "composite" objects. It does not seem possible if it breaks the transformations of its children. Is it a bug, or am I reading/using the doc wrong?

Note: It gets even more fuzzy when trying to build Compound visual out of another Compound visuals, but I guess it all boils down to the behavior described above.

**Comment by djhoese** [comment]
Very interesting. Based on what I'm seeing in the code, this is entirely expected. See in the code here:

https://github.com/vispy/vispy/blob/master/vispy/visuals/visual.py#L551-L563

and here:

https://github.com/vispy/vispy/blob/master/vispy/visuals/visual.py#L580-L583

I think the expectation is that your individual sub-visuals differ by their vertex/coordinates, but otherwise share the same transform of those coordinates. I will see though that your use case is completely reasonable.

I think the compound visual as-is makes sense if you think about the basic Canvas API instead of the higher-level SceneCanvas API you are using. In the `SceneCanvas`, the transforms of parent visuals propagate to the children visuals. So changing the CompoundVisual's transform would automatically take effect on its subvisuals based on the chaining of transforms. In the regular Canvas API however, that wouldn't happen so setting `my_compound.transform = X` is a shortcut or simplification of assigning the transforms for each subvisual.

Perhaps one possibility is to add a keyword argument to the CompoundVisual that turns this transform handling off (on by default for backwards compatibility). I'd be open to a pull request with this functionality added. @larsoner @kmuehlbauer thoughts?

**Comment by risa2000** [comment]
You are right. The code is pretty clear about how it expects `Compound` to work. But then I am wondering if there is any other way in VisPy to get the "composite" object I described above. I am working with several objects, where it is far easier to make calculation of meshes in their coordinate system and then simply translate (and rotate) them into the position in the final scene.

Plus there are few levels of "composition" so ideally I would like to end up with this:
```
Compound#1 (Transform TC1)
|-> Compound#2 (Transform TC2)
|   |-> Object#1 (Transform TO1)
|   |-> Object#2 (Transform TO2)
|-> Compound#3 (Transform TC3)
|   |-> Object#3 (Transform TO3)
|   |-> Object#4 (Transform TO4)
```
having the `Object#4` being transformed by: `TC1*TC3*TO4`

**Comment by djhoese** [comment]
I would suggest using the raw `Node` class (https://github.com/vispy/vispy/blob/master/vispy/scene/node.py#L15) in place of the `Compound` objects in your graph above. By making your visuals children of these individual `Node` instances you will be able to set a transform on the individual visuals *and* on the `Node` objects.

I've done this myself in my own applications where each visual had a transform to convert its coordinates to some intermediate representation and then the parent transformed these intermediate coordinates to the final canvas coordinates.

**Comment by queenish001** [comment]
@djhoese
