### ISSUE TITLE
Vispy on DigitalOcean

### ISSUE THREAD

**Issue by ejtasker** [vispy/vispy#1649]
Hi -- I've written a fast and efficient sphere renderer with vispy but I'd like to deploy it on the web-hosting platform, DigitialOcean. DigitialOcean runs ubuntu, but doesn't have access to GPUs. Does this make it impossible to run vispy?

**Comment by djhoese** [comment]
I can't say with any certainty, but vispy requires OpenGL drivers so that it can run OpenGL commands. On our automated testing for linux (travis) we use fake/virtual buffer using xvfb. If DigitalOcean's servers can run that then it should be feasible.

That said, it would be best if you could get a server with at least an Intel Integrated GPU.
