### ISSUE TITLE
Time.clock was deprecated in python 3.3, and was removed in python 3. 8

### ISSUE THREAD

**Issue by ritobanrc** [vispy/vispy#1659]
From the python 3.8 changelog:https://docs.python.org/3/whatsnew/3.8.html

> The function time.clock() has been removed, it was deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have a well defined behavior. (Contributed by Matthias Bussonnier in bpo-36895)

Vispy still uses in on windows in ptime (vispy/util/ptime.py line 23)

**Comment by djhoese** [comment]
From what I can tell we (@larsoner) fixed this in a past pull request. See https://github.com/vispy/vispy/blob/master/vispy/util/ptime.py#L35-L41 which includes code that hasn't been released yet, but I think it is accurate.

**Comment by djhoese** [comment]
@ritobanrc We released vispy 0.6 about a week and a half ago. This should include the changes to the related time functions. Could you verify that things look correct to you in the master branch?

**Comment by kmuehlbauer** [comment]
@ritobanrc Does latest vispy solve your issue?

**Comment by djhoese** [comment]
Since we haven't had any updates I think we can consider this resolved. Feel free to comment if it seems to not be fixed.

**Comment by rowatc** [comment]
I am running Python 3.10.8 with vispy 0.7.3 py310h9909e9c_0 on Win 11.

When I `canvas = scene.SceneCanvas(keys='interactive')`, I get `AttributeError: module 'time' has no attribute 'clock'`.

This happens with 'raw' vispy, and after I edit ptime.py, replacing systime.time() with systime.perf_counter() or systime.process_time().

[My underlying problem is simpler: I want to do an isosurface write_mesh with axes, so should NOT need anything time related.]

**Comment by djhoese** [comment]
@rowatc I'm not sure if you're asking a question or reporting a bug, but vispy 0.7.3 is over a year old and we have had ~13 releases since then. This has been fixed.

**Comment by rowatc** [comment]
@djhoese updated to 0.12.1.  That fixes the `SceneCanvas` error.  Thanks!
