### ISSUE TITLE
detects a virus

### ISSUE THREAD

**Issue by develooper1994** [vispy/vispy#1674]
Link: https://www.lfd.uci.edu/~gohlke/pythonlibs
vispy-0.6.0-cp37-cp37m-win_amd64.whl
Windows 10 last version detects a virus.

**Comment by larsoner** [comment]
AFAIK we did not distribute those. Are these okay?

https://pypi.org/project/vispy/0.6.0/#files

**Comment by larsoner** [comment]
Also this might be a problem

https://www.reddit.com/r/Python/comments/6rdd21/psa_dont_use_the_unofficial_windows_binaries_in/

What is the md5 you get for `vispy-0.6.0-cp37-cp37m-win_amd64.whl` from Gohlke's site? I get:
```
larsoner@bunk:~/Desktop$ md5sum vispy-0.6.0-cp37-cp37m-win_amd64.whl 
8a82619a8545ac08d5aa3f1332725a70  vispy-0.6.0-cp37-cp37m-win_amd64.whl
```
For ours from PyPi, you can check with `sha256sum` that it matches what Pypi says it should be. This is not the same as the ones from Gohlke's site (because we did not build/upload them).

**Comment by cgohlke** [comment]
Can't reproduce locally with Windows 10 defender and McAfee VirusScan. See also [virustotal](https://www.virustotal.com/gui/url/cb8a0931c31eecc689b1d905dfbd179789b0182e188edf9e7d8b72cc80c5619c/detection?gclid=EAIaIQobChMIk7OblefQ4wIVhq_sCh0VPQfMEAAYASAAEgKmEPD_BwE).

**Comment by develooper1994** [comment]
https://pypi.org/project/vispy/0.6.0/#files link is okay.
