### ISSUE TITLE
Setting  scene.camera  view

### ISSUE THREAD

**Issue by EnriqueSolarte** [vispy/vispy#1701]
Helo everybody, 
I would like to know how to set a specific camera location view for a point cloud visualization. Currently, I am using scene.TurntableCamera () and scene.ArcballCamera (), but they start from a default view, of course, I can move with my mouse the camera view, but I would like to set a fixpoint view. 

In advance, thank you for your help

**Comment by sofroniewn** [comment]
For the `ArcballCamera` I have used the `center` and `scale_factor` properties to set the rotation center and zoom respectively

**Comment by sofroniewn** [comment]
You can also use the `_quaternion` property to set the view angle for the `ArcballCamera`. I do it by creating a new Quaternion with the method below, but the one could imaging adding to the api so that `quaternion` om `ArcballCamera` was a tuple property and setting it did triggered that update under the hood.  https://github.com/vispy/vispy/blob/8cb75ccf4393a22fe30f16cc68607862e8054f10/vispy/util/quaternion.py#L213

**Comment by EnriqueSolarte** [comment]
Thank you so much. 
I guess using an external camera transformation is a better option.  I will use it. 
BTW, so far my current solution was:
`scene.TurntableCamera(elevation=30, azimuth=0, up='-y')`
up parameter can be set as '-x', 'x', 'z', etc. Doing so, azimuth and roll define the desaried view.
Just in case it helps someone.
Again, thank you so much

**Comment by queenish001** [comment]
@djhoese This one can be closed.
