### ISSUE TITLE
Updating scene after running vispy.app.run()?

### ISSUE THREAD

**Issue by gilmoujw** [vispy/vispy#1719]
First of all, thank you for developing this great library. I am using it for 3D visualization in my research. My problem is that after setting up the scene, I use vispy.app.run() to actually display it. vispy.app.run() blocks execution, which makes sense. My issue is that I would like to run other software and update the scene data in parallel with the visualization enabled by vispy.app.run() . Is it safe to simply execute vispy.app.run() in one thread and update the data for the scene in another? If not, is there another way I can keep the vispy window interactive while also doing other things in parallel? Thank you.

**Comment by djhoese** [comment]
This is a common problem in GUI programming and the exact solution will depend on what backend you are using. For now I'll assume PyQt5. You are correct that the usual way this is solved by having multiple threads: the main (a.k.a. drawing, a.k.a. GUI) thread and your computation/data thread. The trick is to make sure that drawing commands (calls to gloo or `.update()` functions in vispy, or most commands in the GUI framework) only happen in the main drawing thread. The best way to do this is to use signals and slots in Qt. You would make it so your thread would update various data values, emit a signal saying "data has been updated" or "here is the data", and then the GUI thread will receive that signal and run its connected "slot" function to update the GUI.

The other option that you'll see in some of vispy's examples is to use a timer. By using a timer you are essentially slipping a function in to the GUI thread's event loop that will run in the main GUI thread. The `app.run()` call is essentially running a list of functions/events. When it hits the end of the list it starts over with some basic functions that it always runs. New functions can be added if something happens by the user (mouse click, keyboard event, etc). Another type of event that can happen is a timer event. When a timer event happens, a new function is added to the event loop's list of functions to run. The gotcha here is that since the timer triggered function is running in the main thread it should **NOT** run for a long time otherwise it stops the event loop from moving on to the other functions in a reasonable amount of time. This makes your GUI seem glitchy and like it is hanging. The upside is that you can call usually call drawing functions/commands from a timer function.

More information than you probably wanted...but there it is.

**Comment by gilmoujw** [comment]
Hi djhoese. Thank you for the level of detail, it helped my understanding significantly. Based on what you said and looking at the vispy contour example and the .app documentation I was able to implement the parallel functionality I wanted. Thanks again.

**Comment by JasonACDsouza** [comment]
Hi @gilmoujw,

I am trying to do exactly what you were trying to achieve. I want to run the update function in parallel to the data that is been generated but once the `vispy.app.run()` runs, I am not able to communicate to the outside threads/processes. I am using a queue to try to achieve what I require but to no avail. For simplicity this is what I am doing, 

```
import numpy as np
import vispy.scene
from vispy.scene import visuals
from vispy import app
import glob
import time
from queue import Queue
from multiprocessing import Process

q1 = Queue()


def update_here(event, count = None):
	print("I AM HERE with count, ", count)
	if q1.empty():
		pass
	else:
		content = q1.get()

		print("I AM HERE WITH COUNT, ", content)



def start_vis():
	cnt = 1000

	timer = app.Timer('auto', connect=update_here(count = 10000), start=0.05)

	# timer = app.Timer()
	# timer.connect(update_here(count = cnt))
	# timer.start(0.05)

	import sys
	if sys.flags.interactive != 1:
		vispy.app.run()

	
def update_que():
	count = 0
	while True:
		count = count+1 
		q1.put(count)

p2 = Process(target = update_que, args = ())
p1 = Process(target = start_vis, args = ())
p2.start()
p1.start()
p2.join()
p1.join()
```
This should print out the value from the queue q1 in the **update_here** function but it does not.
Could you possibly tell me how did you achieve the parallel mechanism? Thanks.

**Comment by djhoese** [comment]
@JasonACDsouza Please do not comment on closed issues with your own tasks. You've already commented about this in your own issue and I am working on a reply. If you'd really like someone else's opinion then mention them in your own issue.
