### ISSUE TITLE
Change how release notes are generated and distributed

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1720]
After having some conversations on gitter with @hmaarrfk and @jni, I think we should update how we generate release notes. Right now it is done manually by whoever is releasing the version of vispy (me). The notes are a restructuredtext page in the sphinx docs: http://vispy.org/releasenotes.html. This is prone to human error and is difficult to link to GitHub issues/PRs/discussions.

A lot of projects store one or more release notes files inside the repository itself and I think that could be a good idea for us. The main point of this issue though is that I'm wondering what options exist for auto-generating release notes from GitHub content. For example, I use `loghub` from the Spyder community on some of my own projects. Running it for the 0.6.2 release that I would like to make this week I can do:

```
loghub vispy/vispy -u djhoese -st v0.6.1 -plg "type: fix" "Bugs fixed" -plg "type: performance" "Performance" -plg "type: enhancement" "Features added" -plg "docs-website" "Documentation changes"
```

And get:

```
###############################################################################
## Version <RELEASE_VERSION> (2019/10/13)

### Issues Closed

* [Issue 1718](https://github.com/vispy/vispy/issues/1718) - Problem of headless EGL rendering?
* [Issue 1711](https://github.com/vispy/vispy/issues/1711) - qt menubar
* [Issue 1687](https://github.com/vispy/vispy/issues/1687) - Issue with simple_glut.py
* [Issue 1686](https://github.com/vispy/vispy/issues/1686) - GPU utilization
* [Issue 1685](https://github.com/vispy/vispy/issues/1685) - .obj rotation problem
* [Issue 1684](https://github.com/vispy/vispy/issues/1684) - Looking for suitable config
* [Issue 1683](https://github.com/vispy/vispy/issues/1683) - Opening & Loading .OBJ Textures
* [Issue 1681](https://github.com/vispy/vispy/issues/1681) - PanZoom camera interaction becomes unusable if the up parameter is changed from "+z" ([PR 1682](https://github.com/vispy/vispy/pull/1682))
* [Issue 1680](https://github.com/vispy/vispy/issues/1680) - Load .OBJ Model
* [Issue 1396](https://github.com/vispy/vispy/issues/1396) - Errors on startup of my application with version v.0.6 (dev)

In this release 10 issues were closed.

### Pull Requests Merged

#### Bugs fixed

* [PR 1712](https://github.com/vispy/vispy/pull/1712) - Volume visual has unset variable texture2D_LUT
* [PR 1703](https://github.com/vispy/vispy/pull/1703) - Fix MarkersVisual.set_data crash when pos is None
* [PR 1691](https://github.com/vispy/vispy/pull/1691) - Fix numpy futurewarning in dtype creation

#### Performance

* [PR 1682](https://github.com/vispy/vispy/pull/1682) - Improve PanZoom camera performance when non-+z direction is used ([1681](https://github.com/vispy/vispy/issues/1681))

#### Features added

* [PR 1706](https://github.com/vispy/vispy/pull/1706) - Switch to setuptools_scm for automatic version numbering

In this release 5 pull requests were closed.

###############################################################################
```

<details>
<summary>Rendered Markdown:</summary>

### Issues Closed

* [Issue 1718](https://github.com/vispy/vispy/issues/1718) - Problem of headless EGL rendering?
* [Issue 1711](https://github.com/vispy/vispy/issues/1711) - qt menubar
* [Issue 1687](https://github.com/vispy/vispy/issues/1687) - Issue with simple_glut.py
* [Issue 1686](https://github.com/vispy/vispy/issues/1686) - GPU utilization
* [Issue 1685](https://github.com/vispy/vispy/issues/1685) - .obj rotation problem
* [Issue 1684](https://github.com/vispy/vispy/issues/1684) - Looking for suitable config
* [Issue 1683](https://github.com/vispy/vispy/issues/1683) - Opening & Loading .OBJ Textures
* [Issue 1681](https://github.com/vispy/vispy/issues/1681) - PanZoom camera interaction becomes unusable if the up parameter is changed from "+z" ([PR 1682](https://github.com/vispy/vispy/pull/1682))
* [Issue 1680](https://github.com/vispy/vispy/issues/1680) - Load .OBJ Model
* [Issue 1396](https://github.com/vispy/vispy/issues/1396) - Errors on startup of my application with version v.0.6 (dev)

In this release 10 issues were closed.

#### Bugs fixed

* [PR 1712](https://github.com/vispy/vispy/pull/1712) - Volume visual has unset variable texture2D_LUT
* [PR 1703](https://github.com/vispy/vispy/pull/1703) - Fix MarkersVisual.set_data crash when pos is None
* [PR 1691](https://github.com/vispy/vispy/pull/1691) - Fix numpy futurewarning in dtype creation

#### Performance

* [PR 1682](https://github.com/vispy/vispy/pull/1682) - Improve PanZoom camera performance when non-+z direction is used ([1681](https://github.com/vispy/vispy/issues/1681))

#### Features added

* [PR 1706](https://github.com/vispy/vispy/pull/1706) - Switch to setuptools_scm for automatic version numbering

In this release 5 pull requests were closed.

</details>

Other options? Thoughts? We could pretty easily migrate the existing release notes to any other format. Even if we don't use loghub or some auto-generated tool I will probably use it to get a list of PRs since the last tag.

**Comment by hmaarrfk** [comment]
loghub seems pretty sweet.  Good tagging all the PRs.

Numpy started to use towncrier, so that you can add more detailed messages to certain PRs that explain things in more detail.

**Comment by djhoese** [comment]
Interesting. So towncrier requires adding those news stories to the directory and then generates the rst for you when generating the sphinx docs, right?

**Comment by hmaarrfk** [comment]
yeah, something like that.

I think a combination of the two is really nice. 
It is good to see every single PR, especially for those that make their contribution!

**Comment by kmuehlbauer** [comment]
@djhoese This would indeed lessen the burden of manual collection of the changes. Not sure how much effort will be involved to use `towncrier`. Are there any docs beside the README in the repo?

**Comment by jni** [comment]
I haven't seen a "snippet template", but using towncrier seems easy, per the NumPy "how to release" docs:

https://github.com/numpy/numpy/blob/master/doc/HOWTO_RELEASE.rst.txt#check-the-release-notes

**Comment by jni** [comment]
so it's just a matter of being disciplined in adding snippets.

**Comment by larsoner** [comment]
I've used https://github.com/github-changelog-generator/github-changelog-generator and it's [pretty easy](https://sphinx-gallery.github.io/maintainers.html#prepare-for-release). For each PR before merge you make sure it's marked as `bug` or `enhancement` then it lands in the correct category in the generated list. And `pandoc` allows converting between formats if need be.

+1 on using some automated method, whatever seems like least effort seems reasonable to me

**Comment by djhoese** [comment]
Seems like we could have sphinx parse a markdown document too if we wanted: https://www.sphinx-doc.org/en/master/usage/markdown.html
I'm not against having the docs page point to the markdown file in github either, but if someone feels strongly about having a dedicated sphinx page (a softlink to the changelog markdown file in the repository) then that probably isn't a big deal either. Oh wait, actually that might be annoying because of how the docs and code repositories are separated.

Speaking of PR labeling, when I joined the project there was already a `bug` and a `fix` label. I'm not sure the distinction is needed (a "bug" label on an issue is a bug, a "bug" label on a PR is a fix for that bug). Another label I've been using in projects like Satpy has been `backwards-incompatibility` so that I can put them in a separate section in the changelog.

Based on stars alone I feel like we should use github-changelog-generator. Doing more research...

**Comment by djhoese** [comment]
I'm still on the fence about towncrier. Looking at their own [release notes](https://github.com/hawkowl/towncrier/blob/master/NEWS.rst) I can see the appeal of having longer human-readable descriptions for changes. It sounds like a lot of extra work so I'm hesitant. Typically I've seen well crafted PR titles as "good enough" but I'm also not a user so who knows. I'm not sure I fully understand the workflow with towncrier either.

**Comment by djhoese** [comment]
I tried using `github_changelog_generator` tonight but I can't get it to behave. Here's my command so far after installing it in my user account on Ubuntu:

```
~/.gem/ruby/2.5.0/bin/github_changelog_generator -u vispy -p vispy --since-tag v0.6.1 --unreleased-only --no-issues-wo-labels --no-pr-wo-labels --no-filter-by-milestone -t <mygithubtoken>
```

Even with all of this stuff it *still* wants to add all issues back from issue 1. I mean maybe it is excluding some closed ones, but it shouldn't be going back to the beginning either. I don't think I've gotten it to complete without hitting a rate limit either, even with my github token set.

Anyone have ideas? I can't even get to formatting it the way I like because it isn't working the way I want.

**Comment by larsoner** [comment]
The since/between stuff can be a bit buggy. It looks like this is what I used for [sphinx-gallery](https://sphinx-gallery.github.io/maintainers.html):
```
github_changelog_generator sphinx-gallery/sphinx-gallery --between-tags v0.3.0,v0.4.0
```
I don't need to pass `-t` because I have `CHANGELOG_GITHUB_TOKEN` in my `.profile`. So adapting that I can do:
```
$ github_changelog_generator --max-issues 500 vispy/vispy --between-tags v0.6.1,HEAD
```
It complains about HEAD but it still works. (If you had an actualy tag like 0.7.0 or 0.6.2 it would probably "just work" with this syntax.) In any case, I get this:

<details><summary>CHANGELOG.md (trimmed to just the 0.6.1->master stuff)</summary>

# Change Log

## [Unreleased](https://github.com/vispy/vispy/tree/HEAD)

[Full Changelog](https://github.com/vispy/vispy/compare/v0.6.1...HEAD)

**Closed issues:**

- Python 3.8 RuntimeError: dictionary keys changed during iteration [\#1729](https://github.com/vispy/vispy/issues/1729)
- VolumeVisual.set\_data method and copy=False may lead to unexpected behavior [\#1727](https://github.com/vispy/vispy/issues/1727)
- Updating scene after running vispy.app.run\(\)? [\#1719](https://github.com/vispy/vispy/issues/1719)
- Problem of headless EGL rendering? [\#1718](https://github.com/vispy/vispy/issues/1718)
- Intersected visuals create defects \(z-fighting?\) [\#1716](https://github.com/vispy/vispy/issues/1716)
- qt menubar [\#1711](https://github.com/vispy/vispy/issues/1711)
- PyQt5 screenshot uses entire window [\#1695](https://github.com/vispy/vispy/issues/1695)
- Issue with simple\_glut.py [\#1687](https://github.com/vispy/vispy/issues/1687)
- GPU utilization [\#1686](https://github.com/vispy/vispy/issues/1686)
- .obj rotation problem [\#1685](https://github.com/vispy/vispy/issues/1685)
- Looking for suitable config [\#1684](https://github.com/vispy/vispy/issues/1684)
- Opening & Loading .OBJ Textures [\#1683](https://github.com/vispy/vispy/issues/1683)
- PanZoom camera interaction becomes unusable if the up parameter is changed from "+z" [\#1681](https://github.com/vispy/vispy/issues/1681)
- Load .OBJ Model [\#1680](https://github.com/vispy/vispy/issues/1680)
- Triangulation with holes [\#1657](https://github.com/vispy/vispy/issues/1657)
- Creating and rendering visuals in real time [\#1645](https://github.com/vispy/vispy/issues/1645)
- Errors on startup of my application with version v.0.6 \(dev\) [\#1396](https://github.com/vispy/vispy/issues/1396)

**Merged pull requests:**

- Fix Python 3.8 compatibility in Canvas 'keys' update [\#1730](https://github.com/vispy/vispy/pull/1730) ([GuillaumeFavelier](https://github.com/GuillaumeFavelier))
- Fix VolumeVisual modifying user provided data in-place [\#1728](https://github.com/vispy/vispy/pull/1728) ([tlambert03](https://github.com/tlambert03))
- Fix depth buffer precision [\#1724](https://github.com/vispy/vispy/pull/1724) ([h3fang](https://github.com/h3fang))
- Volume visual has unset variable texture2D\_LUT [\#1712](https://github.com/vispy/vispy/pull/1712) ([liuyenting](https://github.com/liuyenting))
- Fix setuptools\_scm\_git\_archive usage [\#1707](https://github.com/vispy/vispy/pull/1707) ([djhoese](https://github.com/djhoese))
- Switch to setuptools\_scm for automatic version numbering [\#1706](https://github.com/vispy/vispy/pull/1706) ([djhoese](https://github.com/djhoese))
- Fix MarkersVisual.set\_data crash when pos is None [\#1703](https://github.com/vispy/vispy/pull/1703) ([proto3](https://github.com/proto3))
- Update azure PyPI token to match new standards [\#1698](https://github.com/vispy/vispy/pull/1698) ([djhoese](https://github.com/djhoese))
- Fix numpy futurewarning in dtype creation [\#1691](https://github.com/vispy/vispy/pull/1691) ([djhoese](https://github.com/djhoese))
- Improve PanZoom camera performance when non-+z direction is used [\#1682](https://github.com/vispy/vispy/pull/1682) ([os-gabe](https://github.com/os-gabe))

</details>

**Comment by djhoese** [comment]
I feel like I must be missing something with this tool. It is so slow and seems like it *always* parses every issue/PR. Is it always going to be like that?

Some of the basic command line flags seem to be not working as well. Here is my current command that I'm playing with:

```
github_changelog_generator -u vispy -p vispy --between-tags v0.6.1,HEAD --unreleased-only --no-issues-wo-labels --no-pr-wo-labels --no-filter-by-milestone -t b7e937d0dddbc6b394179bd2f619591a9d167bb1 --bug-labels "type: bug" --enhancement-labels "type: enhancement,type: feature" --exclude-labels "duplicate,question,invalid,wontfix,type: question" --enhancement-label "**Enhancements:**" 
```

Even with the `--no-pr-wo-labels` it still includes a "Merged pull requests" section for PRs that don't have any labels. Any ideas @larsoner?

**Comment by djhoese** [comment]
Also, I'm considering not including any issues in the release notes since any bugs should be fixed by some pull request.

**Comment by larsoner** [comment]
> Even with the --no-pr-wo-labels it still includes a "Merged pull requests" section for PRs that don't have any labels. Any ideas @larsoner?

I would just edit the list by hand afterward. I use it to get me 90% of the way where about a minute of manual editing will get me where I need to be to actually have the correct release notes. (I actually use it in conjunction with pandoc to get to RST as well.)

You could also try to fix the tool itself. In any case, I'm not too surprised it's broken, my experience is also that the command line switches are not consistently used properly.

**Comment by djhoese** [comment]
Ok I almost got everything to work tonight, but need to call it a night before going down the rabbit hole of making a release. I'll plan on releasing 0.6.2 tomorrow.

Turns out the major issues I was experiencing are fixed in the latest release of github_changelog_generator, but for some reason when I followed their install instructions the first time it gave me an older version. The other thing I had a problem with was the "Merged pull requests". I found out that this was including PRs that had labels but were not explicitly excluded or included. After adding the labels to be included/excluded and specifying a couple other options I get:

```
 CHANGELOG.md
# Release Notes

## [v0.6.2](https://github.com/vispy/vispy/tree/v0.6.2) (2019-11-03)

**Enhancements:**

- Switch to setuptools\_scm for automatic version numbering [\#1706](https://github.com/vispy/vispy/pull/1706) ([djhoese](https://github.com/djhoese))
- Improve PanZoom camera performance when non-+z direction is used [\#1682](https://github.com/vispy/vispy/pull/1682) ([os-gabe](https://github.com/os-gabe))

**Fixed bugs:**

- Fix Python 3.8 compatibility in Canvas 'keys' update [\#1730](https://github.com/vispy/vispy/pull/1730) ([GuillaumeFavelier](https://github.com/GuillaumeFavelier))
- Fix VolumeVisual modifying user provided data in-place [\#1728](https://github.com/vispy/vispy/pull/1728) ([tlambert03](https://github.com/tlambert03))
- Fix depth buffer precision [\#1724](https://github.com/vispy/vispy/pull/1724) ([h3fang](https://github.com/h3fang))
- Volume visual has unset variable texture2D\_LUT [\#1712](https://github.com/vispy/vispy/pull/1712) ([liuyenting](https://github.com/liuyenting))
- Fix MarkersVisual.set\_data crash when pos is None [\#1703](https://github.com/vispy/vispy/pull/1703) ([proto3](https://github.com/proto3))
- Fix numpy futurewarning in dtype creation [\#1691](https://github.com/vispy/vispy/pull/1691) ([djhoese](https://github.com/djhoese))
```

Now I just need to come up with reusable set of instructions to document how to do this in the future (including committing the options to a `.github_changelog_generator` config file). I figure I'll dump the previous release notes at the end of the newly generated ones. I'd also like to avoid duplicating the release notes in multiple spots so I'd like the website to point to the github CHANGELOG.md file.

**Comment by djhoese** [comment]
Ugh so close to a release. The tests passed but the wheels that were made were given a version of 0.6.3+abcdefg instead of the 0.6.2 they should have had. This makes me think the wheel building is causing some files to be modified which makes `setuptools_scm` think the package is modified from the tagged 0.6.2.

Have to head in to work. Will investigate there.

**Comment by djhoese** [comment]
Ok, update: Running `python setup.py bdist_wheel` generates the jupyter widget which updates the `js/package-lock.json` file. This change makes the git repository "dirty" and therefore doesn't keep the intended version. I think the smart and simple thing is to reset this file before trying to build the package.

I'm going to try to double check that this is the file being updated on azure and is causing the issue.

**Comment by djhoese** [comment]
Oops, this has been fixed for a while. Closing.
