### ISSUE TITLE
VolumeVisual.set_data method and copy=False may lead to unexpected behavior

### ISSUE THREAD

**Issue by tlambert03** [vispy/vispy#1727]
An issue recently arose in the napari repo (see napari/napari#575) in which calling the `VolumeVisual.set_data()` method was altering the input data and causing unexpected results (but only with float32 input data).  We eventually realized it was caused by line 477 below in the `set_data()` method, in which the data is converted to float32 with `copy=False`.

https://github.com/vispy/vispy/blob/8b61cd439076aa3f50ac5f6dacb4c0af8c1d0684/vispy/visuals/volume.py#L477-L483

I realize we can simply copy the data on our end before calling the `VolumeVisual.set_data()` method, but I'm wondering whether the default behavior shouldn't be to copy the volume before applying the clim normalizations, so as to avoid unexpectedly overwriting the input data)?  (it was particularly hard to find due to the fact that the memory address of the input volume is unchanged _only_ for float32 data)

**Comment by jni** [comment]
Just to add a +1 here. imho a visualisation library should never modify its input data.

Short term, changing to `copy=True` would be a good fix. Longer term, should it not be possible to do the clim adjustment in the shader? Apologies for the naive question as I know very little about shaders!

**Comment by djhoese** [comment]
Wow, what a bug. My initial feeling is that the user should be responsible for copying so we at least allow the fast no-copy version of the code. That is only coming from a performance point of view and not one concerned about user experience. As you pointed out, only **not** copying when it is float32 data is not very useful and is strange. I vote for an explicit copy but I'd like to hear the arguments from @larsoner and @kmuehlbauer too.

I don't have a lot of experience with the VolumeVisual but do with the ImageVisual which has similar logic. Looking at the source code now it looks like the ImageVisual starts with a out of place operation so it copies the data:

https://github.com/vispy/vispy/blob/61fcfe17c6eaa6cbb7657ba4ae9cfe07957ff85f/vispy/visuals/image.py#L406

@jni You are right that shaders could do this logic. The main issue is that OpenGL 2.0 (ES 2) do not support 32-bit float textures. This means that you end up getting something equivalent to an 8-bit integer in the GPU (even though they are represented as 0-1 floats in the GL shaders) and storing 32-bit or 64-bit floats in to an 8-bit float loses you a lot of precision. By doing the clim scaling in the CPU we can reduce the amount of lost precision/data. I think because vispy was originally written with this backwards and mobile compatibility as a main goal, it did not allow the user to do things that weren't compatible. In my own work I've made a custom version of the ImageVisual which does exactly as you propose, it takes the clims, gives them to the shader, and then stores the data on the GPU as a 32-bit float (iirc). The shader then does the scaling and gets the benefit of having all of the original data locally in the GPU. I would be open to the VolumeVisual and ImageVisual getting the functionality to declare their textures in a way to support this.

**Comment by jni** [comment]
@djhoese an explicit copy with the option of turning that off for performance would be good. Then the option in the keyword argument could have a fat warning that the data would me modified in-place.

Thank you for the background info. From long experience, indeed most choices make much more sense when framed in the historical context of the library!

**Comment by larsoner** [comment]
Agreed we should have a `copy=True` parameter, silently changing people's values (and doing so by default) is dangerous

**Comment by djhoese** [comment]
@tlambert03 or @jni Interested in making a pull request (for that sweet sweet hacktoberfest shirt)?

**Comment by tlambert03** [comment]
thanks for your help @djhoese!

**Comment by perlman** [comment]
> In my own work I've made a custom version of the ImageVisual which does exactly as you propose, it takes the clims, gives them to the shader, and then stores the data on the GPU as a 32-bit float (iirc). The shader then does the scaling and gets the benefit of having all of the original data locally in the GPU. I would be open to the VolumeVisual and ImageVisual getting the functionality to declare their textures in a way to support this.

I'll add a +1 to the chorus here. With @jni's encouraging, I have been playing around with different ways to handle label data in napari, where my thought is we should try to do (label,salt) -> color as a shader (similar to what neuroglancer is doing). An option to bypass array manipulation (and clim with it) would be great. (The second half, custom shader and texture, work fine as a subclass of BaseColormap.)
