### ISSUE TITLE
Slow import

### ISSUE THREAD

**Issue by cgohlke** [vispy/vispy#1779]
On my Windows workstation with >1200 of Python packages installed, `import vispy` takes about 3.4 seconds. 

98% of that time is spend at     
https://github.com/vispy/vispy/blob/ded293841c6438ab54af10c561f372155bb77edc/vispy/__init__.py#L26

On this system, more than half of `napari`'s import time is spent on determining the vispy version. 

Please consider not using `pkg_resources` during runtime.

Loosely related to https://github.com/napari/napari/pull/745

**Comment by royerloic** [comment]
Oh, wow, great catch!

**Comment by djhoese** [comment]
The reason pkg_resources is used is because we are using `setuptools_scm` to automatically determine the version number from the git history of the package. I figured this would be a performance hit, but I think we all (@kmuehlbauer @larsoner) decided it wouldn't be that bad and it is recommended ways of using setuptools_scm from their documentation. There is an option with setuptools_scm to write the version to a file (ex. `vispy/version.py`) but some maintainers were worried this would cause confusion or complications when new contributors were doing a dev installation and saw a new version.py file get created. After the last couple versions experience with setuptools_scm I'm starting to lean towards adding this version.py file the way I originally planned on doing it. I agree that this 3s import is just ridiculous.

I thought it would be good if you understood why `pkg_resources` was being used rather than assuming we were doing something just because we wanted to. This is the default way setuptools_scm works.

@kmuehlbauer @larsoner Feel free to chime in on concerns about using `vispy/version.py` (it is generated by setuptools_scm when you install the package from source).

**Comment by cgohlke** [comment]
To be fair, fixing this issue is not enough to speed up napari loading. There are other packages that are using `pkg_resources`: triangle, docutils, and sphinx.

**Comment by larsoner** [comment]
@cgohlke for `napari` is it reasonable to nest the `triangle`, `docutils`, and `sphinx` imports? Or at least make it so that the submodules that use them are only loaded on demand?

Then `vispy` would still be the bottleneck. 

> I'm starting to lean towards adding this version.py file the way I originally planned on doing it. I agree that this 3s import is just ridiculous.

Agreed this is too much and we should avoid it. Writing `version.py` seems better in light of this overhead. Better to let `vispy` devs doing editable installs go through some confusion rather than all end users suffer through 3 sec imports.

**Comment by kmuehlbauer** [comment]
@cgohlke Any idea, why `pkg_resources` needs that much time?

**Comment by larsoner** [comment]
For me it's only 0.2 sec to `time python -c "import pkg_resources"`. I'm going to guess it's because of the 1200+ packages installed on that system (see top comment), and `pkg_resources` doing some parsing of installed packages on import.

**Comment by djhoese** [comment]
@larsoner I think the better test would be to do the `get_distribution` call for `vispy`. I think pkg_resources is having trouble finding the metadata for the vispy package among all the installed packages. Once it finds it then it should be parsing the metadata and pulling out the version number.

**Comment by larsoner** [comment]
Ahh that would be better. 0.24 sec for `import vispy` for me, 0.20 for `python -c "import pkg_resources; pkg_resources.get_distribution('vispy')"`

**Comment by cgohlke** [comment]
> Any idea, why pkg_resources needs that much time?

On this system, `import pkg_resources` causes over 93,000 file system operations (CreateFile, CloseFile, QueryInformation...). 

> suffer through 3 sec imports

That is for a Python installation on a fast SSD with huge cache. Importing from a network drive takes in the order of 30 seconds.

**Comment by djhoese** [comment]
Code for `get_distribution` if anyone is interested: https://bitbucket.org/pypa/pkg_resources/src/33e56f318f5086158de8bb2827acb55db2dbc153/pkg_resources.py?fileviewer=file-view-default#pkg_resources.py-368

Not that we are going to convince any changes that haven't been considered on the setuptools side. I'll just have to switch to using the version.py static file method. @cgohlke If I get this implemented in a pull request would you be able to test it on your system with the 1200 packages?

**Comment by cgohlke** [comment]
> If I get this implemented in a pull request would you be able to test it on your system with the 1200 packages?

sure

**Comment by djhoese** [comment]
PR made #1780

**Comment by cgohlke** [comment]
Related to this issue: `import vispy.geometry.triangulation` is slow if the `triangle` package is installed.

https://github.com/drufat/triangle/blob/bcdd315d85eb20fcb962e28de6198387a1fd1b09/triangle/__init__.py#L1
