### ISSUE TITLE
custom 'draw_cube' in SceneCanvas

### ISSUE THREAD

**Issue by ucacaxm** [vispy/vispy#1809]
Hi,

I have a simple question from a beginner.
I would like to make a function 'draw_cube', or 'draw_mesh' with a good interactive camera for drawing procedurally several cubes or mesh in the on_draw function.

I tried with SceneCanvas by deriving the on_draw function without storing the cube in the scene graph (see the code bellow). An other way would be with app.Canvas but with a good interactive camera (better than arcball).

With the code bellow, the cube is drawed but it is not turned by the mouse.
How can I apply the view/camera matrix to any mesh (visuals) ?

Is there an example based on app.Canvas with a good interactive camera with mouse. 
I mean more complete than examples/basics/visuals/arcball.py with zoom, translation, etc.  An example including a simple but efficient class View/Camera in app.Canvas without the scene graph.

```
class MonCanvas(scene.SceneCanvas):
    def __init__(self):
        scene.SceneCanvas.__init__(self, keys='interactive')
        self.unfreeze()
        self.view = self.central_widget.add_view()
        self.view.camera = scene.cameras.ArcballCamera(parent=self.view.scene)
        self.cube = scene.visuals.Cube((.5, 1.0, 1.0), color=(0,1,1,1), edge_color='red')
        self.freeze()

    def on_draw(self, event):
        print("on_draw")
        super().on_draw(event)
	self.cube.draw()
```

Thank you very much,
Alex

**Comment by djhoese** [comment]
Thanks for posting the question. I've updated your code block to have three backticks (`) on the line before it and after it so it gets formatted properly by github.

I would not recommend implementing camera logic for the base `Canvas` class unless there is a limitation of the `SceneCanvas` that is stopping you from doing what you want to do. If you think this is the case let me know and we can figure out the best solution.

As for your example code using the `SceneCanvas`, is there a reason you don't want the cube on the scene graph? The `SceneCanvas` is set up to automatically redraw all child nodes when a redraw is triggered so there is no need to redefine `on_draw` if your visual is added to the scene graph. The camera system in vispy is only meant to work on the `SceneCanvas`. It does this by manipulating the transform object(s) associated with the view/canvas, but this only works if your visuals are children in the scene graph. The overall vertex coordinate transformation for a visual is a combination of all transforms along the scene graph (ex. visual's transform -> parent node's tranform -> ...-> canvas' transform -> buffer's transform -> GPU). In your case your visual is not part of this chain of transforms because it is not part of the scene graph so it is only using a limited set of these transforms.

**Comment by ucacaxm** [comment]
Thank you for your answer.

The reason why I am looking to do that is I have already all my data in my own data structure.
I just need to do
foreach my data:
    draw_cylinder or draw_cube or draw_sphere

I could setup all my data in the scene graph but let suppose I have 10000 spheres, that means the mesh of a sphere will be duplicated 10000 times in the graph ?


My other option was to start from the examples/basics/visuals/arcball.py and improve the camera interaction. But what I do not understand in this example is the 0.001 in the scale:
self.cube.transform.scale((100, 100, 0.001))
Where can I find the shader which is used in self.cube.draw() ?
Is there a mat4 projection, view, model in the shader as usual ?

Best,
Alexandre

**Comment by djhoese** [comment]
So technically the `Cube` visual is deprecated as far as the naming goes and the `Box` visual is the preferred way of creating this type of shape (not sure I agree with the Box over Cube decision that past me made...).

The Box as you've probably realized is made up of multiple smaller visuals (https://github.com/vispy/vispy/blob/master/vispy/visuals/box.py). So the shader code that gets run is of those individual objects (MeshVisuals). However, Visuals do not follow a projection/view/model vertex coordinate scheme like you might see in other GL situations. This is because of how the SceneCanvas' TransformSystem (the transforms I mentioned before) are implemented; as a series of GL function calls.

You are right that adding thousands of visuals to the scene graph would be terrible for performance, but it will also be bad if you create the Visuals with a regular Canvas or even as a series of separate GL programs (that's what a basic Visual is). Since each GL program is run serially by the GPU having more than 10 or 20 can give you noticeable performance/FPS issues. The best "solution" for this is to create on giant GL program (1 vertex shader, 1 fragment shader) that is able to draw all the shapes you want. This was one goal of the "collections" objects that you'll find in the vispy code, but these haven't been ported to work as Visuals yet. I'm hoping to get some funding by the end of this year where I would be able to work on this.

Probably not the answer you wanted. Sorry.

**Comment by queenish001** [comment]
@ucacaxm Is there any update on your query? Did you get the answer?

**Comment by djhoese** [comment]
Going to close this. Based on what I remember about this either a MeshVisual should be used or the new updated MarkersVisual which now supports sphere markers: https://github.com/vispy/vispy/pull/2209
