### ISSUE TITLE
meshio for i/o

### ISSUE THREAD

**Issue by nschloe** [vispy/vispy#1817]
Main author of [meshio](https://github.com/nschloe/meshio) here.

meshio can read a large number of formats which are applicable for vispy, I think it would be a good match for meshio.

**Comment by djhoese** [comment]
Great! Glad to have you here. Do you have specific interfaces in mind? How do you see VisPy users using meshio?

Right now we have a couple utility functions that use other libraries like:

https://github.com/vispy/vispy/blob/master/vispy/io/mesh.py

Which uses some functions created for reading STL files which was copied from the trimesh project:

https://github.com/vispy/vispy/blob/master/vispy/io/stl.py

There are also some wavefront readers and writers:

https://github.com/vispy/vispy/blob/master/vispy/io/wavefront.py

**Comment by nschloe** [comment]
> How do you see VisPy users using meshio?

Well, how do users use `load_stl` right now?

(meshio supports both stl and wavefront files, plus a couple of dozen more.)

**Comment by djhoese** [comment]
@larsoner or @kmuehlbauer might know more, otherwise there may be existing pull requests or issues that have users who are more familiar with this. I don't really use meshes and am not familiar with the various ways (common or not) that they are described. I believe we read things this way because it is directly passed to our MeshVisual object. I wouldn't be surprised if this is limited to triangles. The texture coordinates might be flexible, but it really depends on what the [MeshVisual](https://github.com/vispy/vispy/blob/master/vispy/visuals/mesh.py#L150) and its lower-level object [MeshData](https://github.com/vispy/vispy/blob/master/vispy/geometry/meshdata.py#L24) can handle.

Note: There are some very important changes being worked on in open PRs (https://github.com/vispy/vispy/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+mesh). They are missing a few changes, fixes, and tests before they can be merged but they may make some of this more possible.

**Comment by kmuehlbauer** [comment]
@nschloe There were quite some attempts to improve on mesh loading, afair. I'm too not involved too much into meshes in general. But it would be nice, if meshio could be used to serve MishVisual/MeshData the needed values.

As @djhoese already mentioned, there are open PR which change Mesh Handling within vispy, ping @asnt.

**Comment by asnt** [comment]
@nschloe Please have a look at #1665 which mentions some ides/wishes for improvement on loading meshes.

I think that a loading mechanism that returns all the mesh info with a predictable and systematic data structure would be welcome. It seems meshio can provide some of that with `mesh.points`, `mesh.cells`... but I don't see support for other attribute arrays and data (texture images, texture coordinates...) in the [OBJ loader](https://github.com/nschloe/meshio/blob/3c12f1598e6a01ef26f9b12c94ebfa358d4c547f/meshio/obj/_obj.py#L22), for example. Did I miss it or is it planned? Is it implemented for other mesh formats maybe?

> One difficulty I do see is the fact that your reader always returns outward normals and "texture coordinates". Is this a strict requirement?

The current loaders return a tuple `(vertices, faces, normals, texcoords)`. This is restrictive to specific cases. A more flexible structure would be welcome.

> Also, do you need triangles or can you handle other shapes are well?

I am not sure but I think most of vispy assumes triangles as primitives. Being able to load quads would open the door to variations, though. (At least, we would be able to display quads as triangles.)

**Comment by nschloe** [comment]
>  but I don't see support for other attribute arrays and data (texture images, texture coordinates...) 

There is `mesh.cell_data`, `mesh.point_data` etc. which host such things. It is possible that some readers haven't implemented support for this yet (e.g., obj files), but this would definitely be something we want are are going to have in meshio.

> I am not sure but I think most of vispy assumes triangles as primitives.

That's fair enough. meshio supports many more cell types (3D too, like tetrahedra, pyramids etc.), but it's easy to just single out the triangles in a file.

**Comment by djhoese** [comment]
I think VisPy's preference for triangles is that it tries to keep OpenGL 2.x and OpenGL ES support. I *think* older GPUs had a limitation on triangles only and quads were just made up of two triangles. As @asnt points out we could convert internally if needed.

**Comment by nschloe** [comment]
Is it a problem that meshio supports Python 3.5+ only? (Not Python 2.7.)

**Comment by djhoese** [comment]
The next release of vispy will be likely be 3.6+ (definitely not 2.7).
