### ISSUE TITLE
Colormaps clamped to 0.0-1.0 range?

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [vispy/vispy#1845]
Before the colormap rewrite (vispy <= 0.5.3) that started using textures as color LUTs, colormaps could extend beyond the 0-1 range. That was very useful to visualize data outside the core range, especially with the viridis color map.

Looking at [colormap.py](https://github.com/vispy/vispy/blob/bfe96648fb50ec1eec56568aff93a302473a2e6f/vispy/color/colormap.py) it no longer seems to be possible to sample color maps outside the 0-1 range, as the control points are already clamped to 0 and 1. Is that correct?

**Comment by djhoese** [comment]
Are we specifically talking *only* about the control points? Or colors too?

Assuming just control points, what did you expect to be returned when sampling outside the 0-1 range? The color on that end of the range (first color if <0, last color if >1)? What do you get now?

**Comment by HENDRIX-ZT2** [comment]
With the old version my image would display colors outside the 0-1 range of the colormap.
See the dark purple - black regions in the spectrum in a screenshot running with the old vispy version:
![im](https://camo.githubusercontent.com/d43d5cfc4eb0213a4b91e712577f68734693f296/68747470733a2f2f692e696d6775722e636f6d2f696f6446354e422e6a7067)

With the current vispy version, my image only displays the clamped 0-1 range of the colormap. I can no longer get colors outside of what the colorbar shows for the 0-1 range. So the data that goes below 0 becomes a uniform lump of purple, when it was nicely detailed with the old colorbar code.
![grafik](https://user-images.githubusercontent.com/28632661/77544990-0f651580-6eaa-11ea-9329-4a04a48a39f3.png)

**Comment by djhoese** [comment]
Interesting. Any idea what colors show up if something is **above** 1 in the old code?

For my own reference here is the old code that did the "mixing" in the GPU:

https://github.com/vispy/vispy/blob/9dbe751dcdbaaa1d17d0a5885f15872b9b0741a8/vispy/color/colormap.py#L127-L140

This python function generates a ton of if/else if statements in shader language and blends the color between two colors of the colormap.

To clarify what's going on, in the old code above a value less than the first control point resulted in a blend (GLSL [`mix`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/mix.xhtml) function) between the first color and the second color using the input value as a weight. So if you had two colors and a weight of 0.5 you would get a 50/50 blend of the two colors. In your case, you are passing a negative value. This isn't a problem for `mix` necessarily but it does result in you getting colors outside of the colormap. Even though this is what you want, this is not how colormaps are supposed to work in my opinion. I feel VisPy should model this behavior off of matplotlib as much as possible and I don't think this behavior is possible there.

In the new code, we put all of the colors in a 1D texture and use the control point as a coordinate into that texture. Texture coordinates are from 0 to 1 and OpenGL allows you to customize what happens when a coordinate is outside this range. However, I don't think VisPy uses any of these and probably defaults to clamping. It is available as a [settable option](https://vispy.readthedocs.io/en/latest/gloo.glir.html#wrapping) in VisPy though. This page has some examples and descriptions of the options (under "Wrapping") but none of them match what we would need for your use case: https://open.gl/textures

The typical cases I've seen in matplotlib are to clamp the color to the edge of the colormap (like we are now) or mask these values and consider them invalid ("discard" them in GL terms). I'd be ok with this as an option to get something similar to what you have now where all `<0` pixels would be the color of your background (black most likely) but there would be no gradient/interpolation for these pixels. Another solution would be to expand the range (clim) for your ImageVisual to include the data you want shown on the display.

CC @tlambert03 who has been working on the ImageVisual alot and @kmuehlbauer who has been reviewing that work.

**Comment by HENDRIX-ZT2** [comment]
Data above 1 turns white, but the effect is not as obvious.

I tend to agree with your opinion that color maps should be clamped at the ends. The old unexpected behavior just happened to produce neat results in my case. The new behavior renders viridis as a color map with too little dynamic range for spectrogram data. So I think I'll have to add a perceptually uniform color map that goes all the way from black to white.

**Comment by djhoese** [comment]
> The new behavior renders viridis as a color map with too little dynamic range for spectrogram data. 

It does? The previous version of VisPy didn't even use every data point of the viridis colormap (every 4th point I think). The new one includes all the colors.

**Comment by kmuehlbauer** [comment]
@HENDRIX-ZT2 Could you please provide a minimal code example which shows this behaviour. This will help us to understand the issue better.

**Comment by HENDRIX-ZT2** [comment]
> 
> 
> > The new behavior renders viridis as a color map with too little dynamic range for spectrogram data.
> 
> It does? The previous version of VisPy didn't even use every data point of the viridis colormap (every 4th point I think). The new one includes all the colors.

Sure, viridis is now sampled more densely but as it is now clamped to 0-1 and no longer extends into white or black at either end, it sort of lacks the punch one expects from other color maps commonly used with spectrograms for audio editing.

Anyway I solved my usability problem by loading [external color maps](https://bids.github.io/colormap/) (inferno, magenta) that have a larger dynamic range. Might be worthwile to include them with vispy, since that was the source of viridis as well. IIRC I read that this was planned after the color map rewrite with texture LUTs.

**Comment by kmuehlbauer** [comment]
> Anyway I solved my usability problem by loading [external color maps](https://bids.github.io/colormap/) (inferno, magenta) that have a larger dynamic range. Might be worthwile to include them with vispy, since that was the source of viridis as well. IIRC I read that this was planned after the color map rewrite with texture LUTs.

Glad you found a solution to your specific problem. Anyway pull request to add the mentioned colormaps to vispy are very much appreciated.

**Comment by djhoese** [comment]
> Anyway I solved my usability problem by loading external color maps (inferno, magenta) that have a larger dynamic range. Might be worthwile to include them with vispy, since that was the source of viridis as well. IIRC I read that this was planned after the color map rewrite with texture LUTs.

I've always loved that presentation. Especially since they did such a good job trying to dumb down the concepts for people who don't know color theory (I don't). I'm glad you found a solution and as Kai said, a pull request to add these other colormaps would be greatly appreciated (and hopefully not too difficult).

I'm still confused by your point about dynamic range. Are you saying perceptually the inferno/magma colormaps do a better job of displaying the high dynamic range of your spectrograms even if all three (inferno/magma/viridis) are clipped in VisPy? And to clarify on the "extends into white or black" that you mentioned, they were *not* going to white and black, they were being interpolated (extrapolated?) beyond the last two colors of the colormap on either end. I suppose if you go far enough in either direction you'll get to black and white.

**Comment by queenish001** [comment]
@HENDRIX-ZT2 Is your query resolved?

**Comment by HENDRIX-ZT2** [comment]
Yup.
