### ISSUE TITLE
Tests against/ wheels for python3.8

### ISSUE THREAD

**Issue by clbarnes** [vispy/vispy#1851]
Would it be possible to get CI doing both of these? Python 3.8's been out for 6 months now.

**Comment by djhoese** [comment]
The builds are ready in Azure to build python 3.8 wheels, we just haven't made a release since those changes. I don't have a timeline for the next release, but we're getting to the point that we need to do it. With everything going on and the way my work is going I only have time to work on VisPy in my free time which is very little.

There are a few PRs that I still want to merge for the next release. We will make a new release after that as soon as possible.

**Comment by clbarnes** [comment]
Great, thank you!

**Comment by djhoese** [comment]
VisPy 0.6.5 has been released with a python 3.8 wheel. This should now be fixed. Thanks for making this issue.
