### ISSUE TITLE
Custom Camera for SceneCanvas

### ISSUE THREAD

**Issue by wgnu6** [vispy/vispy#1873]
In Scene, how would I implement a turntable with WASD as the key events for rotation instead of mouse movements? I want to reserve mouse events for other stuff.

**Comment by djhoese** [comment]
1. Subclass the TurntableCamera class: https://github.com/vispy/vispy/blob/master/vispy/scene/cameras/turntable.py#L12
2. Override these two methods so they don't do anything with mouse events but instead do stuff with key press events:

   https://github.com/vispy/vispy/blob/b5f6228c7c4ec734206e9556033f5c3e7941616c/vispy/scene/cameras/base_camera.py#L118-L139

3. Copy the functionality from the existing "viewbox_mouse_event" method: https://github.com/vispy/vispy/blob/master/vispy/scene/cameras/perspective.py#L198. So it operates on the key press events instead of mouse move events. Some of this may be difficult because this method uses the base class's methods to handle some of the movement behavior. It may be easiest to make a fake MouseEvent (or whatever it is called) and pass that to the base classes to methods like is done here: https://github.com/vispy/vispy/blob/master/vispy/scene/cameras/perspective.py#L58

**Comment by queenish001** [comment]
@wgnu6 Is this issue resolved now?

**Comment by djhoese** [comment]
It has been over a year with no response so I'll close this. If you are still working on this then feel free to comment and we can reopen it and continue discussion.
