### ISSUE TITLE
How to set new image data?

### ISSUE THREAD

**Issue by witignite** [vispy/vispy#1936]
I am trying to iterate through images in a folder and show each on vispy, one at a time. What I am trying to achieve is: when pressing some key, the app would read the next image and show in on the canvas. What I did in is, when pressing some key, execute the following code:
```python
file_index = file_index  + 1
img = cv2.imread(file_list[file_index])  # Read next image
view.add(img)                            # 'view' = ViewBox returned from canvas.central_widget.add_view(...)
```
But vispy doesn't seem to show the newly read image.

Code:
```python
import os

import cv2
import vispy

class Visualizer():
    def __init__(self, dirpath):
        self.canvas = SceneCanvas(keys='interactive', 
                                  show=True, 
                                  size=(1600,900))
        self.canvas.events.key_press.connect(self._key_press)

        self.view = self.canvas.central_widget.add_view(
                        camera=vispy.scene.PanZoomCamera(
                            rect=(0, 0, 1, 1),
                            aspect=1,
                            flip=(False, True, False))
                    )
        
        # Initialize file list here
        ...
        ...
        # Show first image (This works fine; but the next calls do not.)
        self._update_step()

    def _update_step(self):
        # Read next image
        img = cv2.imread(...)
        
        # Trying to set new image here, but vispy doesn't
        # seem to show the newly read image
        self.view.add(visuals.Image(img, parent=self.view.scene))
        self.view.camera.set_range()
    
    def _key_press(self, event):
        if event.key == 'D':
            self._update_step()
    
    def run(self):
        self.canvas.app.run()

if __name__ == "__main__":
    vis = Visualizer(dirpath)
    vis.run()
```

**Comment by djhoese** [comment]
What does it show instead?

I think the best thing, both for performance and for just plain functioning, to do would be to create a single `Image` instance in your `__init__` and then in your `_update_step` do `self.my_img.set_data(img)` and then `self.canvas.update()`. This update may be the main thing you are missing right now, but I would have though `set_range` called that internally. There is also a chance that if the image you are seeing doesn't change, it is likely because the first image you show is "on top" of the new ones. You never actually delete the old Image instances or detach them from the SceneCanvas so they are always living in memory (and on the GPU).

Hope this helps a little. Let me know if I can help further.

**Comment by witignite** [comment]
@djhoese Thank you for your explanation! That solves my issue exactly. The problem seems to be that `self.view.add(...)` just adds an image; it doesn't reset or clear the value, just as what you said.
