### ISSUE TITLE
Use of scene.Axis breaks correct 3D occlusion for Ellipse and other visuals 

### ISSUE THREAD

**Issue by mathijsromans** [vispy/vispy#1952]
I have noticed that 3D occlusion was not working correctly from my program (farther disc is occluding a closer disc). While investigating, I discovered that this only happens when I add a scene.Axis to the scene. The following program reproduces this problem:

```
import vispy
from vispy import scene

canvas = scene.SceneCanvas(keys='interactive', bgcolor='black')
view = canvas.central_widget.add_view()
view.camera = scene.TurntableCamera()
scene.Axis(pos=[[0, 0], [1, 0]], parent=view.scene)
ell1 = scene.visuals.Ellipse(center=(0, 0), color='red', parent=view.scene)
ell2 = scene.visuals.Ellipse(center=(0, 0), color='yellow', parent=view.scene)
ell2.transform = scene.transforms.MatrixTransform()
ell2.transform.translate((0,0,1))

canvas.show()
vispy.app.run()
```

When running the program and rotating the scene with the mouse, putting the yellow disc behind the red disc, the problem becomes visible. See the attached screenshot.
![Screenshot_20201115_232421](https://user-images.githubusercontent.com/325305/99198554-c0058980-2799-11eb-8d76-2a9b27485df8.png)

**Comment by djhoese** [comment]
The issue seems to be the GL settings of the TextVisual here:

https://github.com/vispy/vispy/blob/54439bc83f88f78e45edfa1ce96c17adafbb078b/vispy/visuals/text/text.py#L432-L433

The TextVisual is part of the AxisVisual and includes `depth_test=False`. If we set the `depth_test` to `True` then I don't see this issue. So the "simple" possibly problematic solution would be call `set_gl_state` after you create the Axis, like this:

```
import vispy
from vispy import scene

canvas = scene.SceneCanvas(keys='interactive', bgcolor='black')
view = canvas.central_widget.add_view()
view.camera = scene.TurntableCamera()
ax = scene.visuals.Axis(pos=[[0, 0], [1, 0]], parent=view.scene)
ell1 = scene.visuals.Ellipse(center=(0, 0), color='red', parent=view.scene)
ell2 = scene.visuals.Ellipse(center=(0, 0), color='yellow', parent=view.scene)
ell2.transform = scene.transforms.MatrixTransform()
ell2.transform.translate((0,0,1))
ax.set_gl_state(depth_test=True)

canvas.show()
vispy.app.run()
```

The problem will be when you run in to cases where you want depth testing off for the TextVisual...but I'm not sure when that is.

**Comment by djhoese** [comment]
Some more detail: Setting the GL state is typically something you do for an entire drawing operation and you only do it once. That means that if one Visual needs depth testing off and one needs it on, vispy will only use the last one that is created for performance reasons. Otherwise you would have to modify the _prepare_draw (or draw) method of each Visual to have them set the gl state before each visual is drawn. This could potentially be very slow which is why VisPy doesn't do it by default design.

**Comment by mathijsromans** [comment]
Thank you, that indeed works. It is a bit unfortunate that this doesn't work 'out of the box', since it has surprising results, affecting other visuals. It took me a while before I figured out it was the Axis that caused the problem!

**Comment by djhoese** [comment]
Yes, it is unfortunate, but without the depth test setting the way it is the TextVisual would not behave as most people expect in other cases (I assume).

Closing now. We can reopen if needed.
