### ISSUE TITLE
How to set framerate/FPS?

### ISSUE THREAD

**Issue by desteemy** [vispy/vispy#1955]
I want to change draw framerate in application. Two reasons of doing it are measure performance and save resources. What function should I use?

Let's use example from https://github.com/vispy/vispy/blob/master/examples/demo/gloo/high_frequency.py
And add two lines to it to measure frame rate:
line 90 after self._timer was created
```
    self.measure_fps()
```
line 117 last function in class Canvas (In this example we can omit that, but other application may still show FPS after closing the window)
```
    def on_close(self, event):
        self.measure_fps(callback=False)
        self._timer.stop()
```

Test it. So now it runs on ~29 FPS.

The only option I have found in documentation is to set timer interval [vispy.app.Timer](https://vispy.org/app.html#vispy.app.Timer). So lets try it editing line 88
```
-         self._timer = app.Timer('auto', connect=self.on_timer, start=True)
+         self._timer = app.Timer(interval=1, connect=self.on_timer, start=True)
```
 and when setting it to interval=1 it works as intended resulting in 1 FPS. But setting it on 0.033334 should give 30FPS- I was getting 16-26.  Setting it on very low like 0.0001 or 0 gives ~22 FPS.

My standard display refresh rate is 60Hz.

**Comment by djhoese** [comment]
This all depends on what is being drawn and how efficiently VisPy can tell your GPU to draw it. In general, VisPy will show best performance when you limit the number of Visuals/Programs in your Canvas. VisPy is not currently optimized to do anything inter-Visual (ex. "oh they are trying to draw 50 SphereVisuals we can be smart about that by doing X, Y, Z").

As far as I know setting the interval on the timer is the best way to control FPS, but since drawing speed depends on the number of Visuals and the complexity of those Visuals it isn't a static "draw things so we achieve X frames per second". As for why you see such a wide range of FPS with your different values, I'm not sure. I would expect anything faster than ~29 FPS (what you achieved with auto, which is as fast as Qt can do it) would max out at ~29 FPS, but I also don't have a ton of experience trying to measure FPS with VisPy.

@larsoner @kmuehlbauer any other advice?

**Comment by larsoner** [comment]
Nope, sounds reasonably well covered to me
