### ISSUE TITLE
Getting sys_info() before creating QApplication causes RuntimeError

### ISSUE THREAD

**Issue by Kusefiru** [vispy/vispy#1960]
Hi,

I am developing a Qt app that embeds Vispy canvases.
I want to print system information, be it for Python in general or vispy at the start of my program.

However, calling `vispy.sys_info()` before creating the app causes the following issue :
`RuntimeError: Please destroy the QApplication singleton before creating a new QApplication instance.`

I assume this is due to this function creating a QApplication and not deleting it. It is possible to bypass this issue by calling `vispy.sys_info()` after the creation of my QApplication, but this isn't exactly what I want.

Here is a reproducible example : 
```python
from PySide2.QtWidgets import QApplication, QMainWindow
import vispy.plot as vp
import vispy

# Crashes here
print(vispy.sys_info())

app = QApplication([])

# No crash if done here instead
# print(vispy.sys_info())

win = QMainWindow()
fig = vp.Fig()
win.setCentralWidget(fig.native)
win.show()
app.exec_()
```

For information, I am using : 
- PySide2 : 5.15.1
- Vispy : 0.6.5

**Comment by djhoese** [comment]
Could you explain why you can't have the sys_info after the QApplication is created?

`sys_info` needs to create a `QApplication` object in order to access a valid OpenGL context. Without it it can't provide the OpenGL information shown in `sys_info`'s output.

Normally, VisPy applications are executed from a vispy Application object. Something like:

```
app = vispy.use('pyqt5')
...
app.run()
```

where `app` is now a vispy Application object and `.run()` would replace your `app.exec_()`. In these cases, vispy will reuse any QApplication that was created earlier that Qt knows about:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/app/backends/_qt.py#L282-L291

Alternatively, if you needed access to the QApplication that VisPy is using you could do `app.native` when using the VisPy application where `.native` is the QApplication underneath.

**Comment by Kusefiru** [comment]
Your explanation is mostly what I understood from browsing the files.

I am logging the system informations for multiple libraries before creating and executing the app, in order to check their versions, and eventually have this data available in case something goes wrong during the initialization.

Having access to Vispy's `sys_info` later on means that I need to either do all this logging process after the main initialization part of my software, or do it in two parts, which I'm not a big fan of.

I understand that it would be a smaller change on my side rather than changing Vispy to get `sys_info` working as I wish though.

**Comment by djhoese** [comment]
If you aren't customizing the `QApplication` (passing additional arguments to it) then you can do:

```
app = vispy.use('pyqt5')
qapp = app.native
app.run()
```

Later on. The other important part here is that if you don't create a vispy app before `sys_info` then it will choose the best/default backend in order to get a working context. You are using Qt so this shouldn't be a problem as that is currently VisPy's first preferred backend, but you run the risk of accidentally loading vispy with the wrong backend.

> I understand that it would be a smaller change on my side rather than changing Vispy to get sys_info working as I wish though.

How would you change `sys_info` to make it work better for you? There is nothing wrong with `sys_info` or the way it is creating the application, you just need to reuse the application it creates. *If* you need to customize the QApplication then it needs to be created before `sys_info`. If you only need the library and system information and *not* the GL information that VisPy prints out, then you should just do that yourself. If however you need the GL information there is no other easy way than letting VisPy create an application/context and accessing that information.

**Comment by kmuehlbauer** [comment]
@Kusefiru Did the answer help? How did you finally solve the issue? It would be interesting to know.

**Comment by Kusefiru** [comment]
Yes, I followed the answer, this can be closed.
