### ISSUE TITLE
Best way to save large video

### ISSUE THREAD

**Issue by lj9707** [vispy/vispy#1961]
Hi,

I'm trying to do a visualization project and I'm testing different packages. I'm testing vispy by creating a lot of 3D lines (want to try 10k,100k,1mil) and changing colors at each update and turning it into an animation.  From my testing it seems like vispy can handle those lines (even 1mil it's pretty fast). However when I try to save the animation into a video format (.mp4) it's extremely slow. When I try 10k it tells me it will take 12 hours and 1 mil will take 700 hours. I'm currently using moviepy with vispy to save videos but I'm open to other ways to do this. **My question is: is there any way to save the animation to any kind of video format in a fast and reliable way (or is it even possible with my hardware setup)?**
My machine info:
Windows 10
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
32 GB RAM
NVIDIA GeForce RTX 2080 Ti
I hope my hardware is not the bottleneck. I also noticed that when I run animation.write_videofile() both my CPU and GPU have low usage (CPU 20% and GPU 15% according to Task Manager). 
I'm very new to large scale video/visualization so any suggestions will be appreciated! Thank you!
Here's some code for demo purpose, all_lines is just a list of 3D coordinates:

EDIT: code formatting
```
class Canvas(vispy.scene.SceneCanvas):  
    def __init__(self):  
        vispy.scene.SceneCanvas.__init__(self, size=(400, 400), show=False)  
        self.unfreeze()  
        self.traces = dict()  
        for i, pts in enumerate(all_lines):  
            self.traces[i] = visuals.LinePlot(pts, (1,0,0,1), parent=self.scene)  
            self.traces[i].events.update.connect(lambda evt: self.update)  

win = Canvas()  
view = win.central_widget.add_view()  

def update(ev):  
    win.on_draw(None)  
    for i, pts in enumerate(all_lines):  
        color = (1,0,0,np.random.random(1))  
        win.traces[i].set_data(color=color)  
    return _screenshot((0,0,win.size[0],win.size[1]))[:,:,:3]  

animation = VideoClip(update,duration=60)  
animation.write_videofile('test_line.mp4', threads = 6, fps=20)
```
`

**Comment by djhoese** [comment]
What says it will take 12 hours?

Do you need to use the LinePlot visual or would the basic `Line` work for you (do you need the markers/dots or not)? Just curious as anything you don't need to draw will help performance.

Tips and concerns:

1. You shouldn't need the `self.traces[i].events.update.connect(lambda evt: self.update)`. The `set_data` method of `LinePlot` should call that automatically. If not, I would call `win.update()` just before calling `_screenshot`.
2. If at all possible, you should create one single `LinePlot` or `Line` visual and provide the data in the way it is needed to get displayed properly. This will be 100x faster than creating separate visuals as VisPy/OpenGL has to draw each of these serially.

I'm curious how you were able to test that the performance for so many lines performed well but then when doing this animation it didn't work. If `all_lines` is the thing that is 10k/10M in length, I'm surprised you even got anything to draw. Normally VisPy visualizations consist of less than 10 Visuals, maybe 20. Obviously a good GPU could do more, but it is usually better to find a way to combine Visuals (ex. tell `Line` to draw multiple line segments instead of 1).

**Comment by lj9707** [comment]
Thank you so much for the response!
> What says it will take 12 hours?
> I'm currently using `from moviepy.editor import VideoClip` with vispy. `write_videofile()` says it will take 12 hours.

> Do you need to use the LinePlot visual or would the basic `Line` work for you (do you need the markers/dots or not)? Just curious as anything you don't need to draw will help performance.
>  I have some plans for the markers that's why I chose LinePlot. I tried to switch to Line and it decreases from 12 hours to 10.5 hours

> Tips and concerns:
> 1. You shouldn't need the `self.traces[i].events.update.connect(lambda evt: self.update)`. The `set_data` method of `LinePlot` should call that automatically. If not, I would call `win.update()` just before calling `_screenshot`.
This does not seem to help with the long run time. Since it should call it automatically I removed this.

> 2. If at all possible, you should create one single `LinePlot` or `Line` visual and provide the data in the way it is needed to get displayed properly. This will be 100x faster than creating separate visuals as VisPy/OpenGL has to draw each of these serially.
> In my example does that mean give 10k points to 1 LinePlot visual instead of creating 1 LinePlot visual for every pair? I need to change the color of each line differently. The coordinates are fixed. Will I be able to do this? It would be great if there're any examples I can look at.

> I'm curious how you were able to test that the performance for so many lines performed well but then when doing this animation it didn't work. If `all_lines` is the thing that is 10k/10M in length, I'm surprised you even got anything to draw. Normally VisPy visualizations consist of less than 10 Visuals, maybe 20. Obviously a good GPU could do more, but it is usually better to find a way to combine Visuals (ex. tell `Line` to draw multiple line segments instead of 1).
I'm very new to this and have no clue to be honest. Are you suggesting that what I'm trying to do seems impossible for my hardware setup? What I was trying to say was `animation = VideoClip(update,duration=60) ` returns very fast even with 1mil points. `animation.write_videofile('test_line.mp4', threads = 6, fps=20)` is the line that took forever. I actually just let it run with 10k points and it did return a video doing what I expected to do. 

I'm wondering if I'm doing something wrong because it seems like my CPU and GPU are not fully utilized. Is it even possible to use GPU to save videos? Even if it's not I would expect CPU to have a higher % Utilization. Perhaps moviepy is not the best option? What is the standard way in vispy to save large videos?

**Comment by djhoese** [comment]
> This does not seem to help with the long run time. Since it should call it automatically I removed this.

No it wasn't really meant to help the long run time, but just in case it would be best to remove it. It may be causing duplicate/redundant draws.

> In my example does that mean give 10k points to 1 LinePlot visual instead of creating 1 LinePlot visual for every pair? I need to change the color of each line differently. The coordinates are fixed. Will I be able to do this? It would be great if there're any examples I can look at.

Yes, but how it is done depends on your use case. See the `pos` and `color` kwargs to Line:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/visuals/line/line.py#L58-L63

And also the `connect` kwarg:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/visuals/line/line.py#L67-L75

Colors can be specified per vertex and the GPU will interpolate between the two colors when it draws the line. If you need to draw a lot of "segments" then you could set that as your `connect` parameter and then the vertex pairs for `pos`. In this case you may end up with duplicate colors (a numpy array where every two elements are the same color), but that is only wasted space, the GPU will draw this *MUCH* faster than making separate line segment visuals.

The `VideoClip` line returns immediately because it hasn't actually done any computation yet. The `write_videofile` is the one that actually starts drawing.

I wouldn't worry about your hardware. Doing 20 FPS for only lines would run on any modern computer (in my opinion) if done in the way I described above (as few Visuals as possible). As for using a GPU to save videos: it isn't actually using the GPU to save the video, you are drawing the frames on the GPU then transferring the frames to the CPU which are then saved to disk. As far as I know there is no library that would do that directly from the GPU and for your use case it isn't worth it. You are doing 60 seconds of 20 FPS. That should not be a problem. For utilization, you are only using 6 threads so if you have a 16+ core system that isn't going to be a high CPU percentage. Plus communicating with the GPU is technically single threaded. The multiple threads when saving the video file is probably only for the MP4 encoding, nothing related to the GPU or vispy.

moviepy/VideoClip is likely not the problem here. It is how many Visuals you are creating. The GPU has to draw LinePlot 1, then LinePlot 2, then 3, then 4, ...serially. So you can't even get to the next frame until the GPU has drawn 10k/10M Visuals. That's the bottleneck here.

Side note: When I've done this in the past I've used imageio/imageio-ffmpeg, but VideoClip is probably fine.

**Comment by lj9707** [comment]
Thank you so much for the detailed explanation!  I will try the 1 Visual way.

**Comment by almarklein** [comment]
Closing this since it looks like the question has been answered.

Just wanted to add that you could consider using [imageio-ffmpeg](https://github.com/imageio/imageio-ffmpeg), which allows you to stream the frames to the video file. Moviepy uses imageio-ffmpeg under the hood, but I'm not sure whether it can stream?
