### ISSUE TITLE
Problems while trying to get data from a not drawn isosurface

### ISSUE THREAD

**Issue by benoittachet** [vispy/vispy#1966]
Hi,

I want to create an isosurface that only has its edges displayed. To do that, here is what I want to do :

- Create my isosurface
- Retrieve its vertices and edges
- disable the isosurface's display
- Create a new mesh with the given vertices and edges
- display this new mesh

However, I have 2 problems with that runtime sequence :

When I create my figure, it is displayed, but the vertices and edges cannot be obtained before the next frame (I don't know why). I have to wait for my next update loop to see it.
I can override this problem with the function mesh.draw(), but calling this one totally disables the display, leaving only a black window.

So, I have two ways to run for now, and none is correct to me : Either I display the data with incorrect values (shifted by a given period), or I get the correct values, but I cannot display anything.

Another problem I have is about disabling the Isosurface data : Because of the update, I have to wait for one update() to be able to retrieve it. My problem is that the display is still correct, at the correct time, so I have an edge mesh and an isosurface overlapping on display. I sure can disable the mesh display by setting its parent to None, but if I do this, I cannot retrieve its vertices and edges data anymore at the next frame (got a NoneType return).

In the VispyEdgeDisplayExample1.py file, I set the data, and display it on 2 frames : The first one is the whole isosurface, and the second, its skeleton (this one works, it's just to show how it's done). (There are a few unused elements in the code, 

In the VispyEdgeDisplayExample2.py, I try to load some data and display the edges I can retrieve directly. I immediately get a "Program linking error" when running it :

```
RuntimeError: Program linking error:
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7fb61fd51588>> for DrawEvent
```

In the VispyEdgeDisplayExample3.py, I get back on a 2-frames loop, one to display the previous edge data, and one to load the actual isosurface. These two actions are both done on a given update, to display an edge set at each frame. This example also runs correctly.

Finally, in the VispyEdgeDisplayExample4.py, I do the same thing than in the third example, but I disable the isosurface's display.
Now, I cannot display the correct data, because the vertices and edges seems not to be updated anymore.

All 4 scripts are downloadable here :
[vispyTestData.zip](https://github.com/vispy/vispy/files/5714435/vispyTestData.zip)

**Comment by djhoese** [comment]
It sounds like you could really benefit from https://github.com/vispy/vispy/pull/1689

In the mean time, since I haven't merged that PR quite yet and will be too busy until at least mid-January to deal with it, let's see if we can come up with something with what is available now? You talk about your issue with not being able to get the isosurface edges because you have to draw it, but if you look at the source code the function that actual generates that information is outside the IsosurfaceVisual:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/visuals/isosurface.py#L100-L101

imported as:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/visuals/isosurface.py#L8

And the MeshData object that generates those coordinates/edges is also a separate piece:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/visuals/mesh.py#L248-L251

Maybe it would be worth it to subclass the MeshVisual or subclass the Isosurface and change what it draws? The MeshVisual's `set_data` can take a `meshdata` kwarg directly too but maybe that won't help here. So in your Isosurface subclass you could compute/create your own MeshData object and pass the necessary vertices/edges to the `.set_data` method.

**Comment by benoittachet** [comment]
I'm not sure to understand everything, but here are a few points (tell me if I misunderstood something):

In my sample code, I'm not using the cache values, I'm retrieving data directly from isosurface's mesh_data (attribute inherited from MeshVisual class)

If I understand well, these ones can be retrieved from an isosurface() call ? If that's so, that may be useful. I'll try this, then.

**Comment by benoittachet** [comment]
It looks like the MeshVisual's solution works well, and without any frame delay. Thanks !

I'll keep an eye on the mentioned pull request, it may be useful later to simplify my code.

**Comment by djhoese** [comment]
Thanks for looking into it. Is this OK to close?

And yes, basically you weren't doing something I would normally recommend; drawing a visual just to extract information from it. It is better to figure out how that Visual is calculation that information and duplicate it in your own Visual (or subclass). Sounds like you got things working.

**Comment by benoittachet** [comment]
Yeah, we can close that one. Thank you !
