### ISSUE TITLE
What are the primitives for graceful shutdown/multithreading?

### ISSUE THREAD

**Issue by freckletonj** [vispy/vispy#1994]
It'd be nice to have some documentation on this. 

In order to have more control over the process, I tried to launch it concurrently, but it can't run outside the main thread? It looks like it's because the it needs to run on the main thread to communicate with the GLIR? https://github.com/vispy/vispy/issues/632

I would expect this to work:

```python
from vispy import app, scene, plot
import numpy as np
import multiprocessing as mp
def f():
    fig = plot.Fig()
    x = np.linspace(-10, 10, 1000)
    y = x ** 2
    line = fig[0, 0].plot((x, y))
    fig.show()
p = mp.Process(target=f)
p.start()
```

But since that doesn't work, how can I inspect if the app is up/shutdown properly? And how can I ensure this? When I'm working in the repl, I frequently get segfaults, and weird errors. I've dug through the sourcecode a bit, but alas, this evades me.

**Comment by djhoese** [comment]
https://vispy.org/faq.html#is-vispy-multi-threaded-or-thread-safe

**Comment by djhoese** [comment]
If you are getting a specific error, let me know. As the above FAQ answer talks about it is likely not something specific to VisPy that is causing issues but rather the GUI backend framework (maybe OpenGL).

**Comment by freckletonj** [comment]
Thanks for the pointer! I'll close this for now until I've read up a lil more.

**Comment by djhoese** [comment]
Great. If you want more help let me know. I'm curious what you're attempting to do.

**Comment by freckletonj** [comment]
@djhoese Thanks for your help! Sure, I can explain:

For exploratory work, I like staying in the repl within emacs, which would be benefited if I could control the startup/shutdown of the whole vispy system. For instance, I'll send a whole buffer to the interpreter, interact with it via the repl since the app shouldn't be blocking, and then KeyboardInterrupt when I'm done, but want to keep the repl running. I register cleanup fns via `signal`. 

So I tried shoving all of vispy into its own Process, but, it doesn't work.

An example of a recent bug  leading me to want more concurrent control: Data was coming in at 30Hz, I applied a function over that data, and then updated the plot. The plot was slower to update, and so updates would queue up in the vispy system (iiuc). Long after the data stopped changing, requiring the plot to stop changing, the plot would keep animating along the whole sequence of updates it hadn't completed yet. Ideally, visual updates that lagged would get dropped, replaced by the most recent. 2 solutions that I haven't been able to implement yet: 1.) Drain vispy's internal queue on each update, so laggards are dropped. 2.) Have vispy somehow signal that an update has completed, so I can pull the next available update, where I can control the dropping of laggards external to vispy. I'm working on those now, if you have any advice!

**Comment by djhoese** [comment]
For the exploratory work, the best way to do something like that would be to use ipython and the `%gui qt` stuff. That handles all the fancy-ness of a "background" Qt event loop.

What backend are you using? I have the most experience with Qt. What you talk about for solution 1 is technically already implemented *if* (I think) VisPy detects duplicate calls to `.update()` before it has finished the current update. For the solution 2, If you aren't already I would consider a background thread for the data reception and pre-processing. Send that data to the GUI/VisPy thread when it is ready. In Qt-land this would be a "signal". If you aren't already doing this this should help. Otherwise you could devise a system where the GUI thread sends a signal to the background thread saying "send me more data" and the background thread sends whatever is in the current buffer to the GUI thread to be drawn.

Also, for speed, it may help if you can reduce the total number of Visuals being drawn. If you are using the Plotting API for example, there may be some overhead (this is something I hope to look at in the next month) because of the way things are structured. If you were to use a simpler line plots (no axes, etc) then it would probably draw faster. This is obviously not going to work if you are trying to make things "pretty", but for a quick and dirty solution this may help.

**Comment by freckletonj** [comment]
I'm struggling to find QThread or socket examples, if you have one, I'd love to check it out, I don't know the Qt side of things.

But, I thought I'd update here, There was no problem with vispy. 

At the boooottom of my call stack, I was reading in a loop from a sytem file-descriptor, and sleeping in that loop, which it shouldn't, because the read blocks anyway, and doesn't need to sleep. Events were buffering at the very bottom on that file pipe (not in vispy visual updates), and not being released timely. You're right, it looks like VisPy does drop "laggard" updates.

Thank you! I like VisPy a lot and I'm trying to make it my new goto for scientific visualization!

**Comment by djhoese** [comment]
No problem. Glad you figured it out! If you ever need more ideas for optimization we're here. Good luck.
