### ISSUE TITLE
Add sphinx-gallery Gallery to the website

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2122]
This is a replacement for #2024 as @larsoner pointed out we should just use sphinx-gallery instead of something custom.

The VisPy website's gallery is rather "custom" at this point: https://vispy.org/gallery.html

It would be nice if we could have:

1. Examples that are actively and automatically tested.
2. Run/tested on either every pull request/push in GitHub Actions or at least on pushes to the `main` branch.
3. Automatically generated one or more pages showing what the examples look like (screenshot) and linked to the code.

See https://github.com/vispy/vispy/wiki/Releasing-new-version-of-VisPy-python-package#update-documentation for how gallery images are run right now.

**Comment by djhoese** [comment]
Circle-CI allows you to see the results?

**Comment by larsoner** [comment]
Yes it has artifacts, and I use circleci-artifacts-redirector-action to produce a link, e.g.:

https://github.com/mne-tools/mne-python/pull/9503#issuecomment-871656901

If you look at the statuses (there are many of them) one of them is "Check the rendered docs here!" which is the circleci-artifacts-redirector-action link that just links to the correct artifact for the given PR commit (which could otherwise be accessed from the main CircleCI page anyway like https://app.circleci.com/pipelines/github/mne-tools/mne-python/8772/workflows/48f35cec-c712-460b-89d5-f5dacefedc47/jobs/30168/artifacts )
