### ISSUE TITLE
Signal from camera or view changes?

### ISSUE THREAD

**Issue by pcpatfire** [vispy/vispy#2147]
Is there any signal emitted when the camera moves or the view changes?

**Comment by djhoese** [comment]
I could have sworn you asked this question on gitter a month ago :stuck_out_tongue_winking_eye: 

Check out the `.transform_change` event:

https://github.com/vispy/vispy/blob/624eb42d61fdb6cd225c55c54866f2a0213c8219/vispy/scene/node.py#L64-L66

I feel like there is another one to connect to but can't seem to find it right now. The above events are on *every* `Node` subclass so that includes all `scene.visuals.*` classes and all cameras and the ViewBox Widget.

**Comment by djhoese** [comment]
If you connect to that event on the "view" of your application then that should be emitted every time the camera updates the view.

**Comment by pcpatfire** [comment]
Yes. It works! It's exactly what I needed. Thank you!

**Comment by djhoese** [comment]
Great!
