### ISSUE TITLE
Prevent render of Visual when widget not visible? (qt-backend)

### ISSUE THREAD

**Issue by pperanich** [vispy/vispy#2207]
Hi, I am working on a data visualization application with Vispy and PyQt5 that utilizes a QTabWidget to display different visuals in each tab. I was wondering if all visuals are still rendered on the GPU even if a subset are not visible in the current tab? In my application, I update several visuals in real-time (~30Hz), but would like to only render the visual(s) (update index buffers, etc.)  that are in the active tab. Any thoughts here would be greatly appreciated.

**Comment by djhoese** [comment]
:thinking: Tough question. I think any timers you are using will still be running and will still call `.update()` which will trigger a draw of any vispy components. Otherwise...I *think* (I assume) that Qt would not call the drawing methods of the VisPy Canvas unless they are being displayed. Bottom line I think is that this is probably more up to your code and how you are updating your vispy visuals than how Qt or vispy operate.

Oh! Any resizing of the main window would also likely trigger redrawing on VisPy's components (resize events are separate from drawing events).

**Comment by almarklein** [comment]
I would expect that Qt will indeed not trigger draw events as long as the widget is not visible. I suppose this should be relatively easy to validate with a print-statement.
