### ISSUE TITLE
Access to uninitialized default_app

### ISSUE THREAD

**Issue by KickerTom** [vispy/vispy#2216]
I am using vispy to render some widgets in PySide2 Qt application. All was working fine until I updated vispy version (last working version was 0.6.6). Now I am getting an error:
```
File "C:\Miniconda3\lib\site-packages\vispy\visuals\line\line.py", line 344, in _prepare_draw
    if "webgl" not in default_app_module.default_app.backend_name:
AttributeError: 'NoneType' object has no attribute 'backend_name'
```
In line.py, I see it is trying to access default_app.backend_name global variable. In previous versions, there was a check for None value, which has disappeared in [this commit](https://github.com/vispy/vispy/commit/766a122a397810ff63b428e328c7c2828a321428).

Am I supposed to somehow initialize the default app now? Or was the check for None omitted by mistake?

**Comment by djhoese** [comment]
Thanks for filing this @KickerTom. Do you have a small example script that triggers this so we can test it more easily? A couple things to note:

1. We no longer have a "webgl" backend so this check isn't even needed anymore.
2. This works for all of the other use cases and examples and automated testing that use this, so there must be something "we" are doing that your script isn't. So while this check could be improved there should be a simple workaround for you in the short term. If you can give us a small script maybe we can figure this out.

@almarklein thoughts?

**Comment by KickerTom** [comment]
Thanks for the fast reaction. It's quite likely the problem is on my side, I am in no way expert on vispy :-). I was just surprised it used to work and now it does not, and the way the check in line.py disappeared.
Anyway, here is a sample I succeeded to extract from my app:
```
from PySide2.QtWidgets import QApplication, QMainWindow
from vispy.scene import SceneCanvas, AxisWidget
from vispy.app import Application

class GraphWidget(object):
    def __init__(self, widgetParent):
        self.canvas = SceneCanvas(bgcolor="white", app=Application("PySide2"))
        self.canvas.create_native()
        self.x_axis = AxisWidget(orientation='bottom', axis_color='black', text_color='black')
        self.canvas.central_widget.add_widget(self.x_axis)

class MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.graph = GraphWidget(self)
        self.setCentralWidget(self.graph.canvas.native)

if __name__ == '__main__':
    appQt = QApplication()
    win = MainWindow()
    win.show()
    appQt.exec_()
```

**Comment by djhoese** [comment]
Ok so good news, I'm able to reproduce this with PyQt5 with switching the imports and the Application creation. So this isn't specific to PySide2 and probably isn't specific to the backend at all. This is overall a bug in that if statement change. It should probably be trying to determine what the current app is rather than the default app. By creating your Application directly you are skipping over all the wrappers in vispy for creating an application that are storing some information (like `default_app`) for later use. This isn't incorrect on your part, it is meant to work based on the docstrings and since you had it working before. Even if you do `app='pyside2'` it will still fail.

Short term workaround is to remove the `app=` line you have an then in your `if __name__` block do:

```python
import vispy
app = vispy.use('pyside2')
```

You can also remove the `create_native` call I think.

Long term, I think we just remove that `if` statement. @almarklein ?

**Comment by almarklein** [comment]
Woops. Sorry for breaking your code @KickerTom!

I think I had assumed that applications are always created via `vispy.use()` so that `default_app` was something we could rely on existing.

> Long term, I think we just remove that if statement. 

Yes, it should basically be `if True` :)

**Comment by almarklein** [comment]
>> Long term, I think we just remove that if statement.
>
> Yes, it should basically be if True :)

PR ready: #2217

**Comment by KickerTom** [comment]
> Woops. Sorry for breaking your code @KickerTom!

Oh, no need to apologize. I am grateful you work on this module and thank you both for such a great support and fast fix.

I tested the fix in the PR and I can confirm it resolves the issue I had. Thank you again.
