### ISSUE TITLE
Fast update of only small part of a visual

### ISSUE THREAD

**Issue by TomBugnon** [vispy/vispy#2365]
Hi all,

I'm really a beginner here and don't really understand how vispy works so forgive me for the possibly silly question (I'm struggling with vispy doc).

I'm modifying an app, in which multiple `vispy.scene.visuals.LinearRegion` visuals are used to overlay color indicating epochs on multiple channels, like this:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/14128078/184926997-281079e7-34c6-428c-a141-aad1b3fb681d.png">
The signal and its color overlay can be very long, and only a short epoch is displayed in the GUI by setting the camera limits. Scrolling happens by moving the camera.

I want to be able to change the color for only a few samples very quickly.
Right now, this is done by modifying the array of colors for each position and calling `set_data`.
```       
# region = vispy.scene.visuals.LinearRegion...
region.set_data(
            color=data_colors
        )
self.region.update()
```

Since this has to be done multiple times (one for each channel) it is very slow.
Is there a faster way to update only a small part of the visual? By modifying data only for the samples of interest? 
I tried the following but it doesn't do anything.
```
self.region.color[stfrom + 1:stend + 1, :] = color
self.region.update()
```

Thanks for your help
Tom

**Comment by djhoese** [comment]
Thanks for filing the issue. I'm not really familiar with the LinearRegionVisual but let's see if I can give you some ideas. So `.color` is a read-only property and the fact that you didn't get an error when trying to assign to an individual slice is just an unfortunate side effect of a numpy array as a property (`.color` is a numpy array copy of the color array and you are assigning to it and then it is thrown away).

Your current way of calling `set_data` is what I would plan on using, but I think there are some optimizations that vispy could make. Looking at the code here:

https://github.com/vispy/vispy/blob/d9cf2a9e0409ee103b6e646f056a2071981a7198/vispy/visuals/linear_region.py#L122-L140

The color array passed by the user is always passed to `np.array` and by default this always copies the data (`copy=True` by default):

https://numpy.org/doc/stable/reference/generated/numpy.array.html

Looking at the other parts of the above code, we can see other choices you can make to avoid additional copies. For example, what is the shape and dtype of your `data_colors` that you are passing? If they aren't 32-bit floats with a shape of `(N, 4)` then change them to be. Next, are you keeping a copy of the `data_colors`, updating a slice, then calling `.set_data`? Or are you creating a new color array every time too?

Lastly, looking at the code above, you could *only* for short term testing probably do:

```python
self.region._color = new_color_array  # <-- must be 32-bit float and (N, 4)
self.region._changed['color'] = True
self.region.update()
```

But please make a PR to update the Visual to pass `copy=False` to `np.array` (@brisvag what do you think?).

Oh, second lastly :wink:, if you are updating a lot of Visuals in a row, don't call `.update()` until you are done calling `.set_data` on all of them. You probably only have to call `.update()` on one of them...and actually you could probably even just call `canvas.update()` since that's what the Visual.update ends up calling.

Good luck.

**Comment by brisvag** [comment]
> But please make a PR to update the Visual to pass `copy=False` to `np.array` (@brisvag what do you think?).

Yup, agree! I would add an argument to `set_data(copy=False)` just like I'm doing in #2350 for `Image.set_data()`. I guess in this case it would apply to all the inputs.

**Comment by djhoese** [comment]
And if I remember correctly we said in #2350 that `copy` being True means "Make a copy immediately" and False means "If you need to modify the data, make a copy, otherwise don't"...right @brisvag ?

**Comment by TomBugnon** [comment]
Thank you so much @djhoese and all for the time you took to help out, I really really appreciate that.

I tried some of your suggestions and figured it out. It turns out the `set_data` call is actually fast enough, even when setting data for the whole recording. The bottleneck here was actually that I reconstructed the RGBA arrays everytime, which is solved by David's suggestion.

For the record, calling `region.update` only once doesn't make much of a difference.

Thanks folks!

**Comment by djhoese** [comment]
FYI I have had this on my TODO list to add a `copy=False` keyword argument to `set_data` since we left this issue open. I finally had time to look into it and just realized that no matter what you do, the internals still repeat the pixels with `np.repeat` so no matter what happens there is going to be a copy of the data. I could do some fancy stuff like never recreating the array unless the number of points changes but I'm not sure it is worth it. If someone wants to add this type of functionality feel free to make a comment here and make a PR.
