### ISSUE TITLE
Vispy Axis starts in wrong position before PAN/ZOOM

### ISSUE THREAD

**Issue by ViNOJ-DAViS** [vispy/vispy#2468]
I am trying to show X Y axis for an image. Axis information of the image shows incorrectly before pan/zoom activity. But as soon as you pan or zoom the image, axis comes out properly.

Below I was able to replicate same issue with Embed Vispy into QT example.

```
import numpy as np
from PyQt5 import QtWidgets

from vispy.scene import SceneCanvas, visuals, AxisWidget
from vispy.app import use_app

IMAGE_SHAPE = (600, 800)  # (height, width)
CANVAS_SIZE = (800, 600)  # (width, height)
NUM_LINE_POINTS = 200


class MyMainWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        central_widget = QtWidgets.QWidget()
        main_layout = QtWidgets.QHBoxLayout()

        self._controls = Controls()
        main_layout.addWidget(self._controls)
        self._canvas_wrapper = CanvasWrapper()
        main_layout.addWidget(self._canvas_wrapper.canvas.native)

        central_widget.setLayout(main_layout)
        self.setCentralWidget(central_widget)


class Controls(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QtWidgets.QVBoxLayout()
        self.colormap_label = QtWidgets.QLabel("Image Colormap:")
        layout.addWidget(self.colormap_label)
        self.colormap_chooser = QtWidgets.QComboBox()
        self.colormap_chooser.addItems(["viridis", "reds", "blues"])
        layout.addWidget(self.colormap_chooser)

        layout.addStretch(1)
        self.setLayout(layout)


class CanvasWrapper:
    def __init__(self):
        self.canvas = SceneCanvas(size=CANVAS_SIZE)
        self.grid = self.canvas.central_widget.add_grid()

        self.view_top = self.grid.add_view(0, 1, bgcolor='cyan')
        image_data = _generate_random_image_data(IMAGE_SHAPE)
        self.image = visuals.Image(
            image_data,
            texture_format="auto",
            cmap="viridis",
            parent=self.view_top.scene,
        )
        self.view_top.camera = "panzoom"
        self.view_top.camera.set_range(
            x=(0, IMAGE_SHAPE[1]), y=(0, IMAGE_SHAPE[0]), margin=0)

        self.x_axis = AxisWidget(
            axis_label="X Axis Label", orientation='bottom')
        self.x_axis.stretch = (1, 0.1)
        self.grid.add_widget(self.x_axis, row=1, col=1)
        self.grid.padding = 0

        self.x_axis.link_view(self.view_top)
        self.y_axis = AxisWidget(
            axis_label="Y Axis Label", orientation='left')
        self.y_axis.stretch = (0.1, 1)
        self.grid.add_widget(self.y_axis, row=0, col=0)
        self.y_axis.link_view(self.view_top)


def _generate_random_image_data(shape, dtype=np.float32):
    rng = np.random.default_rng()
    data = rng.random(shape, dtype=dtype)
    return data


if __name__ == "__main__":
    app = use_app("pyqt5")
    app.create()
    win = MyMainWindow()
    win.show()
    app.run()

```
Below is the screenshot which shows wrong axis labelling.

![Screenshot from 2023-04-10 19-05-09](https://user-images.githubusercontent.com/25582939/231435306-81e63323-95cf-4cdf-a144-8d44b5427ceb.png)

Once we do a pan or zoom on the canvas the axis corrects itself.

Kindly let me know what is to be done to get proper axis for the image.

**Comment by djhoese** [comment]
FYI here's a smaller version of the code that still shows the issue:

```python
import numpy as np

from vispy.scene import SceneCanvas, visuals, AxisWidget
from vispy.app import use_app

IMAGE_SHAPE = (600, 800)  # (height, width)
CANVAS_SIZE = (800, 600)  # (width, height)


class CanvasWrapper:
    def __init__(self):
        self.canvas = SceneCanvas(size=CANVAS_SIZE)
        self.grid = self.canvas.central_widget.add_grid()

        self.view_top = self.grid.add_view(0, 1, bgcolor='cyan')
        image_data = _generate_random_image_data(IMAGE_SHAPE)
        self.image = visuals.Image(
            image_data,
            texture_format="auto",
            cmap="viridis",
            parent=self.view_top.scene,
        )
        self.view_top.camera = "panzoom"
        self.view_top.camera.set_range(
            x=(0, IMAGE_SHAPE[1]), y=(0, IMAGE_SHAPE[0]), margin=0)

        self.x_axis = AxisWidget(
            axis_label="X Axis Label", orientation='bottom')
        self.x_axis.stretch = (1, 0.1)
        self.grid.add_widget(self.x_axis, row=1, col=1)
        self.grid.padding = 0

        self.x_axis.link_view(self.view_top)
        self.y_axis = AxisWidget(
            axis_label="Y Axis Label", orientation='left')
        self.y_axis.stretch = (0.1, 1)
        self.grid.add_widget(self.y_axis, row=0, col=0)
        self.y_axis.link_view(self.view_top)


def _generate_random_image_data(shape, dtype=np.float32):
    rng = np.random.default_rng()
    data = rng.random(shape, dtype=dtype)
    return data


if __name__ == "__main__":
    app = use_app("pyqt5")
    canvas = CanvasWrapper()
    canvas.canvas.show()
    app.run()
```

**Comment by djhoese** [comment]
Ok I've tried a few things as tests, not necessarily long term fixes, but even still I get this:

![image](https://user-images.githubusercontent.com/1828519/231531067-21ee7bc7-5c54-48a6-b94c-507cdb735d67.png)

The Y-axis seems decent, but the X-axis is still wrong (image origin at about the -100 mark). I added a:

```
if self._linked_view is not None:
    self._view_changed()
```

to the `_update_axis()` method of the AxisWidget to get this. It seemed to me that the `_view_changed` method wasn't getting called *after* the resize event of the final Window being shown, only before.

I also tried changing the `view.scene.transform.changed.connect` call in the AxisWidget to include `position='last'` with the assumption that the view changed should happen after all other transform changes have happened. But that didn't seem to have an effect.

**Comment by ViNOJ-DAViS** [comment]
> FYI here's a smaller version of the code that still shows the issue:
> 
> ```python
> import numpy as np
> 
> from vispy.scene import SceneCanvas, visuals, AxisWidget
> from vispy.app import use_app
> 
> IMAGE_SHAPE = (600, 800)  # (height, width)
> CANVAS_SIZE = (800, 600)  # (width, height)
> 
> 
> class CanvasWrapper:
>     def __init__(self):
>         self.canvas = SceneCanvas(size=CANVAS_SIZE)
>         self.grid = self.canvas.central_widget.add_grid()
> 
>         self.view_top = self.grid.add_view(0, 1, bgcolor='cyan')
>         image_data = _generate_random_image_data(IMAGE_SHAPE)
>         self.image = visuals.Image(
>             image_data,
>             texture_format="auto",
>             cmap="viridis",
>             parent=self.view_top.scene,
>         )
>         self.view_top.camera = "panzoom"
>         self.view_top.camera.set_range(
>             x=(0, IMAGE_SHAPE[1]), y=(0, IMAGE_SHAPE[0]), margin=0)
> 
>         self.x_axis = AxisWidget(
>             axis_label="X Axis Label", orientation='bottom')
>         self.x_axis.stretch = (1, 0.1)
>         self.grid.add_widget(self.x_axis, row=1, col=1)
>         self.grid.padding = 0
> 
>         self.x_axis.link_view(self.view_top)
>         self.y_axis = AxisWidget(
>             axis_label="Y Axis Label", orientation='left')
>         self.y_axis.stretch = (0.1, 1)
>         self.grid.add_widget(self.y_axis, row=0, col=0)
>         self.y_axis.link_view(self.view_top)
> 
> 
> def _generate_random_image_data(shape, dtype=np.float32):
>     rng = np.random.default_rng()
>     data = rng.random(shape, dtype=dtype)
>     return data
> 
> 
> if __name__ == "__main__":
>     app = use_app("pyqt5")
>     canvas = CanvasWrapper()
>     canvas.canvas.show()
>     app.run()
> ```

**Comment by djhoese** [comment]
Ok I think I've figured this out. It took me more time than I'm willing to admit, especially considering I think I already knew some of this. I added print statements everywhere and followed the series of events to figure out what events were happening and in what order.

The two basic concepts involved are the size of the widgets and the connection between the size/transform of the ViewBox where the Image is drawn and the AxisWidgets. The size and position of the widgets is represented by a `.size` property but also a `.rect` (short for "rectangle"). Each widget has these properties including the GridWidget that is positioning all of its child widgets. These things don't normally change except in two cases: when the window is resized or when widgets are added/removed from a "layout" like the GridWidget. The window can be resized by the user which triggers a resize event, but it is also resized when the main window is first drawn. When we first create our widgets they get default sizes or are told their sizes by the user, but then everything is resized/reinitialized when the window is first drawn on the screen.

The other concept is where the ViewBoxWidget has a camera and that camera changes (the user pan/zomming) the widget transform. This change is connected to a method on the AxisWidget that updates the `.domain` of the AxisVisual. It does this by taking its current extents via the `.rect` property (remember, its size and position) and transforming them with the ViewBox's transform. So if the axis widget is stretch from position 0 to position 800 in the Window then we transform these pixel coordinates through the ViewBox to mean "what does pixel location 800 mean in the ViewBoxes coordinate system".

The problem I noticed is when the window is first displayed and we get a Resize event, the event handler calls resize event handlers (the functions/methods handling the event) in the order the widgets were created/added to the event emitter. So in your current version of the script that means that we updated the `.rect`/`.size` of the Grid, which then updates its children in order so that means the ViewBox, then one AxisWidget, then the other. The problem is that the update of the ViewBox size triggers a "view changed" event which tells the AxisWidgets to update. The AxisWidgets then go on to update their `.domain` based on the size information they have and the current transform of the ViewBox. **BUT** the AxisWidgets haven't had their `.rect`/`.size` updated yet. So the calculation of what the axis should show is done with the wrong size but the right viewbox transform so the end result is just wrong.

The simple workaround is to create and the axis widgets *first* before the viewbox. The longer term solution is probably to disconnect and reconnect the resize event handlers of the AxisWidget when `link_view` is called and make sure that its resize event handler is called *before* the viewbox.

**Comment by djhoese** [comment]
Hm maybe this can't be fixed internally in vispy. It really seems it has to do with the order the widgets are added to the **grid** not when they are created. Here's the new relevant portion of the `__init__` method:

```
        image_data = _generate_random_image_data(IMAGE_SHAPE)
        self.image = visuals.Image(
            image_data,
            texture_format="auto",
            cmap="viridis",
            # parent=self.view_top.scene,
        )

        self.x_axis = AxisWidget(
            axis_label="X Axis Label", orientation='bottom')
        self.x_axis.stretch = (1, 0.1)

        self.y_axis = AxisWidget(
            axis_label="Y Axis Label", orientation='left')
        self.y_axis.stretch = (0.1, 1)

        self.grid.add_widget(self.x_axis, row=1, col=1)
        self.grid.add_widget(self.y_axis, row=0, col=0)
        self.view_top = self.grid.add_view(0, 1, bgcolor='cyan')
        self.image.parent = self.view_top.scene

        self.view_top.camera = "panzoom"
        self.x_axis.link_view(self.view_top)
        self.y_axis.link_view(self.view_top)

        self.view_top.camera.set_range(
            x=(0, IMAGE_SHAPE[1]), y=(0, IMAGE_SHAPE[0]), margin=0)
```

This works for me because the `view_top` is added *after* the axes widgets. Note that the camera has to be declared/set **before** the views are linked otherwise they are linked/attached to the wrong transform for changes.

**Comment by ViNOJ-DAViS** [comment]
Thank you @djhoese  for your assistance with this issue. Your input was invaluable and I can't thank you enough.
