### ISSUE TITLE
how to draw a polygon with holes?

### ISSUE THREAD

**Issue by ericyan71** [vispy/vispy#2471]
is there a easy method to draw a polygon with holes？such examples using shapely.geometry.Polygon is best, thanks.

**Comment by djhoese** [comment]
@brisvag are you a mesh expert? Can this be done with VisPy's MeshVisual?

**Comment by brisvag** [comment]
Not really ^^' I know some folks had issue before in napari when trying to use our `Shapes` layer (which uses meshes) to get shapes with holes. Nothing technically prevents this from working, but I don't think plygons were designed with this in mind, and meshes are a bit more involved to use because you have to manually provide faces.

**Comment by ericyan71** [comment]
yes, I find MeshVisual can used to draw polygon with hole, thanks!
