### ISSUE TITLE
How can I scale vispy coordinate frame?

### ISSUE THREAD

**Issue by jamestran11** [vispy/vispy#2476]
Externally, I am given separate point clouds, and separate translation values to align the pointclouds. I'm able to align them in vispy, however, in order to do so, i need to multiple my translation values by 1000. How can I change vispy frame to be the same scale is my original data, ie use my original translation values to align them in vispy?

**Comment by djhoese** [comment]
Do you have some example code for what you're doing? It sounds like you should be able to do:

```python
my_visual.transform = STTransform(scale=(1000, 1000, 1000))
```

But I'm really not sure I"m understanding your situation so sorry if this is completely wrong or doesn't make sense.

**Comment by jamestran11** [comment]
```
            x = x+transX*1000
            y = y+transY*1000
```

Hi! sure, so below is a example code snippet of what i'm doing. I'm replaying point cloud data in the update function. In the nested for loop, each  x,y point "pt" has already been translated by the code above. If I remove the *1000 multiplier, the point clouds only move a small amount, and do not align. With the *1000 correction, the point clouds align as i want them to. 
```
canvas = vispy.scene.SceneCanvas(keys='interactive', show=True, bgcolor='grey')
view = canvas.central_widget.add_view()
scatter = visuals.Markers()
axis = visuals.XYZAxis(parent=view.scene)
view.camera = 'panzoom'  

def update(event):
    pos = []
    for sequence in listOfScannerPtcldSequences:
        ptcld = sequence.pop(0)
        for pt in ptcld:
            pos.append(pt)

    pos = np.asarray(pos)

    scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, .95), size=5)
    view.add(scatter)

```

**Comment by djhoese** [comment]
So is this a scale issue or a translation issue? You could do something like this:

```
from vispy.visuals.transforms import STTransform

...

# right after creating scatter:
scatter.transform = STTransform(scale=(1000, 1000, 1000))
```

So that multiplies all your coordinates by 1000, but that may not be what you need based one where you're adding the translation currently. There is also a `translate=(x, y, z)` keyword argument to the above transform for translating the coordinates linearly.

If you do end up using the STTransform and need to update these scaling/translations during update, I highly recommend using the properties of the transform rather than creating a new STTransform:

```
scatter.transform.scale = (x, y, z)
```

As this will only update the scaling parameters on the GPU rather than recompiling a whole new transform/shader.

**Comment by jamestran11** [comment]
Ok, it looks like i need to add the translation somewhere else for this to work. But it looks promising,
