### ISSUE TITLE
why line not perfect

### ISSUE THREAD

**Issue by ericyan71** [vispy/vispy#2481]
I write test code to show Line with method=gl|agg, connect=segments|strip seprately, but I found the line is not perfect, when using gl and segments, there are some gap around the connecting position, but when I use agg，the line connecting to first point are difference from others, here is my codes:

environment:
winpython:  3.11
vispy: 0.12.2

```
import numpy as np
import shapely.geometry
from vispy import scene


if __name__ == '__main__':
    canvas = scene.SceneCanvas(bgcolor=(0.1, 0.1, 0.1))
    view = canvas.central_widget.add_view()
    view.camera = scene.cameras.PanZoomCamera(aspect=1)
    canvas.show()

    clr = (0.5, 1, 1)
    s = shapely.geometry.Point(0, 0).buffer(5, resolution=6)
    x = list(s.exterior.coords)
    segs = np.array([x[i//2] for i in range(len(x)*2)][1:-1])
    clr1 = np.array([clr for i in range(len(segs))])
    scene.Line(pos=segs, color=clr1, connect='segments', method='gl', antialias=True,   parent=view.scene, width=10)

    clr = (1, 0.5, 1)
    s = shapely.geometry.Point(11, 0).buffer(5, resolution=6)
    x = np.asarray(s.exterior.coords)
    clr2 = np.array([clr for i in range(len(x))])
    scene.Line(pos=x, color=clr2, connect='strip', method='agg', antialias=True,   parent=view.scene, width=10)

    view.camera.set_range()
    canvas.app.run()
```
![1](https://user-images.githubusercontent.com/22901866/235395637-dd202883-98a9-4e00-ad31-eb9636343ff7.png)

I want the line connecting without gap and gradation, thanks.

**Comment by djhoese** [comment]
Could you please print out the coordinates you get for one of the circles (since I assume they are the same between the circles just shifted over)? For the AGG case, it seems vispy does specify the cap/join behaviors in the code, but doesn't give access to these properties for the user:

https://github.com/vispy/vispy/blob/525504ab61744ef5a50fa06b38298a35f30126c7/vispy/visuals/line/line.py#L411-L415

The simple solution for AGG might be to repeat the first coordinate at the end of the strip of coordinates.

For the 'gl', I'm not really sure what's going on. I do know that setting line width for the `gl` method is not well supported across GPUs (deprecated feature of OpenGL) so we generally advise users to use AGG when they need to manipulate the width of lines.

**Comment by ericyan71** [comment]
@djhoese thanks. the right circle is shifted to (11, 0). setting the line width to 10 is just  for seeing  the problem more clearly, the result is same if I set the line width to 1.  I give two group of picture here, notice that the cirle radius changed to 4, right cirlce's center set to (10, 0)
![1](https://user-images.githubusercontent.com/22901866/235554596-7e8271cb-3fc5-4f29-8b9c-c3f8bff01ec4.png)
![2](https://user-images.githubusercontent.com/22901866/235554686-7f7299ff-2324-4108-882c-2ef3a088f598.png)
we can see, although I set width to 1, the gap and the gradation is still exist.

**Comment by djhoese** [comment]
Any ideas @rougier?

**Comment by rougier** [comment]
The gl line on the left seems to be aliased. Is that the case ? As for the right, I think the problem is the closure of the strip. Don't you have a "closed" parameter?

**Comment by rougier** [comment]
Just saw the "antialias=True". Can you try with false for the GL line ?

**Comment by rougier** [comment]
For the connect method, you can try to give vertices indices instead of "strip". If this works, then vispy code should be fixed.

**Comment by rougier** [comment]
Ok. So doubling start/end point might solve the problem. For closed strip, the agg `closed` keyword should be handled by the visual

**Comment by ericyan71** [comment]
ok,  when djhoese help me to solve another problem, I found this issue is also solved, thanks !
