### ISSUE TITLE
the quality of the saved image

### ISSUE THREAD

**Issue by JintaoLee-Roger** [vispy/vispy#2520]
Hi!

I use the following code to save the render image:
```python
from vispy.gloo.util import _screenshot
.....
# method1
screenshot = _screenshot()
# method2
screenshot = self.render() # in a sence
io.write_png('out.png', screenshot)
```

My question is how can I change the quality of the saved image?

Besides, I seed a `dpi` parameter with different values to `scene.SceneCanvas`, while the render image seems to no change. What is the purpose of this parameter？

Hope to get a reply！ Thanks!

**Comment by djhoese** [comment]
Good question. I don't know off the top of my head except to make your SceneCanvas/viewport larger. If/when you visualize this on your own monitor does it look to be a "good enough" quality? As far as I can tell (searching the repository for "dpi" on github) the DPI parameter passed to the Canvas is only used for things like font text rendering and converting inches to number of pixels (in the case of mimicking matplotlib's figure size in inches functionality).

If increasing the size of your render and then shrinking it down (either with Pillow or another tool) then it may be that the quality of your Visuals is not detailed enough to produce a better image. What Visuals are you drawing/visualizing?

**Comment by JintaoLee-Roger** [comment]
Can I understand it like this: I rendered a canvas with dimensions `(n1, n2)`, and then saved it. So, the highest quality image I can obtain is this one. I can perform degradation operations to reduce the image quality, but I cannot obtain a higher quality image than this on this canvas. Therefore, the highest quality image I can obtain is an image with dimensions of the canvas matching my screen size.

The need I'm looking for is similar to the `imshow()` and `savefig()` functions in matplotlib. I feel that there's a distinction between rendering for display purposes and rendering for image saving. The rendering used for saving images should not be limited to my screen dimensions.

**Comment by djhoese** [comment]
It depends on what is actually going on in your use case. @rougier would probably no more and could hopefully provide some more information on this topic.

If you are viewing a visualization on your screen in the GUI you can look at the quality of the result and determine if this looks "good enough" This involves the algorithms used underneath to, for example, draw a line. How VisPy (or any software) does this is a balance of execution/drawing time, developer time, and quality of the line drawn. VisPy has one (two technically) ways of drawing lines on the screen and they may not be drawing the best anti-aliased line. Or if you're drawing a 3D mesh, maybe the polygons/triangles being drawn could be done better or could have more vertices specified or something similar.

As for `imshow` and `savefig`, it's been a long since I've looked at matplotlib's internals, but I think they have a lot more freedom to draw lines with much better CPU-rendered implementations (AGG library for example). `imshow` is not drawing pixel, by default it is interpolating between image/data pixels. I think when you call something like `savefig` things are being redrawn to whatever size is needed and with DPI involved in the drawing of those things. OpenGL (at least the way VisPy is using it) isn't doing this...I think.

And I don't think you are limited to the size of your screen. The functions you mentioned using for getting a screenshot array can be given the size of the view you want to draw on (as arguments). I think you can give this any size you want.

**Comment by JintaoLee-Roger** [comment]
Well, I note that it depends on my OS. The behavior of the `render` function is inconsistent between macOS (macbook air, M2) and Linux (Ubuntu 22.04).

Two methods to save the render image:

```python
class Mycanvas(scene.SceneCanvas):
    def __init__(self, size, ...):
        scene.SceneCanvas.__init__(self, size=size, ...)
    .....
    # method 1
    def on_key_press(self, event):
        if event.text == 's':
            print(f'In class, canvas size: {self.size}')
            screenshot = self.render()
            print(f'screenshot size: {screenshot}', screenshot)
            vispy.io.write_png('inclass.png')


def show_data():
    ........
    canvas = Mycanvas(size=(6000, 5000))
    
    # method 2
    canvas.show()
    img = canvas.render()
    print(f'out of class canvas size: {canvas.size}')
    print(f'img size: {img.shape}')
    vispy.io.write_png('outofclass.png', img)
```

On linux, I got:
```
out of class canvas size: (6000, 5000)
img size: (5000, 6000, 4)
In class, canvas size: (2560, 1312)
screenshot size: (1312, 2560, 4)
```

On MacOS, I got:
```
out of class canvas size: (2560, 1314)
img size: (1314, 2560, 4)
In class, canvas size: (2560, 1312)
screenshot size: (1312, 2560, 4)
```

That means I am unable to obtain an image of the specified size when the size is larger than the screen size on MacOS (can on Linux).

**Comment by djhoese** [comment]
There is the size of the Canvas which you are specifying and the size that you can pass to the `render` and `_screenshot` calls:

https://github.com/vispy/vispy/blob/6b68262412f6f31b5d9911f3f919953a5bb63b30/vispy/scene/canvas.py#L221

I've never used it, but I would think theoretically that this would let you render onto any size array.

**Comment by JintaoLee-Roger** [comment]
Got it! Thank you very much!
