### ISSUE TITLE
No setter for some properties of Arrow or Line after instantiation

### ISSUE THREAD

**Issue by bjamturley** [vispy/vispy#2557]
Assuming an arrow object is created like so:

```
    new_arr = scene.visuals.Arrow(
        pos=np.array([source, target]),
        arrows=np.array([[source[0], source[1], target[0], target[1]]]),
        parent=view.scene
    )
```

Attempting to update the position (or color and arrow pos) properties after the fact is met with this error: `AttributeError: property 'pos' of 'Arrow' object has no setter`. Is this by design? For my current use case I need to alter these properties dynamically.

**Comment by djhoese** [comment]
I don't know if I'd say "by design". A lot of vispy's visuals were developed out of a necessity for them and the user experience and consistency with other visuals was an after thought. In general Visuals provide a `.set_data` method to combine all types of "updates" in a single method and the Arrow provides this.

This is due to the complexity of how updating a visualization works where if it was a property like `.pos = new_data` we could be making position incompatible with the previous properties of the Visual (ex. array of colors), but we also usually want the GUI to be redrawn right away when we do this setting. So in general the availability of property-style setters depends on the needs of the Visual. Hopefully this helps, but `.set_data` is probably what you need for now.

**Comment by bjamturley** [comment]
Gotcha, I missed that in the documentation. I was a little thrown off because some of the other properties like arrow_color have to be modified directly and because other objects like ellipse don't have the method. Very much appreciate the quick response though, thanks for developing this out.

**Comment by djhoese** [comment]
Yeah consistency is a problem in vispy. It could be fixed or cleaned up but it would require more work than the limited maintainer time can handle. It would also likely break backwards compatibility.
