### ISSUE TITLE
visual.Image, and vispy.plot.image, not working on Linux with Mesa driver

### ISSUE THREAD

**Issue by izaid** [vispy/vispy#598]
This is really weird. I have a fresh installation of Linux Mint (which should behave as Ubuntu). I've got the latest VisPy from Git, and the examples involving images (basics/visuals/image_visual.py, basics/scene/image.py, and basics/plotting/image.py) all don't work. Everything else, including the gloo/animate_image.py, seems to work fine.

This seems like there is a bug in the Image visual. I also just tried the latest VisPy on my Mac, and the Image visual there is fine.

Edit: Using Python 2.7.

**Comment by StephenWest** [comment]
Hello,  

I appear to have tripped up on the same issue?   Mandelbrot.py works, but I get a blank black canvas for  atom.py, a blank white canvas for donut.py, and graph.py has  edges but no point markers.   No error messages in all cases.

I would like to try your suggested Mesa fixes, but the glir.py line numbers above don't make sense to me.   Can you please provide a code snippet around each change candidate, or should I just install the Nvidia driver?  

I am running Ubuntu under VMWare fusion on a MAC.   The code works for me under OSX.
My vispy.__version__ is 0.4.0-dev  cloned from github a few hours ago

vispy.sys_info() reports:

Platform: Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty
Python:   2.7.6 (default, Mar 22 2014, 22:59:56)  [GCC 4.8.2]
Backend:  PyQt4 (qt)
pyqt4:    ('PyQt4', '4.10.4', '4.8.6')
pyqt5:    None
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       wxPython 3.0.0.0
egl:      EGL 1.4 (Gallium) Mesa Project: OpenGL OpenGL_ES OpenGL_ES2 OpenVG
_test:    None

GL version:  u'2.1 Mesa 10.1.3'
MAX_TEXTURE_SIZE: 16384

Thanks

**Comment by izaid** [comment]
If I remember correctly, the Mesa fix was to not use Mesa!

**Comment by Eric89GXL** [comment]
Yeah, that should work. I'm confused, though, because Travis CI uses Xvfb,
which must render using Mesa. It's possible we aren't catching the point
rendering with our tests, though, and that's why the error is undetected
there.

Eric

**Comment by StephenWest** [comment]
It seems that I am stuck with Mesa, because that's what VMWare tools uses to map to the OSX host.

**Comment by Eric89GXL** [comment]
@StephenWest I can translate @almarklein's original suggestions to new line numbers. He was talking about suggestions to get textures working properly using `glEnable(GL_TEXTURE_2D)` because there were issues with images, but it sounds more like you're having problems with point sprites, so these commands (from https://github.com/vispy/vispy/blob/master/vispy/gloo/glir.py#L388) are more likely to be relevant:

```
            # Desktop, enable sprites
            GL_VERTEX_PROGRAM_POINT_SIZE = 34370
            GL_POINT_SPRITE = 34913
            gl.glEnable(GL_VERTEX_PROGRAM_POINT_SIZE)
            gl.glEnable(GL_POINT_SPRITE)
```

In any case, a couple of locations you could try would be:

1. Add it in `GlirParser._gl_initialize(...)` here:

    https://github.com/vispy/vispy/blob/master/vispy/gloo/glir.py#L392

2. Try `Program._pre_draw`:

    https://github.com/vispy/vispy/blob/master/vispy/gloo/glir.py#L707

@almarklein also suggested looking at `GlirTexture.activate`, but I doubt you are having a texture problem so I omitted that one.

Can you try #723 to see if you have a failing test on the `vispy/visuals/tests/test_markers.py` file? You can even just try running the file. It would help us isolate the problem to being with point sprites. Travis is happy with that PR, which should mean that point sprites are working fine there even though it's using Mesa, though.

**Comment by StephenWest** [comment]
Thanks !  

There does seem to be a problem with Point Sprites.  I am testing with demos/gloo/display_points.py

gl_PointCoord in the fragment shader appears to always have the value (0.0, 0.0) 

Nailing its value to (0.5, 0.5) get me lots of colored squares.
Nailing its value to (0.8, 0.8) gets me lots of grey squares

So everything else seems to be working okay?

The code fragment that you proposed was already present in the _gl_initialize(...)  method.  The unmodified definition of this method in class GlirParser starting from L381 is:  

def _gl_initialize(self):
        """ Deal with compatibility; desktop does not have sprites
        enabled by default. ES has.
        """
        if '.es' in gl.current_backend.__name__:
            pass  # ES2: no action required
        else:
            # Desktop, enable sprites
            GL_VERTEX_PROGRAM_POINT_SIZE = 34370
            GL_POINT_SPRITE = 34913
            gl.glEnable(GL_VERTEX_PROGRAM_POINT_SIZE)
            gl.glEnable(GL_POINT_SPRITE)

However, _gl_initialize() never gets called from display_points.py.  

I set a break point, and gl_pre_draw doesn't get called either?

The assert from line 18 of  #723 fails.
This file was not present in my code, so I created it from the web page.

I plan to look into this more in the morning...

Steve

**Comment by Eric89GXL** [comment]
If I add a `raise RuntimeError` inside `GlirParser._gl_initialize()`, I hit in in both `display_points.py` and the little test script I wrote in #723, so at least on my system `_gl_initialize` does get called by `display_points.py` at some point.

**Comment by StephenWest** [comment]
Thanks Eric,

My bad! Finger trouble on my end. I set the breakpoint in the wrong
incarnation of glir.py.  _gl_initialize() does get called.

Can you give me some pointers on how to debug gl_PointCoord being stuck at
(0,0)?

**Comment by Eric89GXL** [comment]
I'm not too experienced with debugging problems with point sprites, but if you can get your hands on the mesa demos you could try e.g. `/usr/lib64/mesa/point-sprite` to see if that at least works. @almarklein @rougier any idea why point sprites might fail?

You could also try other packages that have point sprite support to see if their rendering works, e.g. glumpy, or even some C-based program or demo. It would help isolate whether the problem is vispy-specific or MESA/virtualization-specific.

**Comment by StephenWest** [comment]
I suspect that it's Mesa!  I'll see if I can prove it...
