### ISSUE TITLE
Too many backends?

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#601]
I'm just wondering whether we need to support so many backends, especially backends that are rarely used (SDL2? GLUT? even Pyglet?). More useless backends = more code = maintenance burden = test burden = etc.

**Comment by Eric89GXL** [comment]
GLUT has always been difficult to maintain, isn't well tested, and lacks several capabilities that the other backends have -- okay with people if we axe that one?

**Comment by almarklein** [comment]
I would not mind. It would be a relief in a way.

**Comment by Eric89GXL** [comment]
Closing for now. I think each current backend we have is useful in its own way currently. The GUI backends are useful for GUI-package compatibility, SDL2 is useful because SDL2 is a very easy way to get other nice support (e.g., sound), and GLFW is easy for us to get support on any system. We can revisit this if we incur too much overhead in the future, but it seems pretty stable for now.
