### ISSUE TITLE
Multi-Threading Support?

### ISSUE THREAD

**Issue by alexjc** [vispy/vispy#632]
I'm using iPython from the console window that I spawn in a separate thread, with two VisPy canvases (one for displaying OpenCV camera, and another for visualizations).

Until earlier today when I pulled ~283 changes, I could create markers/lines/polygons from separate threads in the iPython console (or %run scripts) without issues — although in retrospect it may be related to #630.  I had never considered the fact it shouldn't work from a thread, though from my C++ work I know that OpenGL can only reliably be used from a single thread, and ideally the main one.

Today having got latest, it crashes in a variety of ways.

This ticket is more of a question.  Assuming the VisPy app is running from the main thread, should interacting with VisPy visuals from other threads work?  If so, it's broken :-) If not, then I can work around it with some kind of command queue.

Thanks!

**Comment by djhoese** [comment]
Coming to this 6 years later...

I've read this entire thread as best I could and agree with just about everything @campagnola has said. My background (as far as this goes) is in both user GUI applications for analyzing satellite data and also I've built PyQt GUIs in the past with 0.5 second update rates of 10s to 100s of time series variables being updated in a background thread and then plotted with matplotlib.

Getting around the GUI event loop versus ipython loop appears to have been answered so we'll let that go.

Updating a buffer from a background thread may work but I think it should be avoided if at all possible. A solution I've typically gone with is sharing memory (a numpy array) that gets updated from the background thread where the thread then notifies the main GUI thread that new data is available to use. Basically everything outside of GUI-related tasks can be done by the background thread (including putting data in memory where the main thread can get it) while the main GUI thread handles everything else. I think anything doing asynchronous updates of GPU data while the main GUI thread could be using it is asking for trouble.

It sounds like most people here (based on what I know) are either not actively using vispy anymore or have found a usable solution. Or at least I hope you have in the past 6 years. Closing for now. Anyone finding this issue that would like to comment, please re-read the above thread for the *very* valid concerns (execution order, other options, etc) that were provided before commenting here and asking how it could be done. Otherwise consider creating a new issue for your particular problem/question.
