### ISSUE TITLE
Update installation instructions: propose Anaconda as the recommended Python distribution

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#691]

**Comment by almarklein** [comment]
Why? Vispy is pure Python, so I see no reason to put forward one particular Python distro. Also we do not even provide conda packages for Vispy yet...

**Comment by rossant** [comment]
VisPy still depends on NumPy which is far from being pure Python. Our users still need a good Python distribution that makes it easy to install NumPy and some other optional dependencies like PyQt4. Look for example at the discussion in #690.

Providing a conda package would be a good idea indeed!

**Comment by almarklein** [comment]
That is True, but then I would word it a bit differently, otherwise we might give the illusion that Vispy itself is difficult to install. E.g. we could mention the dependencies and then that (ana)conda is an easy way to obtain these.

**Comment by rossant** [comment]
Oh yes sure, and emphasize that VisPy itself is (currently) pure Python.

**Comment by MikHulk** [comment]
Hi,

The problem is not really vispy but the dependance with PyQt. PyQt it is a so big Framework. So it is impossible or very hard to install it into a virtualenv because it is dependant itself with a lot of libraries written in C. However it is possible to install Vispy in Virtualenv but PyQt may be installed directly on the OS. And the packages OS  have to be make accessible in the virtualenv. With --sytem-site-packages option.
Like this : virtualenv --system-site-packages my_path

**Comment by Eric89GXL** [comment]
@MikHulk vispy actually works with a number of different graphics libraries, including Pyglet, which is pure python, and GLFW, which is hopefully fairly easy to install on each platform.
