### ISSUE TITLE
Get rid of on_initialize

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#700]
I would like to get rid of the `initialize` event and the `on_initialize` callback in all VisPy. Having several ways of initializing the scene is quite confusing (constructor, `on_initialize`, first `on_draw`, etc.).

Is it possible to stick to a single option in the whole codebase + examples + documentation? If so, the first `on_draw` might be the way to go. I think the best way to do it would be to add an `is_first_draw` boolean in the `on_draw`'s `event` argument. Then, we would recommend users to use the following pattern:

```python
canvas = Canvas()

@canvas.connect
def on_draw(event):
    if event.is_first_draw:
        canvas.program = Program(...)
        ...
    canvas.program.draw()

```

and we would use this pattern in all `gloo` examples. An alternative solution could be:

```python
canvas = Canvas()

def initialize():
    canvas.program = Program(...)
    ...

@canvas.connect
def on_draw(event):
    if event.is_first_draw:
        initialize()
    canvas.program.draw()

```

I'm not sure how the scene stuff works but I suppose it is similar.

Doing this would also make the IPython WebGL backend more stable, cleaner, and it might even offer a way to fix the multiple-show problem.

WDYT?

**Comment by Eric89GXL** [comment]
I see the canvas constructor, `on_initialize`, and `on_draw` as all serving different purposes. The constructor sets up the Python variables; `on_initialize` sets up OpenGL variables; and `on_draw` is called every time a redraw is needed. I don't quite see how it simplifies things to put `first_draw` in the `on_draw` callback, if it is pretty much just a renamed `on_initialize` event... so I'm -1 on that.

IIRC we originally needed `on_initialize` because the OpenGL context wasn't available during canvas creation. It's possible that with GLIR queues, we could get rid of `on_initialize` altogether, since the OpenGL flushing is delayed until the first draw anyway. If this is true, then we don't need `event.is_first_draw` at all, and can just put all initialization in the constructor, which would be nice. @almarklein do you think this would work? If so, I'm +1 on deprecating `on_initialize` and just putting all of our OpenGL initialization into the canvas constructor.

**Comment by rossant** [comment]
We can't always puthe initialization in the constructor, look at my two examples above.

**Comment by Eric89GXL** [comment]
I assume @lcampagn had a reason to use `first_draw` instead of going with `on_initialize` -- if we have to use that pattern for functional reasons, then I agree we should probably find a way to do it consistently everywhere.

**Comment by Eric89GXL** [comment]
Or maybe we should actually have a `first_draw` event, as well as a `draw` event. That would avoid having to do a conditional on every draw call. Somebody somewhere is going to be keeping track of whether or not the draw is the first one, so it is just as easy to emit a `first_draw` event as it is to emit a `draw` event with a boolean set. This seems more consistent to me. Then the code could look something like:
```
@canvas.connect
def on_draw(event):
    # draw some things

@canvas.connect
def on_first_draw(event):
    # do some drawing inits
   on_draw(event)
```

**Comment by Eric89GXL** [comment]
Although if the first draw bits can't be easily separated from the drawing bits, that won't work... maybe the boolean is just easier.

**Comment by lcampagn** [comment]
In general, anything that is currently in `on_initialize` can just be placed in `__init__` instead because gloo ensures that the GL calls are queued until the correct context is active. For static visualizations, this is probably the only change that needs to be made.

Visuals, on the other hand, are quite dynamic--they may change their appearance at any time in response to user requests. This can cause buffers and other GL state to be invalidated, requiring it to be refreshed at the next draw. So in general it does not make sense to have `on_initialize` OR `on_first_draw`. Instead, the `draw` method checks that it has all of the necessary buffers/state before each draw. Example:

    class MyVisual(Visual):
        def __init__(self):
            # A texture that is valid for the life of the visual
            self._texture = gloo.Texture2D(data)

            # A buffer that may be updated any time during the life of the visual
            self._vbo = None

        def draw(self, event):
            self._tex = self._texture
            if self._vbo is None:
                self._generate_vbo()
            self.program.vbo = self._vbo
            self.program.draw()

        def set_vertices(self, verts):
            """User-initiated event that invalidates vertex buffer.
            The VBO is _not_ regenerated at this time because set_vertices
            might be called multiple times before the next draw()."""
            self._vbo = None
            self._vert_data = verts

**Comment by rossant** [comment]
OK, so @lcampagn your point is that having a `first_draw` event doesn't really make sense because what matters is whether gloo object X is initialized or not, not whether that draw is the first or not?

I think that makes sense, in which case we don't really need anything special in the code, do we? We just have to update all examples that use `initialize`.

Will there be a lot of code to remove in VisPy if we want to get rid of `initialize` altogether? Does anyone wants to do it, or shall I (try to) do it?

**Comment by lcampagn** [comment]
I think it makes sense to leave `initialize` in the backends because some users familiar with OpenGL will expect it to be there. We can discourage its use by the examples.

**Comment by rossant** [comment]
OK so in this case I can just update the examples and maybe documentation, if that's good with you @Eric89GXL

**Comment by Eric89GXL** [comment]
Yeah, we can leave the event in place but never use it in examples or our
code (other than a few existing tests). It will die off naturally that way
:)
