### ISSUE TITLE
Purge open PRs

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#702]
I believe we have too many open PRs, including some very old ones. I propose we either close those which are too old, or finish and merge the others. I'd prefer to have almost no open PRs the day we start the March sprint...

**Comment by Eric89GXL** [comment]
+1 I fully agree. Leaving PRs open is problematic for a number of reasons. First, the code gets stale, so that the contributors and reviewers forget what the issues are and it is difficult to make progress. Second, seeing really old PRs with lots of comments is likely to discourage new contributors. Third, it prevents code from really being used, tested, integrated, and built upon that otherwise could be.

It's difficult to get PRs reviewed and merged in a timely manner because we are all busy people. However, IMHO quick PR review turnarounds are critical for open-source project progress, in some cases perhaps a higher priority than than working on our own code, if the choice came down to doing one or the other...

**Comment by rossant** [comment]
Also merging an old PR might be harder (rebase/conflicts hell)...

**Comment by almarklein** [comment]
+1

**Comment by almarklein** [comment]
Ah, and now I understand why my mailbox is suddenly flooded with 120+ emails related to vispy :)

**Comment by Eric89GXL** [comment]
I think we took care of this :)

**Comment by campagnola** [comment]
If by "we" you mean "Eric Larson, PR Slayer".
