### ISSUE TITLE
Instructions for testing VisPy canvas on Travis

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#711]
It would be great to put instructions somewhere detailing how to unit test VisPy visualizations on Travis. Typically, I have a project on GitHub that uses py.test and Travis. One of my tests displays a custom visualization created with VisPy (using `canvas.show(); app.run()`). Running `make test` locally opens a window, which has to be closed manually.

On Travis, I'd like at least the GLIR commands to be emitted, even if they are not interpreted by anything. This will test my data baking logic, for example.

What are the exact steps to make this work correctly on Travis? (putting the steps in this issue's discussion would be enough at first)

**Comment by rossant** [comment]
And to go a bit further: are there ways to test user interaction? (like click at (300, 400), drag the mouse button 20 px left, etc.)

**Comment by Eric89GXL** [comment]
For visuals testing, take a look at #706. It actually checks the outputs to make sure they are consistent. If your visuals are stable enough to do that, you can use it. It uses a threshold for a correlation (default 0.95), so even if there is a little bit of variability it's considered okay.

Also, all of the examples get tested -- at least that they run without errors or warnings -- by `python make test examples`, so that's another layer of testing we do.

Button presses are faked natively for each Canvas here, which isn't quite what you want:

https://github.com/vispy/vispy/blob/master/vispy/app/tests/test_app.py

Instead you'd want to call e.g. `canvas.backend._vispy_mouse_press(...)` directly, which would simulate what happens when `vispy` gets events from the backend. See this for an example:

https://github.com/vispy/vispy/blob/master/vispy/app/backends/_qt.py#L326

**Comment by rossant** [comment]
Thanks!

For headless rendering stuff, I assume the `before_script` bit in travis is enough and can be reused as is in another project?

**Comment by Eric89GXL** [comment]
Yeah you just need to spin up an `Xvfb` instance to get a functional but slow X server, which I've done for several projects that need it.

**Comment by rossant** [comment]
Is there a way to not install any backend on travis? I get a `RuntimeError: Could not import any of the backends`

**Comment by Eric89GXL** [comment]
Are you asking if it's possible to render without having any backends installed? Currently the answer is no -- that's what the EGL push is for, but it's not there yet.

If you're asking if we test the no-backend case / support, we do -- there is a `deps=minimal` Travis condition which does not install any backend, and the tests should run fine in this case. Any tests that require a backend should be decorated with `requires_application` to avoid hitting the error you describe.

**Comment by rossant** [comment]
OK so it looks like I have to install a backend in order to test views on travis.

**Comment by Eric89GXL** [comment]
Yeah. Is this for a different repo, or for a `vispy` branch you're working on that isn't a PR yet...?

**Comment by rossant** [comment]
No it's another project

**Comment by Eric89GXL** [comment]
Pyglet `tip` is probably the easiest, you can get the line from our `.travis.yml`

**Comment by rossant** [comment]
How do I close the canvas after, say, 1 second? Right now `canvas.show()` freezes travis obviously...

**Comment by Eric89GXL** [comment]
Take a look at our example testing code, it probably does something very close to what you want. What actually gets executed for each example is in `_script`:

https://github.com/vispy/vispy/blob/master/vispy/testing/_runners.py#L166

If you change the `for _ in range(5)` to `for _ in range(60)`, it should run for ~1 sec (assuming draws are very fast).

**Comment by Eric89GXL** [comment]
In other words, something like this should work:
```
with canvas as c:
    t0 = time.time()
    while (time.time() - t0) < 1.:
        c.update()
        c.app.process_events()
        time.sleep(1./60.)
```

**Comment by rossant** [comment]
Excellent, it worked, thanks!

**Comment by lcampagn** [comment]
@rossant, want to write up a section on unit testing for the documentation?

**Comment by rossant** [comment]
@lcampagn I don't have much time right now, unfortunately, but that's definitely something doable during the sprint
