### ISSUE TITLE
Vispy Windows XP Compatibility

### ISSUE THREAD

**Issue by JasonD1980** [vispy/vispy#715]
When trying to run a Vispy Application in windows xp project will not start due to fault "Attribute Error: function 'SetProcessDPIAware' not found".  First instance traced back to "vispy\ext\gdi32plus.py line 165"  this line was commented out and program ran again and produced the same fault but pointed at "vispy\util\dpi_win32.py line 13" this line was also commented out and the program finally loaded.  Exhaustive testing is not yet complete but program is basically functional.

It appears the "SetProcessDPIAware" API is not supported in windows XP and only partially supported in windows vista and later, see....  https://msdn.microsoft.com/en-us/library/dn469266(v=vs.85).aspx and .... https://msdn.microsoft.com/en-us/library/dn302122(v=vs.85).aspx.

Further testing needs to be done to see whether Vispy is obtaining proper DPI settings.  
reference: http://www.experts-exchange.com/Programming/Languages/Scripting/Python/Q_21794611.html

**Comment by Eric89GXL** [comment]
Thanks for the report! Seems like you have a decent handle on the issues -- are you up for submitting a fix?

The easiest (and crappiest) solution would just be to detect XP's presence, and not use the selected functions in that case, returning some sensible default (e.g. 92 or 96). We could start there, and later add more complete support, or just add more complete/better support from the start, depending on your willingness to pursue this. I'm happy to help or even fix it myself if you're not up for it.

FWIW Vispy is able to get the DPI from my machine running Windows 8.1. I haven't tested it on other operating systems, since that's all I have easy access to right now. Perhaps @rossant has?

**Comment by rossant** [comment]
No I just have a Windows 8.1 machine (and Windows 10 preview in a VM).

You'll see on gitter some pointers on how to possibly update the code so that it also work with XP (but this requires more testing on XP).
