### ISSUE TITLE
Call on_resize at first draw

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#762]
The viewport should be correctly set when you first initialize a canvas.

**Comment by Eric89GXL** [comment]
I think some backends do this automatically and some don't.

**Comment by nippoo** [comment]
I'm refactoring/modifying a few examples to assume that on_resize *isn't* being called at first draw. It seems to be slightly non-deterministic on certain platforms: at least for me on the glfw backend, on_resize seems to be called around the first draw about 50% of the time (!!)

It seems slightly cleaner to me to *not* call on_resize, and make sure everything is correctly initialised in the __init__(). Doesn't seem particularly intuitive. If not, where do we call the on_resize() - it should be a blocking call, before the first draw, because people might want to intialise some variables there?

**Comment by rossant** [comment]
can this be closed?

**Comment by Eric89GXL** [comment]
Closing, feel free to reopen if it's a problem in the future
