### ISSUE TITLE
Make volume rendering work in WebGL

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#813]
WebGL doesn't support `while` loops. The GLSL volume rendering code will have to be rewritten a bit. See http://www.atmind.nl/?p=623
cc @almarklein @izaid 

Same problem for mandelbrot and ray tracing examples.

**Comment by izaid** [comment]
At least there's a reasonable workaround for the while loops -- I'll give this a shot when I get a chance.

**Comment by djhoese** [comment]
@izaid Are you still working with OpenGL or WebGL projects? What are you current plans for this type of work? Are you still available to work on vispy?

**Comment by izaid** [comment]
@djhoese Hello after 5 years! TBH, I think there are now many good solutions for volume rendering in WebGL. IPyVolume or vtk.js are the first projects that come to mind. Where do you think VisPy fits into this ecosystem now?

**Comment by djhoese** [comment]
I agree ipyvolume is probably way ahead of vispy in being able to support this type of functionality. I still consider VisPy's jupyter widget experimental and I'm not sure the GLIR architecture will perform well (at least this is my assumption so far) in a jupyter notebook. That said, it would be nice to be feature complete so as improvements are made we know we're covering all use cases.

Just wanted to check what your interest was now since 5 years ago you were interested :wink:

**Comment by almarklein** [comment]
This is now out of scope; the (volume) rendering will now be at the server and the resulting image displayed in the browser.
