### ISSUE TITLE
Glir queues flush when wrong canvas is active

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#880]
I ran into an issue while working on image tests. Basically, there are two canvases in use during a test--one is used to draw the test, the other is a GUI for the user to audit the results. Each canvas has a context with many GL objects, and many overlapping GL identifiers between the two contexts. This is OK so far, but some of the image tests have code like this:

```
    with TestingCanvas() as c:
        ellipse = visuals.Ellipse(pos=(75, 35, 0), radius=20)
        c.draw_visual(ellipse)
        assert_image_approved("screenshot", 'visuals/circle1.png')
```

The trouble is that at the time we call `c.draw`, there is a good chance that the _other_ canvas is actually active, and that this call will cause the context's queue to be dumped into the wrong context. Let's discuss ways this can be fixed.. I'd rather allow this kind of use to function correctly (or at least output a useful error message) because this situation is very difficult to debug given the indirection that occurs in glir. So:

* Can we somehow ensure that a queue is never flushed into the wrong context?
* Can `canvas.draw` activate its own context to allow this kind of use?

**Comment by campagnola** [comment]
See https://github.com/campagnola/vispy/commit/7b99faa573f52a0950c3c71d6bc836dca6cac141
for an approach to the second problem.

For the first problem, here's an important chunk of code (`gloo/program.py:442`):
```
    def draw(...):
        . . .
        # Get the glir queue that we need now
        canvas = get_current_canvas()
        assert canvas is not None
        
        # Associate canvas
        canvas.context.glir.associate(self.glir)
```

What happens when a program gets associated with multiple contexts? Is that allowed, or should we ensure that the program can only be associated once?

**Comment by almarklein** [comment]
I think that everything should work correctly if you consistently use `canvas.gloo.glFoo` instead of `gloo.flFoo`. Not sure if we do this in the visuals yet, though...

**Comment by campagnola** [comment]
So should we make `vispy.gloo` private, then?

**Comment by almarklein** [comment]
No, because there's still all the gloo objects in there :)  We could consider phasing out the `vispy.gloo.glFoo` functions though, perhaps starting with a deprecation warning...

**Comment by campagnola** [comment]
So there is no `Canvas.gloo.Program` ? When I call `program.draw()`, how can I be sure that the correct context is active?

**Comment by almarklein** [comment]
All commands end up at the correct context automatically, except for two situations, where it's responsibility of the caller to ensure that the correct canvas is active: `Program.draw()` and `FrameBuffer.activate()`.

**Comment by rossant** [comment]
@almarklein canvas has no attribute  ̀gloo`... Using `gloo.func` results in the OpenGL calls being sent to the wrong canvas. What's the fix?

**Comment by almarklein** [comment]
Ah, my mistake: it's `canvas.context.func()`

**Comment by rossant** [comment]
thanks @almarklein !

**Comment by Eric89GXL** [comment]
@campagnola I think you fixed this one so I'm closing

**Comment by campagnola** [comment]
There is one thing remaining:  we need to have glir queues check (or enforce) that their associated context is active before they are flushed.

**Comment by karlcz** [comment]
@almarklein, Is there documentation or an example for how the caller can "ensure that the correct canvas is active" for program draw and framebuffers?  I think I may be running into this as discussed in #1090 where I want to run two canvases. These are multi-pass renderers that use the `with fbo ...` idiom to run some programs in an FBO and then run the final pass to the screen using the FBO textures.

**Comment by almarklein** [comment]
@karlcz that should be `canvas.set_current()`

**Comment by karlcz** [comment]
Is there something else I need to do to register a texture, framebuffer, or program instance with a particular canvas and gloo context?  I took simple examples like examples/basics/gloo/hello_fbo.py or examples/tutorial/gloo/texture_precision.py and it works to just modify the main function to instantiate two instances of the custom Canvas before calling app.run(). But, when I do this on my much more complicated volume renderer application, I get errors in one of the two canvas instances, where the attempt to activate an FBO fails with an error like `RuntimeError: Cannot FRAMEBUFFER object 34 because it does not exist`.  

I already switched over to use the canvas.context.foo functions instead of gloo.foo for the GL state manipulation.  I even did the canvas.set_current() during my custom canvas initialization (after base class init) in case the texture, framebuffer, or program creation was implicitly interacting with the current context.

Is there some other synchronization I need to do?  I assumed that only one canvas would be executing at a time out of the app event loop.  My real application has much more expensive shading going on (ray-cast volume rendering) so I could imagine a race condition exhibiting itself where the trivial example apps have very short shader program runs...

**Comment by karlcz** [comment]
Well, I finally I found the source of my problem! My canvas and its subordinate objects had one place where I mistakenly created class members instead of instance members holding gloo.VertexBuffer and gloo.IndexBuffer instances. Somehow sharing these between canvases was causing that other error `RuntimeError: Cannot FRAMEBUFFER object 34 because it does not exist`, even though each canvas had its own FBO objects already.

**Comment by Eric89GXL** [comment]
@karlcz thanks for the update

**Comment by khbilen** [comment]
I ran into a very similar problem in the very first tutorial program, the Flat Colored Square example with gloo. I receive assert canvas is not None error in program.py where the canvas is None. The window briefly appears at the beginning, and then disappears, and I get the error message. Could it be realated? How can I proceed? (I am using Python 3.2, installed vispy 0.4.0)

**Comment by Fuco1** [comment]
Same issue here as what @khbilen describes.

**Comment by Fuco1** [comment]
@khbilen seems like the code in this PR fixes the issue https://github.com/vispy/vispy/pull/782

all I had to do was to add

```python
from vispy.gloo.context import FakeCanvas
c = FakeCanvas()

on top of my program

**Comment by khbilen** [comment]
@Fuco1 I had tried a similar approach. I updated the source code program.py in the vispy.gloo. At the canvas assertion step I created a FakeCanvas. But it did not work. I added the Fakecanvas on top of my code. It did not work either. But now I notice, I receive another error: Function glBindFramebuffer not present in context. It is because I think the context is rather simple.

**Comment by almarklein** [comment]
Closing this. @Fuco1 your problem seems unrelated to the original question. Ik looks like your gl driver is not of sufficiently high version.

**Comment by ghpenguin** [comment]
Hi, 

I'm running 64 bit Devuan Linux. 
vispy 0.4.0 

When I ran the example code, 
http://www.labri.fr/perso/nrougier/teaching/opengl/scripts/hello-world-gloo-scale.py

It was flooding error message without drawing the box.
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 277, in 'calling callback function'
  File "hello-world-gloo-scale.py", line 34, in display
    program.draw(gl.GL_TRIANGLE_STRIP)
  File "/usr/local/lib/python3.4/dist-packages/vispy/gloo/program.py", line 444, in draw
    assert canvas is not None
AssertionError

Adding the two lines removed the error.

from vispy.gloo.context import FakeCanvas
c = FakeCanvas()
