### ISSUE TITLE
Interactive prompt degrades performance

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#945]
Observe:
```
$ python examples/demo/gloo/game_of_life.py --vispy-fps
51.7 FPS
62.5 FPS
$ python -i examples/demo/gloo/game_of_life.py --vispy-fps
>>> 16.9 FPS
19.1 FPS
19.1 FPS
19.2 FPS
19.1 FPS
19.3 FPS
19.1 FPS
19.1 FPS
19.2 FPS
9.8 FPS
1.0 FPS
1.0 FPS
```

We didn't have this problem when using PyQt's interactive prompt support.

**Comment by Eric89GXL** [comment]
I think I've observed this at some point, too. We should definitely investigate to figure out why it degrades. Maybe the profiling code will be helpful here.

**Comment by bollu** [comment]
@Eric89GXL : how does one explicitly profile vispy? do you use the standard tools like ```cProfile```? Or does vispy have built in profiling tooling?

**Comment by Eric89GXL** [comment]
@bollu check out the discussion here:

https://github.com/vispy/vispy/pull/860

It would be great if someone could add a section to the wiki detailing a good procedure, @bollu if you have time please do it

**Comment by bollu** [comment]
it looks like ```inputhook.py``` is the culprit. Specifically, lines 66 to 72.

```
try:
    t = time()
    while not stdin_ready():
        self.app.process_events()

        used_time = time() - t
        if used_time > 10.0:
            sleep(1.0)
        elif used_time > 0.1:
            sleep(0.05)
        else:
            sleep(0.001)
except KeyboardInterrupt:
    pass
return 0
```

If I'm reading this right, you take the time from when you've had no user interaction. 
You start out an event loop, ticking vispy once (```app.process_events```), then measure the time since the last user interaction has taken place. If it's over 10 seconds, then you sleep for a second. If it's over 0.1 seconds, then you sleep for 0.05 seconds until you start the next frame.

I'm not sure as to why this is required (the ```git blame``` isn't terrible insightful either, and neither is the iPython docs). Removing the ```sleep``` brings back performace up to the mark.

Just for the record, here is the profiler info:


###python  examples/demo/gloo/game_of_life.py###
```
         129275 function calls (123341 primitive calls) in 3.317 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    3.166    3.166 _default_app.py:57(run)
        1    0.000    0.000    3.166    3.166 application.py:106(run)
        1    0.000    0.000    3.166    3.166 _qt.py:212(_vispy_run)
        <omitted>
FPS:

56.5 FPS
60.0 FPS
60.0 FPS
60.0 FPS
60.0 FPS
```

###BEFORE: python -i examples/demo/gloo/game_of_life.py###
```
       71052 function calls (68086 primitive calls) in 5.248 seconds

 Ordered by: cumulative time

 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      1    0.002    0.002    5.086    5.086 inputhook.py:60(_vispy_inputhook)
    132    4.803    0.036    4.803    0.036 {time.sleep}
    132    0.001    0.000    0.277    0.002 application.py:73(process_events)
    <omitted>
FPS:

20.9 FPS
18.9 FPS
18.9 FPS
19.1 FPS
19.1 FPS
18.9 FPS
```

Clearly, it spends most of it's time sleeping within ```inputhook.py```


###AFTER: python -i examples/demo/gloo/game_of_life.py###
         8001357 function calls (7995731 primitive calls) in 13.080 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.812    0.812   12.927   12.927 inputhook.py:60(_vispy_inputhook)
   785793    0.316    0.000   10.475    0.000 application.py:73(process_events)
   785793    0.777    0.000   10.159    0.000 _qt.py:207(_vispy_process_events)
   785793    3.427    0.000    6.168    0.000 {built-in method processEvents}
	<omitted>
FPS:

54.7 FPS
60.0 FPS
60.0 FPS
60.0 FPS
60.0 FPS
60.0 FPS

```

**Comment by bollu** [comment]
Also, I'll add a section to the wiki once I read the associated docs and play around with it a bit more :)

**Comment by campagnola** [comment]
Thanks @bollu!
The `sleep` calls are there to prevent pegging the CPU when nothing else is happening. It's actually quite tricky to write an event loop that is both responsive and does not consume too much CPU time. Generally the UI toolkits do a good job of this (and `inputhook.py` is clearly not) so it would be better if we can allow the UI event loop to run, and then check on the TTY periodically using a timer.

**Comment by campagnola** [comment]
For Qt, at least, this should be simple:  http://doc.qt.io/qt-5/qtest.html#qWait
Might look something like:
```
    while not stdin_ready():
        used_time = time() - t
        if used_time > 0.1:
            # never have more than 300 ms TTY delay
            QTest.qWait(0.3)
        else:
            QTest.qWait(0.05)
```

**Comment by bollu** [comment]
ah, @campagnola, yeah, we do this in games too. But, the technique is slightly different.

If you wish to render at, say, 60 FPS, then figure out the time per frame ```1.0 / 60 seconds = 16.66 milliseconds```. Next, time _each frame_ that you have. If it's below 16.66 seconds, then sleep the difference minus some padding (to account for syscall overhead). Otherwise, don't sleep. Would that not work in this case too? or did I mis-understand what you meant?

**Comment by campagnola** [comment]
That's not quite what I mean. In the code example above, python is running the actual event loop and allowing us to process GUI events as long as the user is not typing on the console. So if we wrote something like 
```
while not stdin_ready():
    app.process_events()
```
then we would get very low-latency response to user input in both the console and the GUI, but the CPU would be pegged at 100% the entire time. So it is tempting, then to add a little sleep time:
```
while not stdin_ready():
    app.process_events()
    time.sleep(0.005)
```
However even this will use a surprising amount of CPU, and at the same time it limits the maximum framerate we can achieve because `sleep()` is unconditional. You can keep trying different sleep times, or try dynamically updating the sleep time like `inputhook.py` does now, but ultimately you're much better off letting the GUI decide when to sleep and when to work, because it will have a very highly optimized inner event loop (that is, you should call `app.run()` instead of `app.process_events()`).

The trouble is that Python is already running an event loop, and there does not seem to be a way to visit the console TTY input handler from inside the GUI event loop. Qt offers a solution in the form of the `qWait` function (this is like calling `app.run()` for a predefined duration), but other backends probably do not offer the same feature.

I wonder if it would be easier to write our own command prompt.. these issues are exactly why `pyqtgraph.console` was written.

**Comment by Eric89GXL** [comment]
-1 on writing our own command prompt, I think it would be limiting for a lot of use cases, and greatly increases our coding burden

For now my vote is to optimize our solution, then also add special cases for backends that support it (maybe only Qt for now)

**Comment by Eric89GXL** [comment]
I can take a stab at fixing this since I have access to Windows, Linux, and OSX machines of varying speed capabilities

**Comment by Eric89GXL** [comment]
Or @bollu you can try to fix it and I can just give you usage reports :) I wonder if using 0.001 ms sleep will be too short, it seems to work well on my desktop at least (CPU usage is negligible)

**Comment by bollu** [comment]
@Eric89GXL: I'd like to give this a stab while I'm waiting for collections to stabilize so I can work on plotting :)

**Comment by bollu** [comment]
@campagnola how to we detect which backend vispy is currently using?

**Comment by Eric89GXL** [comment]
If you have a Canvas you can get it from there, if you don't then you can do something like this:
```
>>> from vispy import app
>>> this_app = app.use_app()
>>> this_app.backend_name
'PyQt4'
```

**Comment by bollu** [comment]
thanks
