### ISSUE TITLE
automatically launch vispy in webgl mode if in notebook

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#977]
This could be a nice usability improvement, to have vispy automatically pickup the webgl back end if its running in a notebook.

AFAIK, this is possible to detect since ipython provides a config object that can be used to query status.

If there's a consensus on this, I'll try and write a pull request for this

**Comment by hadim** [comment]
That would be nice. You can use this:

```python
def in_ipython():
    try:
        __IPYTHON__
    except NameError:
        return False
    else:
        return True
```

**Comment by bollu** [comment]
I don't think that's enough: that only tells you if you're in ```ipython``` or not, not if you're in the notebook. For that you'd need to load the cfg object that ipython provides I guess

**Comment by rossant** [comment]
-1: I often use desktop backends in the notebook, to have multiple popups
also the webgl backend is too experimental at this point to be enable by default
finally, the kernel doesn't know whether you are in a notebook, and you'd need some ugly hacks to detect that

i'd rather have an explicit `enable_notebook()` function, like in matplotlib, mpld3, and all other plotting libraries that work in the notebook

**Comment by Eric89GXL** [comment]
@rossant we basically have that already with `use_app('ipynb_webgl')`, right?

**Comment by rossant** [comment]
yes, i imagine we could save a few characters and improve tab completion discovery with such a function
+ we might want to enable other stuff in the notebook later

**Comment by bollu** [comment]
@Eric89GXL yes, but that's not very nice to use, right? API wise :) It's too much internal detail (what is an "app"? why do I need to invoke "webgl"? stuff like that)

**Comment by Eric89GXL** [comment]
There should be one (preferably obvious) way of doing things as much as
possible. In this case maybe it's not obvious. At the same time I'd rather
not increase the number of ways. So my problem with this is, say someone
wants to use the Pyglet or SDL backend, what function should they use?
Should we make separate functions for those?

Maybe we can rename a function, or its arguments, or move it to a different
namespace to make things clearer. Can you come up with an API that would be
more intuitive in light of these issues?

**Comment by rossant** [comment]
`enable_notebook()` could enable not only the app backend but also things like JavaScript modules etc, so it would not be equivalent to just `use_app`.

The notebook backend is quite different from all the other backends (desktop) so I don't see a problem with that.

**Comment by Eric89GXL** [comment]
I agree that functionally it operates differently (remote communication etc.), but we have actually constructed it to be as equivalent as possible to other backends in terms of the experience for end users. FWIW I see this as an advantage. Sure the backend does more complex processing, but all we have to do to use it is `use_app('ipynb_webgl')` to use it. If and when we needed more backend-specific options, they could go in the `use_app` function, especially since other backends might also need extensions at some point. Actually such options would probably go in the Canvas constructor, but we can cross that bridge later...

To put it slightly differently, consider what would happen if we added some other backend that we think of as being "different" from our desktop ones. Maybe we find a way to embed our plots in a matplotlib axes instance, do we use `enable_matplotlib()`? We have talked about using GLFW as our main backend -- what if `qt` adds some cool remote features that we want to incorporate, do we add an `enable_qt_remote()` function? I don't find this as simple as the current solution, even if the current naming is bad. I think of all of these as being particular instances of instantiating an application to use, even if what they do under the hood is quite different.

**Comment by almarklein** [comment]
On one hand I agree with Eric, but I also recognise that users are going to forget (and thus having to look up) the "ipynb_webgl" name (at least I do). For desktop use, people actually do not need it in general, because Vispy is smart enough to select a good default app, this is not so much the case for the notebook (because the IPython folks deliberately made it hard to detect whether you're running in a notebook). Therefore, in this case I think practicality beats purity, and I would be in favour of a `enable_notebook()` function, that simply calls `use_app()`.

**Comment by Eric89GXL** [comment]
what if we changed the name to `use_backend` or `enable_backend()`, then the name would be given in the docstring? or maybe we should just change the name of the backend to `notebook` (we can keep an alias to the old one if we want) so it would just be `enable_backend('notebook')`? That to me is almost the same and prevents future namespace pollution.

**Comment by QuLogic** [comment]
Have you thought of creating an IPython extension instead? One that automatically switches backends and tunes whatever else might be necessary. It would work something like [holoviews](https://ioam.github.io/holoviews/) and should be familiar to any IPython user (e.g., `%load_ext vispy.ipython`). (Note: I am basing my understanding of the holoviews extension on the one line that appears at the beginning of the linked page, but that seems reasonable.)

**Comment by Eric89GXL** [comment]
+1 for that solution, it seems like the nicest way to integrate. For now I guess all it would do is call `use_app`. Any takers for a PR? @bollu if you have time?

**Comment by bollu** [comment]
@Eric89GXL I'm not sure as to what the plumbing needed for that is. I'll definitely take a look and outline what you need for this though.

**Comment by bollu** [comment]
@QuLogic do we need a extension or a magic command?

Like, matplotlib is just ```%matplotlib``` [like so](https://ipython.org/ipython-doc/dev/interactive/magics.html#magic-matplotlib), which is considered a "magic function", that is given access to ```iPython's``` context when it is called.

However, an extension is way more extensive and gives close to complete control over the iPython shell. [docs for extension](http://ipython.org/ipython-doc/dev/config/extensions/#ipython-extensions).

I'm guessing we would want it to be an extension for maximum future flexibility, but I still felt that this could be argued upon.

**Comment by QuLogic** [comment]
I'm not sure you can create a magic command without installing an extension in the first place, but I didn't look too deeply into that side of it.

**Comment by bollu** [comment]
@QuLogic if you load a module, it works. So I'm assuming somewhere in the pipeline of vispy, we check if we're running inside ipython, and then load the custom magic command module. [the docs are here](https://ipython.org/ipython-doc/dev/config/custommagics.html)

**Comment by rossant** [comment]
I think the extension is the way to go

**Comment by bollu** [comment]
@rossant very well. I'll try and get a pull request (WIP) that's a stub in an hour or so. We can move the discussion there, agreed?
